### ISSUE TITLE
Compiling for Windows SCons Documentation Doesn't Mention dev_build and dev_mode Flags

### ISSUE THREAD

**Issue by jonathansekela** [godotengine/godot-docs#10018]
**Engine source version:** Godot 4.4 Dev.
**Documentation source:** Godot 4.3 English

**Issue Description:**
The instructions to setup the godot engine using SCons on the contribution section of the godot docs doesn't mention dev_build=yes or dev_mode=yes. Not using these flags can cause builds and debuggers to not load symbols and breakpoints in many code files, making it difficult to both dig through and test changes to code.

![image](https://github.com/user-attachments/assets/b55c5364-19ee-41f0-a5ac-cf05115b11ac)

**URL to the documentation page:**
https://docs.godotengine.org/en/stable/contributing/development/compiling/compiling_for_windows.html#running-scons

**Comment by jonathansekela** [comment]
I think we should either add an additional Note underneath the one present in the image, or update the wording in this section to mention the dev_* flags and what they do.

**Comment by tetrapod00** [comment]
The [Linux](https://docs.godotengine.org/en/latest/contributing/development/compiling/compiling_for_linuxbsd.html) and [macOS](https://docs.godotengine.org/en/latest/contributing/development/compiling/compiling_for_macos.html) pages also don't give instructions for using `dev_build` or `dev_mode`. The macOS page does *mention* dev_build in passing. None of the three pages mention `dev_mode`. Strangely, the [Android page](https://docs.godotengine.org/en/latest/contributing/development/compiling/compiling_for_android.html#building-the-export-templates) does mention both `dev_mode` and `dev_build`.

Presumably you are supposed to read the [Introduction to the buildsystem](https://docs.godotengine.org/en/latest/contributing/development/compiling/introduction_to_the_buildsystem.html) page first before an OS-specific page, which does introduce `dev_mode` and `dev_build`. I do agree that adding at least a mention of `dev_build` or `dev_mode` to the individual pages makes some sense, as the OS-specific pages *can* be read on their own as complete instructions. Maybe we just need to link to the introduction page.

A solution to this issue should consider at least the three desktop editor compilation pages (Windows, Linux, macOS),, and add similar information to each, rather than adding new information piecemeal as people notice it for whichever OS they are using.

**Comment by jonathansekela** [comment]
I did the same thing as you @tetrapod00 when I first started delving into the engine. I realize there should be a balance between making information too redundant and making it too hard to find in the documentation. Putting everything on every page will make the documentation useless, but this feels like a good idea to add to the desktop setup pages.

I'll move forward by adding a blurb to compiling_for_linuxbsd.rst, compiling_for_macos.rst, and compiling_for_windows.rst. If you all prefer a different method, I'm more than open to suggestions.

**Comment by tetrapod00** [comment]
Adding a blurb to each page sounds good to me (but I'm only a single contributor and the maintainers may have a different opinion).

My first instinct would be to add another `Tip` or `Note` box in the [Windows/Running Scons](https://docs.godotengine.org/en/latest/contributing/development/compiling/compiling_for_windows.html#running-scons) section, that has information about `dev_build` and/or `dev_mode`. There's already a tip box about using production flags, so a box about dev flags makes sense.

I think these pages have more of a requirement to be comprehensive than brief, since in many cases a single user will only be reading the page for their own OS. So I wouldn't personally worry about adding information about a very common scons flag like this.
