### ISSUE TITLE
Incorrect description of Transform3D empty constructor in the documentation

### ISSUE THREAD

**Issue by mikhailvaliev** [godotengine/godot-docs#10138]
It says here in the Constructor descriptions 

https://docs.godotengine.org/en/stable/classes/class_transform3d.html#class-transform3d-constructor-transform3d

That constructor `new Transform3D()`  Constructs a Transform3D identical to the IDENTITY

This is wrong, the output transform matrix contains all zeroes.

**Comment by tetrapod00** [comment]
Are you using C#? In C#, it *is* initialized to zeros instead of IDENTITY. See [the Transform3D section of C# API differences to GDScript](https://docs.godotengine.org/en/latest/tutorials/scripting/c_sharp/c_sharp_differences.html#transform3d). It's also noted in [description of the Transform3D class itself](https://docs.godotengine.org/en/stable/classes/class_transform3d.html#description) that there are "notable differences".

This might be worth noting in the constructor description itself, but I think we currently avoid that for some reason.

**Comment by mikhailvaliev** [comment]
Yes I am using C#. Thank you for clarification and useful links.
