### ISSUE TITLE
Outdated page: Godot release policy | Release support timeline

### ISSUE THREAD

**Issue by etherealxx** [godotengine/godot-docs#10224]
For 4.3 it says release date of `June 2024 (estimate)` meaning this hasn't been updated since said version is released. Same goes for Godot 3.6.

https://docs.godotengine.org/en/stable/about/release_policy.html#release-support-timeline

**Comment by tetrapod00** [comment]
Thanks for reporting. This is fixed in latest/master in (https://github.com/godotengine/godot-docs/pull/9755 and https://github.com/godotengine/godot-docs/pull/9929), but the changes have not been cherrypicked back to 4.3 yet.

There are plans to remove this information from the docs and move it to the website because as you can see, it's hard to keep it up to date across multiple maintained docs versions.

**Comment by tetrapod00** [comment]
Closing, as these have been fixed in latest and are pending cherrypicks. Thanks for the report!
