### ISSUE TITLE
Discord Link expired or wrong in the Gudot Documentation

### ISSUE THREAD

**Issue by Tr33Bug** [godotengine/godot-docs#10306]
**Your Godot version:**
-
**Issue description:**
When clicking on the Discord link in the documentation introduction page I get a "Invalid Invite - This invite may be expired, or you might not have permission to join." message from discord. 

**URL to the documentation page:**
https://docs.godotengine.org/en/stable/about/introduction.html#before-you-start

**Comment by tetrapod00** [comment]
Hi, thank you for reporting this bug! It's already fixed in the ["latest" version of the docs](https://docs.godotengine.org/en/latest/about/introduction.html) by https://github.com/godotengine/godot-docs/pull/10193, so now we're just waiting for the changes to be "cherrypicked" or backported to the stable version, which happens in batches.

**Comment by tetrapod00** [comment]
Closing, as this is fixed in latest and pending a cherrypick. Thanks!
