### ISSUE TITLE
Coding Style Update methods.py

### ISSUE THREAD

**Issue by BrandiCook** [godotengine/godot-docs#10310]
4.3 Stable

Coding style fixes

In the master directory, the methods.py file has many small code smells. For example, missing or inconsistent comments style:
![Image](https://github.com/user-attachments/assets/52c0a904-c1b6-4caa-b472-7f8f21cca973)

I am submitting this issue because I would like to contribute and help fix some of these!

Thanks,
Brandi

**Comment by tetrapod00** [comment]
Welcome! Thanks for you interest in contributing. 

I'm assuming you're talking about [methods.py](https://github.com/godotengine/godot/blob/master/methods.py) in the main repo? 

Code style improvements are great, but they may not be a good place to start contributing for a couple reasons:
- Code style is subjective and the Godot codebase has its quirks, so a code smell to you may actually be intentional.
- We like to avoid making pure style changes in small individual PRs, since it can make the git history noisier. So even if a change is good, it *may* not be a good change as a single small PR.

Before making PRs for these changes, you might want to ask in the [contributors chat](https://chat.godotengine.org/channel/general) first, or consider looking for another first issue to start with. We have a "good first issues" tag across this repo and the main repo.

**Comment by mhilbrunner** [comment]
Closing, as per the above answer. Also, the `godot-docs` repo is not the right place for this discussion. Thanks for considering to contribute :)
