### ISSUE TITLE
GDscript has no best practices Page

### ISSUE THREAD

**Issue by XxDavid123xX** [godotengine/godot-docs#10331]
**Your Godot version:**
4.3
**Issue description:**
There's much people that has a problem with Optimization, so a page with basic tricks to Optimize the code.
**URL to the documentation page (if already existing):**
There's no one of course.

**Comment by tetrapod00** [comment]
Yeah, this may or may not already be covered. I think *GDScript* in particular doesn't currently have an optimization page because most of the slow things you can do in Godot are not really slow because of GDScript specifically. They are slow because you are using a slow algorithm that is slow in every language, or you are doing *a lot* of calls to rendering, physics, navigation, etc.

We do have several [Best Practices](https://docs.godotengine.org/en/stable/tutorials/best_practices/index.html) pages, including:
- [one](https://docs.godotengine.org/en/stable/tutorials/best_practices/data_preferences.html) that actually does touch on why GDScript in particular can be slow
- [one](https://docs.godotengine.org/en/stable/tutorials/best_practices/logic_preferences.html#loading-vs-preloading) that describes tradeoffs of a GDScript-specific functionality

We also have several pages on [Performance](https://docs.godotengine.org/en/stable/tutorials/performance/index.html), which apply to mulitple languages including GDScript.

If you're looking for a best practices/performance page on GDScript in general, I'm not opposed to the idea. But the content you're looking for may already be covered in one of these places. If you take a look through those and *don't* find what you're looking for, a good starting place for a new page would be to collect a list of tricks you'd like documented somewhere, or at least make a list of questions that you would like to be answered by a new page.

**Comment by tetrapod00** [comment]
Closing, since we already have pages that cover optimization, and there was no response.
