### ISSUE TITLE
American vs. British English

### ISSUE THREAD

**Issue by jcs224** [godotengine/godot-docs#1066]
I just wanted to clarify, in an official capacity, which version of English we should be using for documentation. In #1063, we thought that American is more appropriate for the documentation since that is what the API is using. However, there are a few British spellings in there.

When a decision is reached, maybe I'll do a PR that indicates which spelling standard to use. In my opinion, American is preferable, because of the aforementioned API issue and also because GitHub's spell-checker doesn't like British spelling 😛 

Thanks!

**Comment by akien-mga** [comment]
Yeah let's enforce American English, that's more or less the norm in technical documentation.

The one thing I'd request is that we don't use American *Capitalized Titles With One Uppercase Letter to Each Word or Maybe Not Some Small Ones But Nobody Is Ever Sure Which* title style :)
I know it's proper style for American writing, but personally as a non-native speaker I see it as very clickbait-ish (maybe because you always see "10 Things This Guy Can Do, His Doctors Can't Believe It" and never "Ten things this guy can do, his doctors can't believe it"). I think normal sentence casing + html styles is enough to denote titles without having to overuse uppercase letters.

**Comment by jcs224** [comment]
Sounds good to me. I agree with avoiding fully capitalized titles, which is actually mentioned in the docs already. Thanks for your guidance!

**Comment by jcs224** [comment]
If anyone else runs across this, I will probably run the docs through this program every once and a while, and make changes based off of it. Looks handy.

https://www.npmjs.com/package/american-british-english-translator
