### ISSUE TITLE
Tutorial suggestion: Viewports (Gun scopes, picture-in-picture, splitscreen)

### ISSUE THREAD

**Issue by mhilbrunner** [godotengine/godot-docs#1070]
Was mentioned in https://github.com/godotengine/godot-docs/issues/66.

**Comment by Calinou** [comment]
This may be better addressed by a demo: https://github.com/godotengine/godot-demo-projects/pull/502

**Comment by aaronfranke** [comment]
We do have [this demo category](https://github.com/godotengine/godot-demo-projects/tree/master/viewport) which covers PiP in general, and for splitscreen specifically we have both the [dynamic split screen demo](https://github.com/godotengine/godot-demo-projects/tree/master/viewport/dynamic_split_screen) and the regular [2D platformer demo](https://github.com/godotengine/godot-demo-projects/tree/master/2d/platformer) which has splitscreen. Perhaps a tutorial could be made for how to add the splitscreen in the 2D platformer demo, possibly just start the tutorial by saying to download the 2D platformer and then immediately delete `src/Main/Splitscreen.tscn` so that we can recreate it in the tutorial.

I'm thinking that it might be nice to add a minimal real time strategy demo which would demonstrate things like minimap/radar and more [as discussed here](godotengine/godot-demo-projects#502), but I haven't started on this and I would appreciate some art assets to use for such a thing.

For gun scopes, maybe we could add that to the Godot FPS tutorial, but that tutorial still has a ton of problems and some open discussion as noted in #3174. I think this one would be useful because it demonstrates something that we don't currently have a demo for, in particular, a 3D viewport inside of a 3D world. Aside from gun scopes, I think making a high quality FPS demo would be a nice idea, since FPS games are super popular and many people want to know how to make guns in Godot.

**Comment by NathanLovato** [comment]
We've removed tutorials from the docs and are moving towards writing a reference manual, closing as a result
