### ISSUE TITLE
tutorial_vector_math: better explanation of the dot product

### ISSUE THREAD

**Issue by akien-mga** [godotengine/godot-docs#108]
Cloning from https://github.com/godotengine/godot/issues/988

> Hi, the section says the dot product is hard to understand and makes no sense.
But I’ve found a really nice and intuitive way to think about it:

>> The dot product simply is the indicator for how much two vectors have in common.
The bigger, in relation to their magnitudes, the more two vectors have in common.
Simple. :)

> I think that it’s hard / makes no sense is a false meme,
and it’s just the explanation we learned it from that has always been bad,
which instilled fear, and caused us to have trouble understanding it in the first place.

> So I hope you can add the above explanation,
and remove the lines about it being hard or making no sense. :)

**Comment by StraToN** [comment]
I'd say it's not the role of the documentation to explain math concepts, but since this page is here it has to stay. I don't agree on removing "hard" parts of the dot product explanation since they are not wrong. However, I don't see any problem on adding more information about the dot product.

Remember this is a math theory wiki page, not specially related to Godot (GDScript references are given though, which is pretty good). A mathematical concept being difficult to apprehend is a subjective notion. Same goes for a lot of those, we could make a list (quaternions, etc). Some people will understand this easily, some others will have problems and need more explanations, regardless their maths level or ease of understanding.

**Comment by akien-mga** [comment]
I've re-read the part about the dot product: https://github.com/godotengine/godot-docs/blob/master/tutorials/vector_math.rst#dot-product and I admit that it's not as bad as described by the OP (though maybe it has been improved since the initial report).

> Most people trying to understand vector math give up here because, despite how simple it is, they can't make head or tails from it.

This states that it's "simple", which it is, so the rest is just written in a didactic way for people that do find math formulas daunting. Then it goes on with some good real life examples, so it's a good section IMO.

Let's close.
