### ISSUE TITLE
Move GDNative from "Plugins" to "Scripting"

### ISSUE THREAD

**Issue by vnen** [godotengine/godot-docs#1169]
GDNative is more related to scripting. While you can make plugins with it, the feature is not restricted to them.

**Comment by NathanLovato** [comment]
Doesn't scripting suggest we're talking about high-level and only interpreted code?
GDNative ended in the Plugins section because it's designed to help you access external libraries and/or write library code you can interface with the higher level scripting languages. Although you can write gameplay code with it you'd probably better use gdscript/C#. In any case I don't think C/C++ etc. would fit in scripting.

**Comment by vnen** [comment]
I see "scripting" as "code for your game" (as opposed to "code for the engine"). There's nothing stopping anyone to make the whole game in C or C++, that's the point of NativeScript and all the language bindings. If I was looking for how to program my game logic in C, that's the section I would open first (and there are people looking for that).

Also, when I see "plugins" I think only of "plugins for the editor" and not "using third-party libraries in the game", but that may be biased by my acquaintance with Godot.

Maybe split it into NativeScript (which is about coding game logic) and the GDNative itself, which has a broader interface. Currently the only tutorial available is about NativeScript and doesn't even mention external libraries.

**Comment by mhilbrunner** [comment]
Sure :)

**Comment by skyace65** [comment]
@GDQuest This was done at some point, this issue can be closed.
