### ISSUE TITLE
Create official Godot C# style guide

### ISSUE THREAD

**Issue by mhilbrunner** [godotengine/godot-docs#1296]

**Comment by paulloz** [comment]
This is some coding conventions from what I saw in the current documentation.

* Public fields, properties, methods should be named using `UpperCamelCase`
* Private fields, properties, methods and local variables should be named using `lowerCamelCase`
* Opening and closing brackets should be on their own lines
* Brackets can be spared if there's only one line inside the `if`, `while`, `for` etc.
* `this.` should be avoided if possible (I don't like this one but that's how everything is written right now)
* Local variables should be declared with `var` and not the actual type (same as above if you ask me)

**Comment by KellyThomas** [comment]
At the moment the demo projects have signal handlers named `OnSignal()` and `OnClassSignal()`.  Once we have decided on a name scheme we should apply it consistently in this project and integrate it into the Connect Signal dialogue.

https://github.com/godotengine/godot-demo-projects/blob/master/mono/monkey_pong/Wall.cs#L6

    public void OnWallAreaEntered(Area2D area)

https://github.com/godotengine/godot-demo-projects/blob/master/mono/monkey_pong/Paddle.cs#L26

    public void OnAreaEntered(Area2D area)

**Comment by neikeq** [comment]
We should this naming convention: https://docs.microsoft.com/en-us/dotnet/standard/design-guidelines/names-of-type-members

> * Private fields, properties, methods and local variables should be named using `lowerCamelCase`

- Properties and methods should be named using `PascalCasel` regardless of their accessibility level.
- Locals should use `camelCasel`.
- Private and internal fields are not mentioned in the guidelines, so I would be fine with `camelCasel` or either `_camelCasel` or `_PascalCasel` (both with an underscore prefix). Use properties instead of public or protected fields.

> * Local variables should be declared with `var` and not the actual type (same as above if you ask me)

Only where it makes the code more readable. e.g.:

``` C#
// ACCEPTABLE?
var node = GetNode("..."); // Node node = GetNode("...");
// OK
var floor = new StaticBody();
var sprite = GetNode("...") as Sprite;
foreach (var child in children) { ... }
```

``` C#
// NOT GOOD
var count = 10; // int count = 10;
var result = task.Result; // Whatever result = task.Result;
```

**Comment by mysticfall** [comment]
I agree with pretty much everything neikeq listed in the above comment. Personally, I would use `var` in every case when it's possible because virtually everyone uses an IDE to code C#, but if the intention is to make the code more readable also in the documentation, I don't have anything against the suggestion.

**Comment by paulloz** [comment]
Agreed with @neikeq (once again, I wrote what the actual state of the documentation was, not what should be done).  
Concerning this remark (to which I agree too):
> Use properties instead of public or protected fields.
It should be noted that the current codebase does not comply:
 * [Vector3](https://github.com/godotengine/godot/blob/master/modules/mono/glue/cs_files/Vector3.cs#L29-L31)
 * [Vector2](https://github.com/godotengine/godot/blob/master/modules/mono/glue/cs_files/Vector2.cs#L22-L23)
 * [Transform](https://github.com/godotengine/godot/blob/master/modules/mono/glue/cs_files/Transform.cs#L15-L16)
 * ... (I haven't looked everywhere)

**Comment by KellyThomas** [comment]
I strongly prefer `camelCase` over either `_camelCase` or `_PascalCase` for fields.

**Comment by neikeq** [comment]
> Although the documentation currently states [MSBuild 15.0+ is a requirement](http://docs.godotengine.org/en/3.0/getting_started/scripting/c_sharp/c_sharp_basics.html) there is still an effort being made to maintain compatibility with earlier versions.

Game projects can use C# 7, which requires MSBuild 15.0+. At some point we will have to enforce MSBuild 15.0 for both the API assemblies and GodotSharpTools.

**Comment by mysticfall** [comment]
By the way, I'm going to try a mass code clean up on the source files under `modules/mono/glue/cs_files` with my IDE's code inspector.

I'll try to configure it to the convention we agree upon this thread. So, if you have any suggestions or opinions about it, please let me know.

**Comment by mysticfall** [comment]
As to internal or private fields, it seems the standard conventions don't say anything but it looks like `_camelCase` or `camelCase` to be more commonly used than `_PascalCase`.

In my case, the default code style configuration of an IDE I use follows `_camelCase` convention, so I've been coding in that style for a while. But I don't have a too strong opinion against `camelCase`.

**Comment by paulloz** [comment]
It's weird to me that `internal` or `private` fields could use `_PascalCase` when it is used for `public` methods like `_Ready` or `_Process`...

**Comment by neikeq** [comment]
So between `camelCase` and `_camelCasel`, which one is more commonly accepted?

**Comment by mysticfall** [comment]
I'd say `_camelCase`, because .NET core itself seems to follow that style (i.e. [code sample](https://github.com/dotnet/corefx/blob/master/src/Common/src/System/Collections/CompatibleComparer.cs#L11)) and Rider recommends it as default.

**Comment by paulloz** [comment]
I don't have a strong preference for one or the other.

**Comment by skyace65** [comment]
On the subject of using `var` I prefer using `int`, `float`, `bool` and `string` over `var`. Other than those data types I'd use `var`

**Comment by paulloz** [comment]
For documentation writing: when connecting to signals defined in the editor (e.g. [here](https://godot.readthedocs.io/en/3.0/tutorials/misc/pausing_games.html#example)) we should keep the signal handler named in `snake_case`.

**Comment by aaronfranke** [comment]
@mysticfall has created a C# code cleanup PR here: https://github.com/godotengine/godot/pull/18053

I agree with most of his changes, but I am **not** a fan of changing everything to `var`, at all. It makes the type ambiguous, which is confusing and leads to problems. @mysticfall has encountered one of the issues with using `var` in his PR, as when he removed default assignments, he had to change the types back to explicit. It can also cause other problems like confusion. 

The main use case of `var` is when it makes code more readable due to avoiding repetition. 

`var f = new Dictionary<int, List<VeryLongClassName>>();` 

is much better than 

`Dictionary<int, List<VeryLongClassName>> f = new Dictionary<int, List<VeryLongClassName>>();`

But, replacing `int` with `var` makes the code *less* readable.

I vote for *not* changing everything to `var`, unless the type name is longer than ~10 characters.

**Comment by mysticfall** [comment]
@aaronfranke Thanks for taking time to review my code and share your opinion.

The reason why I prefer `var` is as follows:
 * It's only for local variables, so their declarations are closely located to their use sites.
 * In most cases, it's not difficult to infer the actual type of such variables - `var a = 10` isn't that much difficult to read than `int a = 10`, for example.
 * In some cases, it can take a bit more efforts to infer the actual type, like for such statements as `var a = GetValue()`. However, it's often possible to do so from the context (i.e. `var x = vector.x`), or by using an IDE.

If we decide to use `var`s conditionally, then probably we better use it for only such cases where we declare a variable and instantiate the target type at the same time, like `var x = new Type()`.

I don't see much benefit of using `Vector3 pos = new Vector3()` instead of writing `var pos = new Vector3()`, so I wouldn't apply any hard and fast rule depending on the length of type names.

**Comment by Chaosus** [comment]
And public constants should be uppercase ? I hope so..

**Comment by mysticfall** [comment]
> I want you to explain why var is a better choice than int, not just that it's as good, acceptable, or doesn't cause problems.
I'd say for it's better for consistency. It's the same reason why we better not mix different line break rules, even though it wouldn't cause any real problems.

If we have a consistent rule, it's easier to configure an IDE or other static code analysers to check if new code conforms to the accepted standard of the project.

> I'm not trying to pull a Torvalds on you @mysticfall, just trying to discuss things.
@aaronfranke I fully understand. So, please don't worry about it :)

**Comment by aaronfranke** [comment]
That's a good point. However, it wouldn't be hard to make a consistent rule for style-checking programs, we'd just have it search for when the type name text is present twice in the same line!

And maybe, as I've suggested, only check if the type name is longer than X amount of characters.

**Comment by aaronfranke** [comment]
For casing, here is my proposal: PascalCase methods, camelCase variables, and UPPER constants. 

It makes them easy to differentiate, and this is the styling that Unity uses (and while this isn't the only reason to do it this way, appealing to Unity users should definitely be a goal of Godot C# to promote Godot).

**Comment by mysticfall** [comment]
I don't think it'd be a good idea to follow Unity in this matter, as it's notoriously negligent in following the standard coding conventions (i.e. lower case properties).

I think it'd be more reasonable to follow the style guide published by MS themselves which suggests using PascalCase for constants:

 * https://blogs.msdn.microsoft.com/mschray/2013/05/06/practical-naming-standards-for-c/
 * https://docs.microsoft.com/en-us/dotnet/standard/design-guidelines/capitalization-conventions

**Comment by paulloz** [comment]
What are you calling *variables*? You pinged me in #17212 saying the fields I was talking about should not be capitalized. As stated above *«public and protected fields should be avoided, use properties instead»* so anyway something should be changed about these fields as public API should not expose mixed case convention...

**Comment by aaronfranke** [comment]
A variable like `real_t x` in `Vector3`.

**Comment by mysticfall** [comment]
I think it could be a good time to gather all the issues in this thread, on which we still need to make an agreement:

 * Wheter to use `_camelCase` or `camelCase` for private fields.
 * As to use of `var`s : a) Never use them b) Always use them c) Only when duplicating type info d) Depending on the length names.
 * Whether to use `PascalCase` or `CAPS_WITH_UNDERSCORES` for constants.

For me, it's `_camelCase`, b) or c), and `PascalCase`. I'll update my PR as soon as we reach an agreement about these issues.

**Comment by exts** [comment]
Not a fan of `m` if we're going to even bother with a prefix we should go with what microsoft has been using as an unofficial standard for years which is the underscore for private class members.

**Comment by mysticfall** [comment]
As to @paulens12 suggestions, 

1. Personally, I don't like using an arbitrary prefix that isn't used often by other projects. It reminds me too much of the Hungarian notation, which is generally avoided by C# programmers.

Besides, properties and methods are technically also members of a type, so it could be confusing to use the `m` prefix only for member fields.

2. The reason why I chose `c` rather than `d` is that I don't see much benefit in using `Vector3 pos = new Vector3()` instead of `var pos = new Vector3()`.

In that case, `Vector3` is just 7 letters long, but it's obvious what the type of `pos` would be even when we replace the first type name with `var`.

On the other hand, something like `SomeLongTypeName value = GetValue()` wouldn't be as obvious even if we replace `SomeLongTypeName` with `var`. So, I don't think we should decide when to use `var` soley on the length of type names.

3. I think we should go with the coding guide provided by MS in this case, which is `PascalCase` for both constants and public properties.

**Comment by paulens12** [comment]
@exts the reason why I'm proposing m is that underscore is really uncomfortable to type and at least me personally, I'd like to avoid having to type it at all. I get that m is not widely used, but at the same time I don't really get why anyone would choose underscore apart from "everyone else uses it". Why does everyone else use it? Well, I don't know. I think out of the three options (underscore, m, or nothing at all, using this. where appropriate instead), underscore is the worst.

**Comment by exts** [comment]
@paulens12 I get why you want it, but 'm' was never a standard in c# so no need to introduce an arbitrary prefix like that imho. We need to keep things as C# standard as possible where people unfamiliar with godot can come in and contribute. We don't need to focus on standard practices that has been around purely in the gamedev space for years purely because it's a common thing in the gamedev space (mostly seen in C++ projects)

To answer your "why do people use it" because for years microsoft used it, the people that created the language.

**Comment by paulens12** [comment]
good points. As for 2., I personally would chokes something between c and d, but that was not an option. C means using var ONLY when duplicating type info, which means long names would still have to be typed out. On the other hand, d means that short names could be duplicated. I think the best way would be in the middle: use var when the name is either too long or it's duplicated.

As for point 1, I really just wanted to express my disgrace with underscores here. I don't have a very strong preference of what prefix to use or whether to use them at all, I just dislike underscores, if that makes any sense. Maybe after all, this. is the best choice. Personally, I feel it's still faster to type than stretching my fingers out to reach shift and minus.

**Comment by mysticfall** [comment]
@mhilbrunner just ~~coerced~~ persuaded me into writing a draft for the style guide and I'll begin in a couple of days.

So, it'd be nice if you could share your thoughts on the issues raised above before then, even though we'd still continue discussing the matter after I'm done with the draft if it's needed.

**Comment by paulloz** [comment]
1. Don't care about `_` or no `_` in front of private fields, that's trivial.  
2. `var` should be used when it does not impact readability (e.g. there should not be a rule telling people to write `var x = GetNumber();` and not `int x = GetNumber();`).
3. Don't care either.

**Comment by neikeq** [comment]
> 2. As to use of `var`s : a) Never use them b) Always use them c) Only when duplicating type info d) Depending on the length of type names.

I think it's not that simple to make a set of rules.

- _a)_ is discarded because there are many places where using `var` improves readability.
- _b)_ is discarded because there are many places where using `var` hinders readability.
- _c)_ is fine, but there are exceptions. For example, I think `foreach (KeyValuePair<string, Node> kvp in dict) {}` could be replaced with `foreach (var kvp in dict) {}` as long as `dict` is declared near the loop.
- _d)_ misses the point. Although `var` is most useful to avoid typing long names, it doesn't necessarily improve readability.

I would simply leave it as "when it improves readability" and add a few code examples from this discussion.

> ... (e.g. there should not be a rule telling people to write `var x = GetNumber();` and not `int x = GetNumber();`).

In this case, using `var` does not improve readability, it does the opposite.

One think I would recommend is to always use [built-in type keywords](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/built-in-types-table) instead of `var`. I don't see how `var` would improve readability versus them. Even if you write `1.25f`, `1.25d`, `true`/`false` or a string literal, the keywords are just short to type...

**Comment by mysticfall** [comment]
I think we are close to an agreement on the usage of `var`s. Thanks everyone for the input!

Now we only need to determine on the other two issues, so please keep them coming :)

**Comment by neikeq** [comment]
I guess we will go with `_camelCase` for private fields, since it's what most prefer.
Constants should use `PascalCase`, not `CAPS_WITH_UNDERSCORES`.

**Comment by mysticfall** [comment]
@aaronfranke 
That's an interesting case, and I can only assume they were rather inconsistent in naming it. My guess is that they erraneously applied the exception about two-letter acronyms which shouldn't be the case with `PI`.

A funny thing is, they even shows `PI` as an example of non-standard naming practice in their guide:
 * https://docs.microsoft.com/en-us/dotnet/standard/design-guidelines/capitalization-conventions

So, I guess it was a mistake from their part, but I agree we need to decide if we should replicate such an error in our API or not.

**Comment by neikeq** [comment]
Indeed. Let's use `Pi` and `Tau`.

**Comment by mysticfall** [comment]
I just updated #18051 to reflect how we decided on the proper usage of implicit typing.

By the way, am I correct in assuming we shouldn't use any C# 7.0 features in the engine source?

From #17936, it seems that the requirements for Mono build is MSBuild 14, not 15, so I was wondering if I should mention that the source must conform to the C# 6 specification in the style guide.

**Comment by skyace65** [comment]
@mysticfall 
I don't think MSBuild 14 is the minimum. The [Introducing C# in Godot](https://godotengine.org/article/introducing-csharp-godot) blog post on the Godot website mentions MSBuild15 as the minimum. Compatibility with MSBuild14 might have been accidental or plans could have changed. I'd recommend asking one of the devs who might know just to be safe

**Comment by mysticfall** [comment]
@skyace65 It seems that @KellyThomas already mentioned it in his first comment in this thread:
 * https://github.com/godotengine/godot-docs/issues/1296#issuecomment-378566156

Personally, I think it'd be better if we target C# 7 with MSBuild 15, if there's no practical reason that prevents it.

@KellyThomas , @neikeq Could you share your thoughts on this issue?

**Comment by mysticfall** [comment]
I've encountered a case where we need an explicit cast even if a code inspector I use (Rider/ReSharper) think it as redundant.

Can I use a vendor specific directive to suppress such false positives, to prevent mistakes like this? : 
```c#
// ReSharper disable once RedundantCast
var max = (float)Mathf.Max(r, Mathf.Max(g, b));
```

**Comment by KellyThomas** [comment]
Some users are finding Mono 5.4 to be incompatible with the MSBuild 15 that ships with Build Tools for Visual Studio 2017. Workarounds are to use MSBuild 14 or install MSBuild15 via Visual Studio.

As long the Godot stable builds require Mono 5.4 and there is no real need to use c#7 features I would suggest avoiding them in engine code.

**Comment by mysticfall** [comment]
Ok, then I'll use C# 6 / MSBuild 14 until all related issues get resolved. Thanks for the info!

**Comment by aaronfranke** [comment]
So... tabs or spaces? Tabs are easier to add/remove when working with code. The existing C++ code seems to use mostly tabs, and more editors use tabs by default. But spaces have a more consistent size. GitHub treats tabs as 8 wide, while most other editors treat tabs as 4 wide. Code written using tabs would look different in GitHub vs in text editors. Honestly I don't care which, but we should pick one.

**Comment by paulloz** [comment]
A comment above is mentioning this:
> other than curly braces in their own line, 4 spaces for indentation, and no spaces between identifier and parenthesis or square brackets.

**Comment by mysticfall** [comment]
Just opened a PR with an initial draft of the style guide. Please feel free to suggest changes, and sorry for the delay!

**Comment by aaronfranke** [comment]
For integers stored in a floating format, should we write `1` or `1f`?

**Comment by mhilbrunner** [comment]
Closing this for now, as we now got a first version of a C# style guide thanks to @mysticfall and the other contributors here. Thanks for the discussion and helping out, everyone! :)

For specific changes and additions, we should create new issues and PRs to discuss.

**Comment by aaronfranke** [comment]
For the record, here's a link to it: https://godot.readthedocs.io/en/latest/getting_started/scripting/c_sharp/c_sharp_style_guide.html
