### ISSUE TITLE
[Discussion] Class references using 1 page per function and add code examples

### ISSUE THREAD

**Issue by StraToN** [godotengine/godot-docs#133]
It seems people don't find current Class Reference documentation sufficient, and keep asking for "tutorials" for this feature or that function. While it is clear that for now, we need to clear the task of filling the classes.xml file, we can discuss the evolution of its presentation.

Other propositions available here: https://github.com/godotengine/godot/issues/7360

---

Currently, each class is documented as one reference page. All members, functions and signals are listed and described in this page.
To enable documenters writing code snippets to show example(s) of usage for each function of each class, we need to have one page per function, accessible from the main class page. 
Example for TODAY: 
- class_sprite.rst
- every function is accessed in this same page, using anchor links.

Example FUTURE: 
- class_sprite.rst
  - class_sprite_set_texture.rst
  - class_sprite_get_texture.rst

The idea is to have a similar organization as Unity documentation has:
- Main : http://docs.unity3d.com/ScriptReference/Graphics.html
  - Child : http://docs.unity3d.com/ScriptReference/Graphics.Blit.html

Having 1 page per function has the following advantages:
- allows documenters to document specific use cases, or add links to them if they are located elsewhere
- allows addition of code snippets

Disadvantages:
- since all the class reference is located in the classes.xml file, adding even more content in this file to create child pages for each class' function will inflate greatly its weight. 

A potential solution to this problem would be to split classes.xml into 2 XML files; the second one would contain long descriptions in it, but I feel it will be somehow problematic for maintenance.

I recommend to keep classes.xml's current structure and the current "short" description we have for each function, as we need them to be displayed in the _main_ class page. In the main page, each function name should now be a link to the corresponding _child_ page, which is filled with the content of another tag in classes.xml.

classes.xml methods current structure: 

```
<method name="set_texture">
    <argument index="0" name="texture" type="Texture">
    </argument>
    <description>
    Set the base texture for the sprite.
    </description>
</method>
```

New structure:

```
<method name="set_texture">
    <argument index="0" name="texture" type="Texture">
    </argument>
    <description>
    Set the base texture for the sprite.
    </description>
    <long_description>
    *Here is the content of the child page.*
    </long_description>
</method>
```

---

Code examples:
We must not forget future translations for class reference. We have no choice but to duplicate (in the future) classes.xml file for each language (classes.en_EN.xml, classes.fr_FR.xml, etc).
However, certain portions of long descriptions of each class method could be shared by every translation : scripts and source codes. 

In that way, script examples could be inserted in another XML file (classes.script_examples.xml). Each script can be identified with an ID (designed to be unique, say `<classname>_<function>_<XY>`) and called from classes.xml using a special tag, like: `<script id="Sprite_set_texture_001" />`.

---

Here you go. 
Discuss !

**Comment by bojidar-bg** [comment]
Ok, my 2c:

The script examples would be better if they are included via a BBCode tag (such as `[script] Sprite_set_texture_001 [/script]` or `[script="Sprite_set_texture_001"]`), since that would allow for much simpler parsing code (and reuse of the current code).

I guess the second method (with child pages) is much better for this, since we would get better organization with it.

**Comment by StraToN** [comment]
@bojidar-bg You mentien first and second methods as if they were two different proposals: they are not. What you so-call method 1 is actually what we currently have in godot-docs. Method 2 is the proposal :)

**Comment by BlenderNPR** [comment]
@StraToN your idea is aligned with how Processing is currently documenting their API.

Here is 1 page example: [https://processing.org/reference/image_.html](https://processing.org/reference/image_.html)

It has **Examples**, **Description**, **Syntax**, **Parameters**, **Returns **and **Related APIs**

**Comment by StraToN** [comment]
@BlenderNPR Yes, a little bit. The difference is that Godot functions are related to classes (so they're actually **methods**. In your example with Processing, image() seems to be a simple function. 
Other that that, yes, the idea is very close.

**Comment by ogrotten** [comment]
Whatever the method of organization, the docs sorely need embedded examples. 

2ndly, I think you're kinda throwing out the baby with the bathwater. . . the quest to find and use the best method to include examples has thus far resulted in no included examples.

I think so long as you minimize repetition, and use a portable/flexible/generic method (xml, json, etc) then there can be no wrong method, and any issues can be patched easily.

**Comment by Noshyaar** [comment]
Just throwing my idea out there because now it seems a bit difficult to achieve. 

Since Godot 3 can export to HTML5, what if we include GDScript compiler directly in the docs? (kinda like W3School [Tryit Editor](https://www.w3schools.com/html/tryit.asp?filename=tryhtml_radio) or TutorialsPoint [CodingGround](https://www.tutorialspoint.com/compile_cpp_online.php)) 

Then every [script] or <script> tag can redirect to this editor. (For in-editor docs, maybe create new GDScript with script in the tag.)

**Comment by vnen** [comment]
> the quest to find and use the best method to include examples has thus far resulted in no included examples.

Well, one could say that... but considering how much of the class reference was filled (or rather how it *wasn't*) I believe the problem is just the lack of documentation contributors. It's not that there are no examples, there's simply no documentation at all for a great part of the engine classes and methods. More truly so with the 3.0 changes (which just by being change hinders the documentation effort).

I think we can still discuss a better way to include examples (and I'm a fan of a page per property/method), because 3.0 is just now getting stable enough to welcome documenters to do a job that won't be undone in a few weeks.

**Comment by NathanLovato** [comment]
We've had some discussion, improvements to the parsing system, and now classref guidelines + more contributors, so let's see how it goes once the classref is > 80-90% complete, and we'll open new issues to discuss problems that'll show up then
