### ISSUE TITLE
Add a page explaining cross languages interactions 

### ISSUE THREAD

**Issue by paulloz** [godotengine/godot-docs#1425]
Hi all 😄 

One of the most asked questions these days on Discord is about calling C# from GDScript or GDScript from C#.  

![image](https://user-images.githubusercontent.com/437025/39661605-aafe78e0-5054-11e8-9d91-dd64a91c23e5.png)
![image](https://user-images.githubusercontent.com/437025/39661606-ae83521a-5054-11e8-917b-3d96f7bfe473.png)
![image](https://user-images.githubusercontent.com/437025/39661607-b379770e-5054-11e8-860b-cd7a595d6f28.png)
And so on and so forth.

It made us realize that the only place tackling this in the documentation is [this small section](https://godot.readthedocs.io/en/3.0/getting_started/scripting/c_sharp/c_sharp_differences.html#communicating-with-other-scripting-languages) and explanations about signals.  
It'd be cool to have some details about `call`, `get`, `set`, and explanations about what is possible / impossible to do across the different scripting languages.  
A while ago I created [an issue](https://github.com/godotengine/godot/issues/15894) on the main repo which sums up how to call methods from one side to others (not sure it's up to date though).

**Comment by Omicron666** [comment]
Ys, that could be in an intro page in category ![category screenshot](https://i.imgur.com/49OfPJD.png)

**Comment by akien-mga** [comment]
> What needs explanation?

Well, how to call stuff written in one language from another one (and maybe some details about the background of why this is possible, since some users seem to have strong opinions that it shouldn't be feasible :)).

**Comment by neikeq** [comment]
> > What needs explanation?
>
> Well, how to call stuff written in one language from another one

I'm aware this needs documentation. I was addressing @Noshyaar's comment which seemed to indicate there was something else which needs an explanation.

> (and maybe some details about the background of why this is possible, since some users seem to have strong opinions that it shouldn't be feasible :)).

This should be docummented in the Object class reference. Perhaps it should have its own page for more details.

The way `Object.call(method, ...)` works is:

- If the method is "free" (hard-coded)
  - instantly free (`memdelete`) the object and return
- If the object has a script instance (language implementation dependent)
  - If the script instance has the method, call it and return
  - Otherwise, if the script has the method (static method), call it and return
- If ClassDB has a native method bind (MethodBind) with this name for this class, call it and return
- Error, invalid method

https://github.com/godotengine/godot/blob/fc90f41f53a639649bbc764746bfc59d22b98081/core/object.cpp#L857-L919

The way `Object.get(property)` and `Object.set(property, value)` work is:

- If the object has a script instance (language implementation dependent)
  - If the script instance has a field or property, get/set it and return
- If ClassDB has a property bind (PropertySetGet) with this name for this class, call its native getter/setter and return
- Hardcoded "script" property set/get
- Hardcoded "\_\_meta\_\_" property set/get
- Hardcoded "_sections_unfolded" property set/get
- Fallback to _setv/_getv and then setvar/getvar. No idea what this is

https://github.com/godotengine/godot/blob/fc90f41f53a639649bbc764746bfc59d22b98081/core/object.cpp#L404-L519

**Comment by Calinou** [comment]
This was implemented in #2826, closing.
