### ISSUE TITLE
Mention max 2D Z index

### ISSUE THREAD

**Issue by JarLowrey** [godotengine/godot-docs#1453]
It is not mentioned [in the docs](http://docs.godotengine.org/en/3.0/classes/class_node2d.html), but `z_index` can only range from in `[-4096, 4096]`. This can be tested by attempting to change to a smaller/larger number in the editor, and it will be bounded. This can cause problems if you are attempting to set a random z_index beyond this range.

**Comment by akien-mga** [comment]
Indeed, it's bound by `CANVAS_ITEM_Z_MIN` and `CANVAS_ITEM_Z_MAX` in VisualServer: http://docs.godotengine.org/en/3.0/classes/class_visualserver.html#numeric-constants

**Comment by JarLowrey** [comment]
Nice find. I think it would be good to mention/link in Node2D or other nodes as needed.

**Comment by reduz** [comment]
@derrideanauthor No, use the YSort node for this instead and make your life easier

**Comment by derrideanauthor** [comment]
@reduz Thanks I considered using this but could not get it to work. Still there is an issue if the game includes horizontal overlapping as well (mine does).  What I really wanted to know is why is there limit in the first place? HTML accomplishes z-index without limitation.

**Comment by eligt** [comment]
I would also like to know the reason behind this limitation and whether it's possible to increase the range. It should definitely be documented anyway.

**Comment by oiblank** [comment]
@reduz Y-sort is not really a solution tbh, since it's too limited, doesn't work with tilemaps, and thus makes it impossible to Y-sort tiles and player/npcs while using multiple tilemaps or instancing whole levels separately to a player (not having characters as children of tilemap) without dynamically changing players/npcs z_index according to his position and setting z_index for each tile in ready function.. Please correct me if I'm wrong, been struggling with this for a long time.

**Comment by Piralein** [comment]
The documentation of 3.3 and above mentions this limitation.
[#48868](https://github.com/godotengine/godot/pull/48868)
[3.3 Docs](https://docs.godotengine.org/en/3.3/classes/class_node2d.html#class-node2d-property-z-index)

With the class reference beeing part of the engine a backport is probably not needed and this can be closed.
(I can open a pull request otherwise)

**Comment by Calinou** [comment]
Closing per @Piralein's comment.
