### ISSUE TITLE
FPS Tutorial: collision behavior not influenced by player position / projectile direction

### ISSUE THREAD

**Issue by PetePete1984** [godotengine/godot-docs#1485]
**OS:**
Windows 10

**Godot Version:**
- https://github.com/godotengine/godot/commit/c80ac06 nightly build from Calinou's CI service

**Repro project:**
- http://docs.godotengine.org/en/latest/_downloads/Godot_FPS_Part_2.zip
- the zip included with the tutorial exhibits the problem and represents the project at the end of the tutorial's second part

**Description:**
All collisions of bullets with boxes seem to push the boxes in one predefined direction, regardless of player facing, bullet impact point or bullet forward direction.

**How to reproduce:**
- start the included project
- press 3 to equip the pistol
- (optional) aim and shoot at the top face of the leftmost purple cube (mouse & click), watch it get correctly knocked back
- walk behind the leftmost purple box, aim at its top face and shoot, at which point it will get pulled towards the player
- walk to the side of the purple box, shoot it, watch it tumble to the side

At this point I'm not sure if it's an engine problem or if the tutorial's code is at fault.
Relevant code is found at https://github.com/TwistedTwigleg/Godot_FPS_Tutorial/blob/71ec3b126c7fb2169d3d332311a8c36e764a3569/Bullet_script.gd#L39 and https://github.com/TwistedTwigleg/Godot_FPS_Tutorial/blob/master/RigidBody_hit_test.gd

CC @TwistedTwigleg

**Comment by TwistedTwigleg** [comment]
Okay, I did some testing, figured out what I think was the problem! I made a (hopefully) fixed version, that also fixes a lot of issues with the old bullet system as a bonus!

The problem is how the bullet direction is being calculated in `RigidBody_hit_test.gd`.

Currently, `RigidBody_hit_test.gd` tries to calculate the direction the bullet hit the RigidBody at by using it's position and the bullet position. This gives a direction pointing from the bullet to the center of the RigidBody. It then used that direction and applied a impulse at the bullet's global position.

There are a few problems with this method though. The first problem is this method does not take the rotation of the bullet into account. This means a bullet skimming the surface has the same effect as a bullet shot straight.

The other problem is the cubes (or whatever object) rotate around when it's edges are shot.

____

I have found a solution though! The solution is instead of passing the global position of the bullet into `bullet_hit` (in `RigidBody_hit_test`), we instead just pass the entire global transform! This makes it where we can use the bullet's local Z vector to get the direction the is heading, which we can use to make the RigidBody always go in the proper direction (relative to the bullet).

I've also fixed a problem where the origin of the impulse was improperly calculated. Because `apply_impulse` takes a position relative to the RigidBody's position, the new version calculates the relative position of the bullet instead of using the global position.

I've attached a (hopefully) fixed version of the finished part 2. Please give it a try, and let me know if you can still reproduce the error!

[Godot_FPS_Part_2.zip](https://github.com/godotengine/godot-docs/files/2058595/Godot_FPS_Part_2.zip)

**Comment by PetePete1984** [comment]
Yup, that fixed it. Thanks!

**Comment by TwistedTwigleg** [comment]
Great! I'll try to make a PR with the fix soon! (maybe this weekend)
