### ISSUE TITLE
Update Mesh Generation Tutorial

### ISSUE THREAD

**Issue by clayjohn** [godotengine/godot-docs#1509]
I have always been bothered by the Mesh Generation tutorial. It requires the users to use both Gimp and Blender, and then the Godot aspect of the tutorial is very short. 

I would like to rewrite the tutorial to be contained purely within Godot. Using Godot to make a subdivided quad and then using noise in the shader to offset the vertices. I think this way the tutorial could be way more Godot-centered and also be more useful for people learning shaders and stuff.

If anyone has any other ideas or reasons why the tutorial should stay the same please let me know! Otherwise im going to make a PR in the next couple days with a revised tutorial.

**Comment by StraToN** [comment]
I wrote this tutorial back for Godot 2.1. At this time, Godot 3.0 was not there and direct geometry was kind of on the exit way.

So, in order to demonstrate a larger workflow involving external tools (GIMP and Blender, but I remember stating you can use your favourite softs) and importing into Godot. I agree using Blender for a simple quad is overkill though but at the time of writing I had no choice.

No problem if you wish to update this tutorial. I am not even certain it teaches the *right* way to do, but I believe it fulfills its primary objective: learn geometry shading basics in Godot. 

Your proposal (using noise in the shader to offset the vertices) is very interesting, but I don't think it is an update to this tutorial, but an extension :) .

Looking forward to read your PR!

**Comment by clayjohn** [comment]
Thanks for replying! I hope I didn't sound too rude in my original post, looking back at it now I think I come off kinda rude and I didn't intend that. 

Your right, when you would've originally written it Godot didn't have the ability to make a subdivided quad in-engine. So now is the time to update that!

I think I will actually change the scope of the tutorial a bit. Instead of calling it "Mesh generation with heightmap and shaders" I am thinking of calling it "vertex displacement with shaders" because a) the tutorial isn't teaching mesh generation, and b) I plan on replacing the heightmap with noise that way the tutorial can focus more on writing shaders and less on importing and using textures.

**Comment by clayjohn** [comment]
This can be closed now that #1540 is merged
