### ISSUE TITLE
how do i edit projectsettings for override.cfg information? 

### ISSUE THREAD

**Issue by ghost** [godotengine/godot-docs#1523]
this is very confusing

> To edit an existing page, locate its .rst source file and open it in your favourite text editor. You can then commit the changes, push them to your fork and make a pull request. Note that the pages in classes/ should not be edited here, they are automatically generated from Godot's XML class references.

it says open .rst in your favourite text editor (to edit it), but when i open .rst to edit it, at the top of the file there is a line that says:

https://github.com/godotengine/godot-docs/edit/master/classes/class_projectsettings.rst

```
.. Generated automatically by doc/tools/makerst.py in Godot's source tree.
.. DO NOT EDIT THIS FILE, but the ProjectSettings.xml source instead.
.. The source is found in doc/classes or modules/<name>/doc_classes.
```

now it's telling me to not edit the file, but edit it in the xml..

however, when i edit the projectsettings xml:
https://github.com/godotengine/godot/blob/master/doc/classes/ProjectSettings.xml

and click preview changes, i can't see what i edited @willnationsdev 

all i want to do is add some override.cfg information why is this so complicated and what am i doing wrong?

**Comment by girng** [comment]
i wrote some information about how to use override.cfg and what its good for, but it was in my .rst, and it says we cannot edit that file. 

if i copy and paste it here, can someone just use my text   and get in the docs? thank you

**Comment by akien-mga** [comment]
Well, you quoted it yourself:

> To edit an existing page, locate its .rst source file and open it in your favourite text editor. You can then commit the changes, push them to your fork and make a pull request. **Note that the pages in classes/ should not be edited here, they are automatically generated from Godot's XML class references.**

So you should edit https://github.com/godotengine/godot/blob/master/doc/classes/ProjectSettings.xml
GitHub can't show you a "preview" of the changes as it's XML and it bears no information on how things much be parsed and rendered. This XML is parsed by Godot itself for the in-editor help, and converted to rst files for the only docs manually.

**Comment by girng** [comment]
problem is, i'm not sure how to make it look good in projectsettings.xml. i want to give a code example and explain what it does, why it's important, etc. **then see a preview of it before a PR**.  can we just use a .rst to markdown converter or something, and edit the markdown? then, edit it and make a PR?

for example, i was thinking of adding a header at the bottom of projectsettings.xml.

that says "Using override.cfg" or something. but i only know markdown and not sure how to do that in .xml. i just want to give information about override.cfg, not learn XML :(

**Comment by bojidar-bg** [comment]
@girng Currently, the .xml files and the generated .rst files are meant to be an API reference, not general documentation. This means documenting only classes, methods, properties, constants, etc.

On the other hand, the rest of the documentation (the non-generated files) is meant to be general documentation about using the engine. This includes tutorials, development overviews, and so on.

In your case, it seems like you want to make a tutorial about using `override.cfg`. That's great!
Unfortunately, it cannot be put in the API documentation, since `override.cfg` is not part of the API. 
Instead, it could be made into a tutorial, maybe in the [misc section](http://docs.godotengine.org/en/latest/tutorials/misc/index.html), and then linked to in the API documentation, similar to [here](https://github.com/godotengine/godot/blob/98b59cf2a387e469851eee137cc6310cfc4b2a6d/doc/classes/CanvasLayer.xml#L9).

**Comment by Calinou** [comment]
OP has removed their account (which means they can't open a pull request anymore), closing.
