### ISSUE TITLE
Document negative indexing for strings/arrays

### ISSUE THREAD

**Issue by mhilbrunner** [godotengine/godot-docs#1534]

**Comment by BornStellarMakesEternalLasting** [comment]
Since I know that GDScript uses syntax simmilar to Python searched the python.org documentation to search for negative indexing for arrays. From what I can tell negative indexing in python is known as slice notation. Here are three links to mentions of slice notation and some preview text 

[5. Built in Types](https://docs.python.org/2/library/stdtypes.html?highlight=slice%20notation)
str.count(sub[, start[, end]])

    
Return the number of non-overlapping occurrences of substring sub in the range [start, end]. Optional arguments start and end are interpreted as in slice notation.

[PEP 357: The ‘__index__’ method](https://docs.python.org/2/whatsnew/2.5.html?highlight=slice%20notation)

The NumPy developers had a problem that could only be solved by adding a new special method, __index__(). When using slice notation, as in [start:stop:step], the values of the start, stop, and step indexes must all be either integers or long integers.


[4.3 The range() function](https://docs.python.org/2/tutorial/controlflow.html?highlight=slice%20notation)

If you do need to iterate over a sequence of numbers, the built-in function range() comes in handy. It generates lists containing arithmetic progressions:
`>>> range(10)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]`


Is this the kind of information you are looking for?

**Comment by mhilbrunner** [comment]
No, the basic idea is that you can use negative numbers/indexes < 0 for arrays (and strings).

This is useful for iterating arrays (and strings) in reverse, for example.

````
arr[-5]
````

etc

**Comment by mhilbrunner** [comment]
I'd say "count from the back" instead of "count from the right", but otherwise that looks good to me :)

**Comment by BornStellarMakesEternalLasting** [comment]
Alright I made the pull request in godot/godot-docs #20180

**Comment by mhilbrunner** [comment]
Closed by https://github.com/godotengine/godot/commit/adb16be6b96602061fcc2037e6b6e1e27ae41023
