### ISSUE TITLE
Resizing handles and Confusing description in #collision-objects

### ISSUE THREAD

**Issue by BrahRah** [godotengine/godot-docs#1564]
https://godot.readthedocs.io/en/3.0/tutorials/physics/physics_introduction.html#collision-objects

First of all I wanted to know about the outside and inside handles they are very confusing for beginners and from what I've read it's even dangerous to use them. I had to ask in the chat to get directed to this, searching resize didn't bring them up. 

I've read the green "Important" part and it doesn't tell me which handles are the Node2D handles. The ones that are red in the picture or on the outside?

When I searched "node 2d handles" the only page I found was the same page that doesn't really explain the handles.

**Comment by cbscribe** [comment]
The "inside" handles, which are connected directly to the shape, are used to size the shapes themselves. For example, a circle shape has one handle that sets its radius.

The "outside" handles are not part of the shape at all. When you're using a CollisionShape2D, it's a helper node that assists you in *making* your shape. Because CollisionShape2D is a Node2D-derived node, it has the rectangular selection handles. They shouldn't be used because they don't set the shape directly.

The good news is that in 3.1, this is getting addressed. The Node2D handles will be hidden in helper nodes like this.

**Comment by Calinou** [comment]
This was solved in https://github.com/godotengine/godot/pull/17502, closing.
