### ISSUE TITLE
No explanation about CollisionShape2D

### ISSUE THREAD

**Issue by breakmt** [godotengine/godot-docs#1568]
Page: http://docs.godotengine.org/en/stable/getting_started/step_by_step/your_first_game.html

In a section "Finally, add a CollisionShape2D as a child of Player..." there is warning "Don’t scale the shape’s outline! Only use the size handles (circled in red) to adjust the shape!" But no explanation about why I can't scale it using outline circles. I'm (as a newbie in Godot) don't get this part. It would be nice to get more wide explanation.

**Comment by rcorre** [comment]
@bojidar-bg do you happen to know why? If you tell developers not to do something without explanation, chances are they'll do it :grin:, but in this case the consequences aren't obvious.

Still, even "it throws the physics engine off" would be better than no explanation in the docs.

**Comment by breakmt** [comment]
@bojidar-bg this explanation didnt help me to understand the topic

**Comment by lawsonry** [comment]
Well it's likely because the physics engine is looking at the points that make up the collision shape polygon, and somewhere inside the way it accounts for scaled shapes it assumes you want to not only scale the collision shape but also the values going into and out of the physics calculations. 

I'm not sure why you would ever want to "scale" a collision shape anyway. If you think about what that would mean, you're taking, say, a rectangle, and instead of defining its collision boundaries precisely over the area we want colliding, you're taking a smaller rectangle and telling it to scale itself--to a size that coincidentally is the size of your collision shape, but still a scaled calculation nonetheless.

**Comment by rcorre** [comment]
Thanks @lawsonry, that helps. It's not so much that you'd "want" to scale a collision shape, but as a newbie there doesn't seem to be an obvious reason not to.

**Comment by breakmt** [comment]
@lawsonry just 1 question more - why do we even need this outline if it will fail physics? Are there any situations when it can be usefull?

**Comment by lawsonry** [comment]
@breakmt I just re-read the tutorial page and got to where the warning is. I think it's one of those cases where the author of the tutorial may have inadvertently scaled a rect instead of resizing it with the handles, and wants everyone else to avoid making that silly mistake as well. I could be wrong, of course. 

Do we need it? Probably not. Does it hurt? I don't think so. Who does it target? Probably not many. So can we remove it? Probably.

**Comment by breakmt** [comment]
@cbscribe #17502 is 110% cool thing! thanks a lot!

**Comment by lawsonry** [comment]
@cbscribe I knew it was going to be the exact opposite of what I said lol. I know the feeling of needing a warning like that, so best to keep it in then. 

I did a visual test of what the difference is between having your collision shape fit **without scaling** versus **with scaling**. Take a look at these two gifs:

**Without Scaling (i.e., using the normal collision rect size handle):**
![scaling-collision-shape-rigidbody](https://user-images.githubusercontent.com/4774899/43907316-03d68908-9baa-11e8-9e2c-cd42cba7a708.gif)

**With Scaling (i.e., using the outer rect handles to adjust scaling of collision rect:**
*Scaling: 2.99x2.99*
![scaling-collision-shape-rigidbody-with-scaling](https://user-images.githubusercontent.com/4774899/43907373-250bc322-9baa-11e8-987e-4711f4862564.gif)

I think seeing the difference visually helps to make my previous point: that the scaling of the collision shape--rather than its area--affects how the physics engine applies things like bounce and friction effects.

**Comment by lawsonry** [comment]
Okay I have a more illustrative example.

Take a look at this setup. I have some map tiles that I have created some collision shapes over, as children of static body 2d nodes. So it goes:

```
Sprite
+ StaticBody2D
+ + CollisionShape2D
```

As you can see from the [comment above](https://github.com/godotengine/godot-docs/issues/1568#issuecomment-411788689), applying scale modification to the collision shape results in some subtle differences in how things like bounce and friction are computed.

A more salient example is in trying to scale your StaticBody2D around your sprite. 

Let's say you have some tiles that you want to put collision shapes around for a 2d Platformer:

![half-scale-on-static-body2d](https://user-images.githubusercontent.com/4774899/43913990-6af0b058-9bbb-11e8-9531-09fe6385c8d1.png)

In the above screenshot, you can see that I have inadvertently scaled the StaticBody2D rect to fit my tile exactly. Then, I created CollisionShape2D's as normal, each one having a normal Scale(1,1). 

Now here's what our example looks like before playing:

![map-looks good](https://user-images.githubusercontent.com/4774899/43914085-b7dc4530-9bbb-11e8-93a6-5ac2f1177a00.png)

Great. Let's run this bad boy:

![look at result](https://user-images.githubusercontent.com/4774899/43914119-ca6f4b70-9bbb-11e8-921d-803d687068ed.png)

Ah, see what happened? The StaticBody2D's scale difference was applied to its children's sizes. It's as if the 50% scale for the StaticBody2D was computed for its CollisionShape2D children as meaning "Assume that you are 50% smaller than you are supposed to be." 

Adjusting the scale of the StaticBody2D back to Scale(1,1) in the editor illustrates this, as it causes the children CollisionShape2D's to expand by 50%:

![resetting-static-body-scale](https://user-images.githubusercontent.com/4774899/43914205-092379e0-9bbc-11e8-81f8-349d16e69783.png)

I hope these help to illustrate what's going on.

**Comment by lawsonry** [comment]
@bojidar-bg Thank you! I was just trying to illustrate what the original poster was talking about. 

I think once all the changes in master are pushed out to a new release, a lot of the issues I see around here will go away.

Keep up the great work!

**Comment by Calinou** [comment]
Is this still an issue in Godot 3.2?

**Comment by Calinou** [comment]
Closing, as this was most likely solved in Godot 3.2 judging by the discussion above.
