### ISSUE TITLE
The doc says the SceneTree has no getter for network peer, but there is one

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot-docs#1579]
http://docs.godotengine.org/en/3.0/tutorials/networking/high_level_multiplayer.html#initializing-the-network

The doc says to keep a reference to the `peer` due to inexistent getter after setting it on `SceneTree`, and mentions a workaround using `set_meta`.
However, none of this is needed since the getter exists as a property.

It is going to change in 3.1 though.

cc @Faless

**Comment by Faless** [comment]
Okay, I kinda lost track of this email.
In any case... My idea was to deprecated `get_tree().[Network related stuff]` in favour of the new `multiplayer` property in `Node`.

**Comment by jonbonazza** [comment]
@Calinou @NathanLovato at this point this could be considered a bug rather than an enhancement as Zylann is correct. Even with Fales' recent(ish) refactoring of the multiplayer api in relation to rhe scene tree, there is still a way to get a reference to the peer instance if needed. In fact, a lot of these docs likely need to some work, as I don't believe many if them have been updated at all to reflect Fales' changes.

**Comment by Mickeon** [comment]
Not very knowledgeable of how the current inner workings of online are in Godot, but is this relevant for 4.0?

**Comment by Faless** [comment]
Indeed, the [docs for 3.5](https://docs.godotengine.org/en/3.5/tutorials/networking/high_level_multiplayer.html) doesn't seem to reference `set_meta` anymore (and instead mention `get_network_peer`).
This also changed a bit in `4.0` to use `multiplayer` instead of `get_tree()`, so the docs will need to be rewritten.
