### ISSUE TITLE
Explain why FPS camera is rotated

### ISSUE THREAD

**Issue by rcorre** [godotengine/godot-docs#1599]
From a note in the [movement section of the FPS tutorial part 1](http://docs.godotengine.org/en/3.0/tutorials/3d/fps_tutorial/part_one.html#making-the-fps-movement-logic):

> Because the camera is rotated by -180 degrees, we have to flip the Z directional vector. Normally forward would be the positive Z axis, so using basis.z.normalized() would work, but we are using -basis.z.normalized() because our camera’s Z axis faces backwards in relation to the rest of the player.

This sounds pretty confusing to a newbie. This very text admits there is a simpler way to do it ("Normally forward would be the positive Z axis"), so why on earth does the tutorial choose this confusing camera rotation?

I'm guessing there is a good reason, so an extra sentence or so explaining **why** would be great.

**Comment by TwistedTwigleg** [comment]
> ... why on earth does the tutorial choose this confusing camera rotation?

Well, there is one major reason behind it being this way: The `Camera` node always faces the negative Z axis! The only way you can change it would be to go into the Godot source and make a change there.

> This very text admits there is a simpler way to do it ("Normally forward would be the positive Z axis")

What I was meaning to say is something like this: 

"Normally nodes face forward, pointing towards the positive Z axis, so using basis.z.normalized() would work"

It should be easy enough to change the note to something like this, which should help clear up any confusion:

"Because the camera is rotated by -180 degrees, we have to flip the Z directional vector. Normally nodes face forward, pointing towards the positive Z axis, so using basis.z.normalized() would work, but we are using -basis.z.normalized() because Camera nodes face the negative Z axis instead. We are using -basis.z.normalized() so when we move the player, we are moving them in the same direction the camera is facing"
