### ISSUE TITLE
Document RigidBody methods

### ISSUE THREAD

**Issue by rcorre** [godotengine/godot-docs#1696]
At http://docs.godotengine.org/en/latest/classes/class_rigidbody.html#member-function-description, the following are undocumented:

- `add_central_force ( Vector3 force )`
- `add_force ( Vector3 force, Vector3 position )`
- `add_torque ( Vector3 torque )`
- `apply_central_impulse ( Vector3 impulse )`

As a user, I wonder:

- is `add_central_force(force)` equivalent to `add_force(force, Vector3(0, 0, 0))`?
- is `apply_central_impulse(impulse)` equivalent to `apply_impulse(impulse, Vector3(0, 0, 0))`?
- what is the difference between `add_force` and `apply_impulse`?
- what is the difference between `add_torque` and `apply_torque_impulse`?

**Comment by cbscribe** [comment]
You're looking at the docs in the `latest` branch, which includes functionality that is in development now. `add_central_force()`, for example, is a new method. Documentation typically comes later, as things may still change between now and a beta release of 3.1.

If you're using 3.0, you should switch to the "3.0" or "stable" branch of the docs.

As for your other questions, which apply more generally:

`add_force()` applies a constant force to a body. The force continues until it's removed. For example, to implement a rocket's thrust you'd add a force while the engine was thrusting and remove it when it turns off.

`apply_impulse()` on the other hand is an instantaneous "kick". This is analogous to hitting a ball with a bat. 

The torque-related methods are similar, but with "twisting" instead of linear forces.

**Comment by rcorre** [comment]
@cbscribe yes, I'm on (more-or-less) latest. I had assumed that API docs were generated from comments or something similar, and would update alongside new functionality.

Anyways, thanks for the explanations. Hopefully those can make it into the docs whenever they are ready.

Do you know if `add_central_*` is the same as `add_*` with the position at 0, 0, 0? If so, why not just `add_force(force, position=Vector3(0, 0, 0))`? Unless `position` is actually supposed to be the first argument, to mirror `apply_impulse`. It seems weird that the two have opposite argument orders:

```
void add_force (force, position )
void apply_impulse (position, impulse )
```

Is that intentional, or a typo?

**Comment by cbscribe** [comment]
> `void add_force (force, position )`
> `void apply_impulse (position, impulse )`

Good catch - those should be standardized.

**Comment by TGRCdev** [comment]
Whoops, these are functions [I added](https://github.com/godotengine/godot/pull/20404). I can go back and add documentation once I get home.
****
>is add_central_force(force) equivalent to add_force(force, Vector3(0, 0, 0))?

In practice, yes. In code, the implementation is a *bit* different:

```c++
void add_central_force(const Vector3 &p_force) {
		applied_force += p_force;
}

void add_force(const Vector3 &p_force, const Vector3 &p_pos) {
		applied_force += p_force;
		applied_torque += p_pos.cross(p_force);
}
```

The same applies to `apply_impulse` and `apply_central_impulse`.
****
>```
>void add_force (force, position )
>void apply_impulse (position, impulse )
>```
>Is that intentional, or a typo?

No, that's how it was implemented in `body_sw.h` before I touched it. Actually, the order of those two change a lot across 2D and 3D, and across `force`, `impulse` and `torque`. I can open an issue for that to discuss the best way to handle this at the next compatibility breakage.

**Comment by rcorre** [comment]
> I can open an issue for that to discuss the best way to handle this at the next compatibility breakage

Sounds great! I was thinking these were totally new and we had the opportunity to solidify the API before 3.1, I didn't realize they were already in the 2D API.

**Comment by NathanLovato** [comment]
Thanks for letting me know. If you find any other, could you please ping me (@gdquest)? Otherwise, I may not get a notification.
