### ISSUE TITLE
Add more information about getting One-Click Deploy to work

### ISSUE THREAD

**Issue by unfa** [godotengine/godot-docs#1712]
I've got trouble getting my One PLus 5T to work with Godot via adb under Linux Mint.

After I followed installation instructions here:
https://github.com/M0Rf30/android-udev-rules

Suddenly - everything works!

I have spent weeks trying to get this to work, maybe it'd be good to mention this in the manual?

**Comment by The5-1** [comment]
Bumping this since https://docs.godotengine.org/en/3.1/getting_started/workflow/export/one-click_deploy.html is really quite sparse in giving directions that may aid the reader in troubleshooting.

For me it was simply a matter of revoking USB debugging authorization, see:
https://stackoverflow.com/questions/23081263/adb-android-device-unauthorized
