### ISSUE TITLE
Particles section of "Your first game" needs more explanation

### ISSUE THREAD

**Issue by Todilo** [godotengine/godot-docs#1714]
I don't seem to get to be able to set the same settings as in the tutorial and with no further explanation it's really hard.

- Visibility rect is by default set to AABB and no instruction on how to set it to Rect3
- Scale curve is by default <null> and no instruction how to set
- The gradient has offset which is set to FloatArray[2] with no instruction how to set to 0
- Same with color that is to be set to 0
Overall no real explanation how any of it works.

**Comment by fabslab** [comment]
I think Rect3 is just from an old version of Godot since if you open the project code for that tutorial it is set to AABB not Rect3.
The color section has a decent explanation and you can dig into the arrays and set the individual values using the indices property.
The one thing I can't figure out though is how the Scale Curve was set.
