### ISSUE TITLE
"Your first game" is way too complicated an example 

### ISSUE THREAD

**Issue by triptych** [godotengine/godot-docs#1730]
The "your first game" example : http://docs.godotengine.org/en/3.0/getting_started/step_by_step/your_first_game.html
As a tour of the features of Godot is good, but as a "first game" example it's WAYYY too complicated.

As a developer I was able to track along until the documentation started to make assumptions about hooking up events, and passing flags around, with multiple scenes. As a first game that's super complicated for a first time Godot user.  This should be like game #3 not game #1 .

Also, as a first game there aught to be a few "checkpoints" where the tutorial asks the player to run the game to see if things are working.  I got through all the tutorial and kicked off the game only to have a blank screen -- which of course meant I missed something, but if there were a few checkpoints in the documentation like "try things out now" it would be less of a big task to go back and try to debug everything. This also is another example of how this "Your first game" is too complicated for a first time Godot user. 

Having a player object move, then enemies, then layer in the paths, multiple scenes, etc. would be a better way to ramp up the difficulty without frustrating the user.

**Comment by cbscribe** [comment]
I'm revising this for the 3.1 release, so your comments/suggestions for pain points and clarifications are welcome. I especially like the idea of checkpoints.

I don't, however, agree with your premise. I designed this game based on beginner projects done with my students, and it has the goal of demonstrating the essentials you need to know for just about any Godot project. This game is placed in the "Step by step" section after the sections on creating scenes, scripting, and instancing. This is supposed to be a project that ties it all together.

I am thinking that there should probably be a "Signals" tutorial after "Scripting" but before "Your First Game". Signals are very important to understand for working with Godot. A brief doc similar to the "Instancing" one that demonstrates their uses would likely go a long way to helping new users.

**Comment by triptych** [comment]
I agree that it covers all the things that one might need in a game, I just believe that for a first game, it may be overwhelming for someone starting out in Godot. Adding the checkpoints, in my opinion would help make it easier to digest for newbie Godot users, as am I.

**Comment by triptych** [comment]
Also, in terms of pain points, when you start to discuss the UI, I felt like I was "doing it wrong" because the screenshots did not match with what I was seeing. Perhaps move the custom fonts part before the layout part. Just another comment.

**Comment by pwab** [comment]
> I designed this game based on beginner projects done with my students [...]

Are your courses text based @cbscribe or is the class taught by presenting the steps so the students can repeat? I ask because I can understand the point of view that a comprehensive first game example can be overwhelming when you have to take the steps alone with only a text as your guide.

On the other hand it is stated at the beginning that you have to have some programming experiences, the project files can be downloaded and all in all it is a very well polished and still compact game. And it needs time and patience when getting in touch with a new environment (if you come from another engine/framwork) or you start game programming from zero, @triptych. I'm not sure if an even easier game example would be that much better. You still have to dive deep into other peoples code, getting a grasp of the logic behind every aspect of the engine and you need to read/watch a lot to really understand what you are doing in those kind of tutorials. That is the way to go I guess.

Just a quick thought: Maybe linking to your [video series](https://www.youtube.com/watch?v=uPoLKQG0gmw&index=1&list=PLsk-HSGFjnaFutTDzgik2KMRl6W1JxFgD&t=0s) could be helpful for people prefering a presented tutorial, @cbscribe? Wasn't this discussed before somewhere else?

**Comment by cbscribe** [comment]
> I ask because I can understand the point of view that a comprehensive first game example can be overwhelming when you have to take the steps alone with only a text as your guide.

Of course, that's always going to be the benefit of having the instructor in the room. Whether watching a video or reading a document, if you don't have a person to talk to when you get stuck, you're going to have a bit more trouble.

We get a wide range of readers to the docs. The priority has generally been to address the documentation to those looking to learn Godot, not those looking to learn coding in general. As someone who teaches programming, I don't really think Godot is a great place to start for the latter. A game engine is a complex collection of specialized tools, and is too much to throw at a beginner.

That said, the beginners are still going to try, so we can try to make things as friendly as we can and point them to other novice-level resources where we can. I already have a list of changes/ideas for the next revision, which I'm going to start on soon.

> Just a quick thought: Maybe linking to your video series could be helpful for people prefering a presented tutorial, @cbscribe? Wasn't this discussed before somewhere else?

It's been discussed, but it's problematic. Videos take much longer to make and can't be easily changed. The docs are constantly getting updated and improved, so the video version will quickly get out of date.

**Comment by triptych** [comment]
As someone who worked on the game via a series of evenings over a week or so, I've voiced my concerns and the author has already mentioned the steps he's going to take to address them. My primary issue was just that getting some positive feedback in the midst of the tutorial with pauses to try out what you have so far will go a long way to making someone feel successful going through the  tutorial, regardless of it's length or complexity.

**Comment by fabslab** [comment]
I think the tutorial is great, it covers the right amount of features imo but there are a few things skipped over. One that I can't figure out though is how to set the scale curve of the particles material so that it matches the one there, I don't see any reference to any texture file in that project and don't know how to create it in the editor.
