### ISSUE TITLE
Simplex Noise ClassRef Typos

### ISSUE THREAD

**Issue by clayjohn** [godotengine/godot-docs#1748]
Many of the values in the method descriptions in the Simplex Noise class reference are using two ` instead of three. So they are not getting properly formatted.

**Comment by akien-mga** [comment]
It's expected to use two backticks for inline code formatting, but apparently reST chokes on it if there's no space between the tokens (so <code>\`\`x\`\`, \`\`y\`\`</code> would work but <code>\`\`x\`\`,\`\`y\`\`</code> doesn't).

Should be fixed in the XML: https://github.com/godotengine/godot/blob/master/modules/opensimplex/doc_classes/SimplexNoise.xml#L59

Simple fix would be to add spaces after commas (including in the codeblock examples btw, as that's our GDScript style guide), but the explicit names of arguments could also be removed in the description as it's somewhat redundant with their existing info on arguments names and types.

CC @JFonS

**Comment by akien-mga** [comment]
Fixed by godotengine/godot#22259.
