### ISSUE TITLE
Thinking of "Your first game" tutorial

### ISSUE THREAD

**Issue by flydyman** [godotengine/godot-docs#1751]
Hi there!
When I tried to make this tutorial by myself, I've got not worked project. There will be nice to change code sections more detailed, f.e. after adding new lines of code, list full function with highlited new lines. 
I know about full source at the end of page, but this is "step-by-step" tutorial, and after completing this one end-user need to run working application and not comparing his source with "right" sources from github. 
That was my opinion.

With best regards

**Comment by pwab** [comment]
Thanks for the feedback!

Which errors/warnings you got while writing the code or what error poped up when you tried to run the game? Maybe there are unclear instructions on where to enter a specific part of the code.

The idea in adding a full code block after each step is okay as long as this is only optional for the reader. There could be a spoiler tag hiding the full source block or we could add a zip after each step.

But it would be much easier to understand **why** the wrong copy&paste happened in the first place. So we won't blow up this tutorial too much.

**Comment by cbscribe** [comment]
First off, I'm sorry you had trouble with the tutorial. I do recommend you check out the [Community resources](https://godotengine.org/community), especially the Discord and Q&A where you can get help when you are having a problem.

I would be interested in exactly where you encountered problem(s). 

@flydyman are you a beginner to programming in general? The Godot docs are targeted at those who want to learn how to use Godot, not those who are new to programming entirely. Learning to code is an completely different task.

Also, as a general bit of advice, you should *never* copy-and-paste from a web tutorial. Type the code in yourself - it will lead to much more successful learning.

As for possible actions, as I'm in the process of revising this tutorial for the 3.1 release: If we include a full code listing after every change, the tutorial will become *very* long and we have the problem of people not wanting to do it because of that. It also gets harder to find things because every section looks the same. I'm asking others for more feedback so we can see what the prevailing opinion is.

**Comment by triptych** [comment]
One method I've seen some tutorials do is link to the sourcecode in git --  you might have like a tutorial folder, and inside that folder step1, step2 etc which are complete listings for the tutorial at that point.  Another method I've see is have one code listing, but each step is another tag/branch/commit hash which you link to in the documentation. So you might have filex.ext which is the complete listing, but if you look at the checkins for it, you can see the progression from empty file to complete listing. In the docs you point to that file + the commit hash.

All that is a lot of work however for the documentation writer. As I mentioned in another issue comment, just having pauses in the tutorial where you ask the reader to go compile and run the code at that point and see if it's working would be a big help. It's when you go through a lot of information without a pause to let them see if what they have is working is the main issue. Seeing gradual progress is really motivating for the reader to complete the tutorial, instead of going all the way through it and have it not work because they missed something in step 2.

**Comment by cbscribe** [comment]
Closing this, as OP never responded to questions. Also, the new tutorial for 3.1 will add more clarifications and test checkpoints.
