### ISSUE TITLE
"Online Tutorials", is it place for videos? Can I make them?

### ISSUE THREAD

**Issue by Shultc** [godotengine/godot-docs#1773]
Hello,
I started to work with Godot (C#), and noticed that documentation have always empty sections "Online Tutorials".
![godot engine](https://user-images.githubusercontent.com/458282/46276545-1a671000-c569-11e8-9a80-cbdf283236bf.png)

Is it place for video tutorials? I am interested to start youtube video series about Godot C# (it is really to hard find information right now). If I will brake those videos to parts, according to the documentations sections, can they be added there? Are those videos shall meet any other requirements?

**Comment by mhilbrunner** [comment]
Currently, the "Online Tutorials" section is mostly used to point to relevant tutorials on the official Godot docs website, as far as I know.

The only place that comes to mind that only links to third party tutorials is the Community Tutorials section in the docs:
http://docs.godotengine.org/en/stable/community/tutorials.html

Also not sure how we would divide C# and GDScript tutorials there.

Maybe this would be best to discuss on the Godot Discord, in the #documentation channel :) Most of the docs team hang out there.

More video tutorials would of course be very welcome!

**Comment by Shultc** [comment]
Thank you, for your answer.
I don't have discord... Will try to figure it out, to contact Community Tutorials team.

I understand, that "more video tutorials would be very welcome", but if they will be unfindable; making of them will be waste of time

**Comment by mhilbrunner** [comment]
Closing, as this was discussed on Discord.

Consensus seems to be this, by @cbscribe/KidsCanCode:

*Other contributors can chime in here, but I am against the idea of having videos for individual pages in the documentation. It's just not practical. With a written page, others can submit a PR for changes. Are you going to edit/re-record the video every time there needs to be a change? We spend a lot of effort making sure the docs are in clear, proper English, since the readers may be non-native speakers. The language/voice in the videos would need to be very clear and neutral for the same reasons and again, impossible to change efficiently.*
