### ISSUE TITLE
I can not get this to work

### ISSUE THREAD

**Issue by KoopHauss** [godotengine/godot-docs#1789]
extends KinematicBody2D

export (int) var speed = 200
export (float) var rotation_speed = 1.5

var velocity = Vector2()
var rotation_dir = 0

func get_input():
    rotation_dir = 0
    velocity = Vector2()
    if Input.is_action_pressed('right'):
        rotation_dir += 1
    if Input.is_action_pressed('left'):
        rotation_dir -= 1
    if Input.is_action_pressed('down'):
        velocity = Vector2(-speed, 0).rotated(rotation)
    if Input.is_action_pressed('up'):
        velocity = Vector2(speed, 0).rotated(rotation)

func _physics_process(delta):
    get_input()
    rotation += rotation_dir * rotation_speed * delta
    move_and_slide(velocity)

this is the supplied code for Rotation + Movement; I can't get it to work. I even copied and pasted it into the script. I think I'm done with this engine, your documents are a joke. They're no help. Cause you have no context in any of your tutorials. You don't explain any of the How? When? or Why? questions. You lazily refer us to some list that may as well be written in some sort of alien language. At least if you aren't already fluent in some sort of programming language. None of your lists help people who don't know programming!

2/3rds of the follow along tutorials don't make sense, and don't work! And if they do, HOW? Would, I ever be able to find out what I'm doing wrong if there is no video content or anyone to show me what I did wrong. Not that there isn't video content . . . just not content of the tutorials. Except for the creeps game of which I'm sure that the creator of that content is the same person that does the correlating video. But I don't know for sure, I just know that the video really did help to follow the documentation, because the video pretty much went along with the docs. 

The problem with most content creators on those popular tube channels is that they care more about popping out videos that show off how well they can do something by just narrating what they're doing on screen. There's no context!

 I'm done with this engine. Anyone at all who has never programmed . . . there are other engines out there that are currently open source and have been around for 20+ years. Yes there is bad, even horrible content out there as far as tutorials go for these popular engines, but I promise you will be able to find more good and great content more often for them than you will for godot. There just isn't anyone who know's it well enough to be able to really teach it.  And if you think I just can't learn it . . . Then you're one of those who can't teach it.

**Comment by NathanLovato** [comment]
I understand you're frustrated. Learning to code is hard, and you're going to face obstacles along the way. But that's not the way to give feedback: this manual is the collective work of 270 persons who worked benevolently - and many more if you take in account the translations in progress. It's a massive undertaking, a complex wiki that has to speak to all kinds of audiences with different needs. And people keep improving it.

> content creators [...] care more about popping out videos

As one of these content creators, I can tell you that you're absolutely wrong. You seem to have no idea of the work it takes to research topics, create code examples, edit and publish tutorials. People like Chris, Mike, and I work long hours and help people for absolutely free. Now the reason the tuts aren't working for you is it's impossible to make tutorials that work for absolutely everyone, and we each have mostly make tutorials for people who already have at least some programming experience. If you make the video or tutorial slow enough for someone who never programmed before, then it's bad for someone who already has a little more experience.

Have you tried the Udemy course by Gamedev.tv? It's super affordable, and they focus on step-by-step content for beginners.

Constructive criticism is always welcome. In this post though, you're spitting on educational material that works for a lot of people, thousands of hours of work, just because it doesn't work for you *right now*. If you have 0 experience with game design and programming, a simpler tool may be better to get started. Something like [GDevelop](https://gdevelop-app.com/) for instance.

Godot is a complex engine with thousands of features. It's not necessarily the best tool for your first projects - it all depends on where you're at right now.

**Comment by triptych** [comment]
Recommend closing this issue as it's not really an actionable bug in the documentation.

**Comment by KoopHauss** [comment]
I think I closed all my open issues, thanks for the feedback. I'll check
out the link.
