### ISSUE TITLE
Documentation updates

### ISSUE THREAD

**Issue by djrm** [godotengine/godot-docs#189]
I've been thinking about updating some material for the docs in order to match the new features in 2.1, but it came to my mind that it is possible that some people for some particular reason want to stay in an older version of godot, so maybe the documentation should have something like different versions. 
Of course this introduces the big problem of the fragmentation of the documentation, since basically more content will be added for newer version, while the previous versions get outdated. (notice that this fragmentation is natural and inevitable since there's already a lot of unofficial content targeted to the current version)

I would prefer to keep the official documentation up to date with the latest stable version.

**Comment by akien-mga** [comment]
For the time being I think we shouldn't bother trying to keep documentation for older versions. I don't see any reason why users would want to stay on 2.0.x instead of using 2.1 when it's out (unless it's super buggy, but we won't release it if it's buggy anyway). Maybe for 3.0 is the new renderer is troublesome for simple games meant to run on low-end hardware, then we could keep documentation around for 2.1.

**Comment by hanst99** [comment]
If documentation for older versions of godot is desired it should simply use an older build of this documentation at a different mirror. There's no point in keeping the documentation for multiple versions within a single document, except to highlight changes to previous versions.

**Comment by cbscribe** [comment]
Can we close this issue as we now have 2.1 and master doc branches?

**Comment by NathanLovato** [comment]
Yeah let's close - we can always reopen issues
