### ISSUE TITLE
Please add  a review process before publish the translations

### ISSUE THREAD

**Issue by Geequlim** [godotengine/godot-docs#1981]

**Comment by Geequlim** [comment]
The translations from weblate may contain errors that would mislead new users.

People prefer untranslated versions instead of translated versions modified with machine translators.

Please add a review process to keep the documentation safe.

**Comment by akien-mga** [comment]
While I agree that bad translations are worse than no translation, the sheer size of our translation content makes it quite hard IMO to enforce a review process before publishing.

I do agree that machine translation should be avoided, and I should have asked for review when seeing that a commit brought zh_CN translations from ~50% completion to 100%. I had a cursory check myself to ensure it wasn't spam, and the translated strings seemed to have the same punctuation and references to latin Node names as the `msgid`s, so I went ahead with it.

Apart from such obviously suspicious changes, it's pretty difficult to enforce a review process IMO. Godot's documentation has 11000 strings, and it grows all the time as contributors write new tutorials. There are dozens and dozens of hours of work needed to bring any given language to a decent level of completion for so much content, and I feel that enforcing pre-publishing reviews would slow down the process *a lot* (as @bojidar-bg says Weblate already has such a feature, yet there are hardly any strings which have been reviewed/approved yet, because there is still so much work to do).

IMO the workflow should be two step:
- First translate the content, avoiding machine translation but still allowing imperfect translations in the first pass. Many translators are not experienced technical translators and produce subpar content, but a first draft is still valuable.
- Once the translation is complete, proofread everything to ensure a high level of quality.

That's why for now I push updated translations without asking for reviews, as it's easier to get new contributors involved if they see mistakes in the translations, than if they don't see any translation at all. Translations are limited to the `latest` branch for now, so they're not set in stone and can continue to be improved.

**Comment by akien-mga** [comment]
On the topic of machine translation, I could revert the state of zh_CN translations to before the commit that added machine translations if you want (Dec 3).

**Comment by Geequlim** [comment]
@akien-mga 
Yes I agree with you that is hard to review such a large translation content with the community and the review process might slow down the translation process.

> IMO the workflow should be two step:
> First translate the content, avoiding machine translation but still allowing imperfect translations in the first pass. Many translators are not experienced technical translators and produce subpar content, but a first draft is still valuable.
Once the translation is complete, proofread everything to ensure a high level of quality.

I'm totally agree about that.

Here are my suggestions to make the translation process safer:
* Don't publish the translations without target language speaker's review for stable.
* Add a notice on top of each translation page to tell readers that the article was translated by community and it may contain errors.
* Add a link to the origin article for each translation page.

**Comment by akien-mga** [comment]
Good suggestions, I was also thinking about adding a banner that would tell that translations are community-provided works in progress and that if anything is unclear, people should refer to the English version (and/or help fix the translation).

Do you want me to revert the zh_CN translation to the previous state (~50% complete a priori manually translated), or is the machine translation still a useful base for reviewing it all?

**Comment by Geequlim** [comment]
I reviewed some of the translations `tangdou1` commited. Some of that is useful and he/she is trying to improving the machine translated contents. So I think it is OK to keep that in the master version of the ducumentation.

**Comment by akien-mga** [comment]
For stable, maybe we can have a policy that we'll only build stable docs for those with > 50% of reviewed (proofread) content on Weblate.

**Comment by Geequlim** [comment]
That's good idea.

Rémi Verschelde <notifications@github.com>于2018年12月6日 周四19:59写道：

**Comment by tangdou1** [comment]
In my opinion, it is just to early to talk about the reviewing issue for the translating documents since there is no more than three persons who is continuously trying to translate these documents and there are also many machine translation in the previous translation. For newbie, it would be always good for them to read these technical documents in their local language even if these documents are translated by machine. However, it would be better to improve these translations in future.

**Comment by Omicron666** [comment]
Imho only content that has been reviewed by human should be able to skip the Needs editing / to verify tag.

Has the author reviewed all strings he pushed (even though from a machine translation) ?
Asking just about fairness compared to displayed progress of other languages. (I was nicely surprised (but kinda duped ?) by the 100% green state of Chinese translation)
And also so translators have any ideas of what needs to be actively reviewed...

Some of machine translations could be used for other languages too, in such case.

But imagine if we push machine translations for all other languages with 100% checked state. Godot Engine suddenly 100% translated in 100+ foreign languages ? x_x

**Comment by NathanLovato** [comment]
Should we close the issue for now? Looking at weblate, it seems at least that for some of the docs, people use the review / needs editing feature right now.

**Comment by mhilbrunner** [comment]
Closed, seems the discussion above has run its course. Thanks everyone!
