### ISSUE TITLE
get_node() in Scripting tutorials

### ISSUE THREAD

**Issue by pikmeir** [godotengine/godot-docs#2079]
The Scripting tutorial shows get_node() examples instead of the new format.

http://docs.godotengine.org/en/stable/getting_started/step_by_step/scripting.html

**Comment by bojidar-bg** [comment]
Link to latest: http://docs.godotengine.org/en/latest/getting_started/step_by_step/scripting.html
Still valid there tho. Probably intended, as `get_node` is easier to grasp at first.

**Comment by cbscribe** [comment]
Agreed. New users should understand `get_node()` first, then be introduced to the shorthand.

**Comment by LuminousLizard** [comment]
Greeting !

I place my question here, because it's about the same function and the same chapter.
At the end you write:

> If Button were instead a child of Label, the code to obtain it would be:
> `get_node("Label/Button")`

but if I create a scene with 2 buttons (1 is child of Label, the other child of Node) ...
```
-> Node
--> Label
---> Button
--> Button
```
... and write following script ... 
```
extends Panel
func _ready():
	get_node("Label/Button").connect("pressed", self, "_on_Button_pressed")

func _on_Button_pressed():
	get_node("Label").text = "Hello !"
```
... then both buttons execute the function. Is that so ?

When I write following, then only the button (chid of node) executes the function:
`get_node("Button")` 

But if I write following, then BOTH buttons (child of node and child of Label) executes the function:
`get_node("Label/Button")` 

By the way: Thanks for the great game engine :+1:  .

**Comment by bojidar-bg** [comment]
@LuminousLizard You probably have connected `get_node("Button")` to the same function using the UI.

**Comment by LuminousLizard** [comment]
@bojidar-bg That was the problem. Thanks !

**Comment by BridgetNichols** [comment]
I assume by the new format you mean using `$` as a shorthand to `get_node`. If so a possible way of going about this without making it more difficult for beginners, is to keep using `get_node` but also mention `$` as an easier alternative to `get_node`. For example, when the text is explaining what `get_node` does, it can also explain the shorthand term. In the code examples, there could also be comments showcasing the alternative format. For example:
```
func _ready():
     get_node("Button") # Alternatively $Button
```
If you're not talking about using `$` then that's a little embarrassing on my part, but I've been wanting to contribute to this project for awhile now, and I thought I may as well see if I may be able to contribute to something.

**Comment by mhilbrunner** [comment]
@BridgetNichols Feel free to submit a PR adding a note to point out that the alternate syntax using `$` may be used, maybe with an example. :)

I think that would be good addition. Closing this issue now, as the original point has been discussed I think.
