### ISSUE TITLE
Serious oversights in the latest shader docs

### ISSUE THREAD

**Issue by MysteryGM** [godotengine/godot-docs#2192]
Hi, so the latest shader documents have more problems than the older one. Even with the shaders broken into 3 parts, because there is less information on making a shaders.

Problems:

1.) The first main problem is that there is almost no mention of uniform or varying, only a very small snipped in [Canvas shader](https://docs.godotengine.org/en/latest/tutorials/shading/shading_reference/canvas_item_shader.html#doc-canvas-item-shader) and just in passing. - This problem was brought to my attention by a ex-Godot user who said Godot's shaders doesn't support variables.

2.) The second problem is that there is no example of what any of these shaders look like. Only detailed descriptions of the parts that aren't as useful to anyone who hasn't used a shaders before.

3.) Even users who learn how the shaders work, have no idea of how to link them with the game or how to send properties from the script to the shader.

Suggestion:

Every shader category could start with a example, and breakdown of the shader's anatomy.
Here the shader will show the parts and how variables are used.
Every shader could be independent and not require knowledge from other shaders, even if it means re-explaining a concept.

The [main shader](https://docs.godotengine.org/en/latest/tutorials/shading/shading_reference/shaders.html?highlight=shader) page could explain how shaders are manipulated with code and how to access the shader variables.
It could also be that this problem is too big, that a separate documentation page is needed to properly explain how shaders work.

A lot of the in-depth knowledge would be better placed at the end, for people who want to know the inner-workings of shaders.

**Comment by akien-mga** [comment]
CC @clayjohn

**Comment by clayjohn** [comment]
@akien-mga I will address each of the statements in turn. However, I would first like to say that it really seems like he has not read much of the documentation. 

> Hi, so the latest shader documents have more problems than the older one. Even with the shaders broken into 3 parts, because there is less information on making a shaders.

All of the information from the old docs was carried forward and expanded upon. Nothing was deleted form the old documentation. Please provide a specific example of something that is missing. 

> 1.) The first main problem is that there is almost no mention of uniform or varying, only a very small snipped in [Canvas shader](https://docs.godotengine.org/en/latest/tutorials/shading/shading_reference/canvas_item_shader.html#doc-canvas-item-shader) and just in passing. - This problem was brought to my attention by a ex-Godot user who said Godot's shaders doesn't support variables.

Here is the section on [Varyings](http://docs.godotengine.org/en/latest/tutorials/shading/shading_reference/shading_language.html#varyings) and here is the section on [Uniforms](http://docs.godotengine.org/en/latest/tutorials/shading/shading_reference/shading_language.html#uniforms). The uniform section contains substantially more information than in previous versions. 

> 2.) The second problem is that there is no example of what any of these shaders look like. Only detailed descriptions of the parts that aren't as useful to anyone who hasn't used a shaders before.

This is because they are in the section titled "shading reference". They are not meant as in-depth tutorials but rather as a reference document on the features of each shader type. 

I have plans to write tutorials aimed at beginners, but I have not yet had the time. I spent months updating the shading reference as it is.

> 3.) Even users who learn how the shaders work, have no idea of how to link them with the game or how to send properties from the script to the shader.

The [Vertex displacement with shaders](http://docs.godotengine.org/en/latest/tutorials/shading/vertex_displacement_with_shaders.html) tutorial walks users through how to control uniforms from script. The [Uniform](http://docs.godotengine.org/en/latest/tutorials/shading/shading_reference/shading_language.html#uniforms) section of the shading reference also explains how to do so. I don't know what else we could add to make that more clear for you. There is only so many tutorials we can add on the same topic. At some point you just have to take the time and actually read the documentation in order to learn from it. 

> The [main shader](https://docs.godotengine.org/en/latest/tutorials/shading/shading_reference/shaders.html?highlight=shader) page could explain how shaders are manipulated with code and how to access the shader variables.
It could also be that this problem is too big, that a separate documentation page is needed to properly explain how shaders work.

The section you refer to is the shader reference. Again, a reference is not suited for in-depth tutorials focused on beginners. Those things are more suited for the tutorials section.

 >A lot of the in-depth knowledge would be better placed at the end, for people who want to know the inner-workings of shaders.

And for a final time. The shading reference is the place for more advanced information. Beginner information will be contained in beginner tutorials.

**Comment by MysteryGM** [comment]
> All of the information from the old docs was carried forward and expanded upon.

OK, so you are correct all the old information is there. The problem appears to be that a Google search of "Godot shaders" takes the searcher to this post: [https://docs.godotengine.org/en/latest/tutorials/shading/shading_reference/shaders.html?highlight=shader](url) the "shaders" page.
From here the user can go to, any of the 3 shaders without ever finding the "Shading Language" page.

In fact, when I tried to prove the ex-Godot user wrong, I had a similar problem where I could not find that page even after multiple searches for uniforms produced only the canvas shader. I had to point to the older documents.

Could a possible solution be to include a link to Shading language inside every shader type document?

> I have plans to write tutorials aimed at beginners, but I have not yet had the time. I spent months updating the shading reference as it is.

I understand, but in the meantime shader anatomy should cover a lot of the details of using a shader and be fast to make; a standard output shader can be used.

> The [Vertex displacement with shaders](http://docs.godotengine.org/en/latest/tutorials/shading/vertex_displacement_with_shaders.html) tutorial walks users through how to control uniforms from script.

Again this looks to be a problem with the links and order of the document. I actually use the Godot shaders a lot and never found that document page.

Right now everyone is just finding the "Shaders" -> "Spatial shaders" or what ever type they want and then they think they have read everything Godot has on shaders; as it looks like the end of the path.

Having a link at the end to "vertex displacement" could help to resolve this.

> Beginner information will be contained in beginner tutorials.

I can't seem to find this section either.

**Comment by clayjohn** [comment]
> From here the user can go to, any of the 3 shaders without ever finding the "Shading Language" page.

No. In fact, you can't even access either of the three shader pages without seeing the shading language page.

Here is a screenshot of the Shaders page
![screenshot 2019-02-16 at 1 33 40 pm](https://user-images.githubusercontent.com/16521339/52905480-83d17d80-31ef-11e9-8535-920ddd2ff288.png)
If you press "Next" it takes you to the shader language page.

Or you can reach it from the sidebar on the left.

Or if you go to the shading reference menu, its right there. Second in the list (before the three shader pages).

![screenshot 2019-02-16 at 1 31 30 pm](https://user-images.githubusercontent.com/16521339/52905481-8633d780-31ef-11e9-8646-82024db3f481.png)

> I understand, but in the meantime shader anatomy should cover a lot of the details of using a shader and be fast to make; a standard output shader can be used.

If its that easy, submit a PR

> Again this looks to be a problem with the links and order of the document. I actually use the Godot shaders a lot and never found that document page.

Its not our fault if you choose not to navigate the menus. Its on the first level of the [shaders tutorial page](http://docs.godotengine.org/en/latest/tutorials/shading/index.html).

![screenshot 2019-02-16 at 1 31 14 pm](https://user-images.githubusercontent.com/16521339/52905482-8b912200-31ef-11e9-9b40-7536b9f5a5a6.png)

> Having a link at the end to "vertex displacement" could help to resolve this.

When you view any shader document, all other shader documents are available with one-click from the sidebar menu.

Again, here is the Shaders page you can see on the left that all the shading reference documents and tutorials are on the left side.
![screenshot 2019-02-16 at 1 33 40 pm](https://user-images.githubusercontent.com/16521339/52905480-83d17d80-31ef-11e9-8535-920ddd2ff288.png)

**Comment by MysteryGM** [comment]
> No. In fact, you can't even access either of the three shader pages without seeing the shading language page.

An yet for some reason people still miss it.
![Example](https://i.imgur.com/wSlfmww.jpg)

> When you view any shader document, all other shader documents are available with one-click from the sidebar menu.

I didn't get to the documents by browsing the Godot docs, I jumped in from google. The bar slides down with the user, obscuring the side bar as they read the documents.

> If its that easy, submit a PR

Any rules I need to know about before submitting a PR?

**Comment by clayjohn** [comment]
> An yet for some reason people still miss it.

Your suggestion was that we provide a link. I showed you that there are three links. At that point if you miss it there is nothing else we can do. 

> I didn't get to the documents by browsing the Godot docs, I jumped in from google. The bar slides down with the user, obscuring the side bar as they read the documents.

This isn't something that can be fixed by amending the document itself. Take this up with [read the docs](https://readthedocs.org/)

> Any rules I need to know about before submitting a PR?

Yes, you can find them in the [docs](http://docs.godotengine.org/en/latest/community/contributing/index.html)

**Comment by clayjohn** [comment]
I have made a PR for some easier introduction shaders. Please let me know what you think. #2323

**Comment by clayjohn** [comment]
Fixed by #2323

**Comment by MysteryGM** [comment]
The shader tutorials are well made. Will be marking this as resolved.

If you have time you should announce the update on the forums, there is a lot of users who want to use shaders but don't know where to start.
