### ISSUE TITLE
Movement error

### ISSUE THREAD

**Issue by daboz5** [godotengine/godot-docs#2210]
Hi, down I copy-pasted what is in Godot Docs. It didnt work, then I figured that every movement is wrong one. It needs to be
right ---> ui_right
left ---> ui_left
up ---> ui_up
down ---> ui_down

Now it works for me. I am just learning, so it was quite a hurdle, I managed it because some tutorial in Godot 2.1 didnt have the right code for 3.1, but some parts of it were still right.

extends KinematicBody2D

export (int) var speed = 200
export (float) var rotation_speed = 1.5

var velocity = Vector2()
var rotation_dir = 0

func get_input():
    rotation_dir = 0
    velocity = Vector2()
    if Input.is_action_pressed('right'):
        rotation_dir += 1
    if Input.is_action_pressed('left'):
        rotation_dir -= 1
    if Input.is_action_pressed('down'):
        velocity = Vector2(-speed, 0).rotated(rotation)
    if Input.is_action_pressed('up'):
        velocity = Vector2(speed, 0).rotated(rotation)

func _physics_process(delta):
    get_input()
    rotation += rotation_dir * rotation_speed * delta
    move_and_slide(velocity)

**Comment by cbscribe** [comment]
I'm assuming you're referring to the section of the 2D Movement tutorial here:
http://docs.godotengine.org/en/3.0/tutorials/2d/2d_movement.html#rotation-movement

The reason the input actions didn't work for you is because you didn't follow the directions earlier in the tutorial here:
http://docs.godotengine.org/en/3.0/tutorials/2d/2d_movement.html#setup

In this section, you are shown how to set up the input actions for the tutorial, including a screenshot of how they should appear. Setting up custom input actions allows you to set additional keys, such as the W/A/S/D keys for movement, or the "click" action we use in other parts of this tutorial.

**Comment by daboz5** [comment]
Hi, I did those things (had to add keys), but my default was ui_[movement], not [movement], so I would also have to change that.

**Comment by cbscribe** [comment]
Yes, the `ui_*` actions are in the engine by default. But you are able, and instructed by the tutorial, to add your own. 

I'm going to close this issue as it's not an error in the docs.
