### ISSUE TITLE
Outdated UI in “Learning step by step”

### ISSUE THREAD

**Issue by vnen** [godotengine/godot-docs#228]
From @palrogg on godotengine/godot#6210:

> The [“learning step by step”](http://docs.godotengine.org/en/latest/tutorials/step_by_step/_step_by_step.html) pages are great but some parts use older versions of Godot:
> - older version of scene inspector in [Instancing, step by step](http://docs.godotengine.org/en/latest/tutorials/step_by_step/instancing.html#instancing-step-by-step)
>   (I had to click the button with a link icon, instead of "plus", which now adds a node)  → <img width="240" alt="scene_inspector" src="https://cloud.githubusercontent.com/assets/12730304/17823836/ac5250d6-662c-11e6-90a1-1c69ac234e08.png">
> - .scn instead of .tscn scene in [Instancing](http://docs.godotengine.org/en/latest/tutorials/step_by_step/instancing.html) and [Scripting](http://docs.godotengine.org/en/latest/tutorials/step_by_step/scripting.html)
> 
> If it may be useful, I can extend this list, as I'm going through these tutorials right now.
> 
> Thanks a lot for your work!

**Comment by UKNightWatch** [comment]
“learning step by step” - ["Simple 2D game"](http://docs.godotengine.org/en/stable/tutorials/step_by_step/simple_2d_game.html);

- Third image has node as "game" not as "Node2D" yet example script still has "extends Node2D" which is confusing
- Third image has other nodes renamed which is fair in practice but makes the tutorial confusing
- It is not made clear to reader that running / launching the tutorial game while following the tutorial will result in game not working - due to script added later. Confusion rains!

All this and, I suspect, more in the tutorial will 'throw' new or inexperienced users and frustrate them.

I can see the direction the tutorial is taking and could probably put right any faults as I work through it. Problem is, a tutorial like this should be a welcoming walk through for new (especially if inexperienced) users.

I do not know if the script issue is due to tutorial being written for an older version of GODOT. I do know that the poor correlation between the image and script I mention is inexcusable for a tutorial.

I'm not sure I would have the time to edit the tutorial to make it more welcoming and ... correct ..! I just wanted to point out the faults I have found so far.

**Comment by StraToN** [comment]
> Third image has node as "game" not as "Node2D" yet example script still has "extends Node2D" which is confusing
Fixed.
> Third image has other nodes renamed which is fair in practice but makes the tutorial confusing.
Fixed.
> It is not made clear to reader that running / launching the tutorial game while following the tutorial will result in game not working - due to script added later. Confusion rains!
It feels like common sense to me that an incomplete project will not work. Scripts add logic to scene nodes - without them, no logic, no movement, no reaction to inputs. Just a still game.

If the reader does try to run the project while reading while it is incomplete, the compiler will either complain (which is not a bad thing as the reader will then continue his reading and complete the scripts with their missing parts), or it will run but won't act as expected (which should result in the same reaction from the reader).

Anyway, this tutorial was recently improved and committed. I'll close this issue for now as I believe it is better than before. Also feel free to reopen and add you remarks if you need to.
