### ISSUE TITLE
Timer docs have no examples

### ISSUE THREAD

**Issue by mitchcurtis** [godotengine/godot-docs#2349]
https://docs.godotengine.org/en/3.1/classes/class_timer.html#class-timer-property-wait-time has no examples of how to use it. The documentation for signals does though:

https://docs.godotengine.org/en/3.1/getting_started/step_by_step/signals.html#timer-example

Though that example also doesn't mention that you need to add the timer as a child node:

https://godotengine.org/qa/4196/create-a-timer-dynamically?show=8236#a8236

I would gladly fix this myself but the readme for this repo says the rst files in classes/ are generated, and links to this instead:

https://github.com/godotengine/godot/tree/master/doc/classes

I have no idea how to link to the signals page from the Timer reference page. :/

**Comment by mitchcurtis** [comment]
Oh, also, it should document how to destroy the timer in the slot:

func shoot():
    # snip

    var hit_ground_timer = Timer.new()
    hit_ground_timer.set_wait_time(0.6)
    hit_ground_timer.connect("timeout", self, "_hit_ground", [hit_ground_timer, projectile])
    hit_ground_timer.start()
    add_child(hit_ground_timer)

func _hit_ground(timer, projectile):
    timer.queue_free()

**Comment by cbscribe** [comment]
The tutorial doesn't mention adding it as a child node because it doesn't suggest instancing it via code either, any more than with the Button example. At this stage of the tutorial, users are mainly using the editor to add nodes.

Typically if an object needs a Timer node that needs to be used more than once, it's better to add it to the scene. If you need a one-off timer, it's much more efficient to use `SceneTree.create_timer()` rather than go through the steps of instancing -> configuring -> adding -> starting -> freeing.

**Comment by mitchcurtis** [comment]
Makes sense, but the part about Timer reference docs having no examples still applies.
