### ISSUE TITLE
get_root method is not documented on SceneTree

### ISSUE THREAD

**Issue by pgoral** [godotengine/godot-docs#2425]
In many tutorials and docs one can find get_tree().get_root(). But get_tree() return SceneTree and SceneTree (or any base class) does't have get_root method documented

**Comment by LikeLakers2** [comment]
It actually is documented -- it's just not documented as a function anymore, since 3.x versions of the engine. Instead, it's now documented as [a property, `root`](https://docs.godotengine.org/en/3.1/classes/class_scenetree.html#class-scenetree-property-root).

In general, if something is named `get_X()` or `set_X()` and you can't find those specific function names, try searching for `X` instead. (i.e. for `set_multiplayer()` and `get_multiplayer()`, you would look for the `multiplayer` property)

**Comment by pgoral** [comment]
Ok, thanks for clarifying that 👍
