### ISSUE TITLE
Update Panel object's documentation

### ISSUE THREAD

**Issue by Galaxy613** [godotengine/godot-docs#2426]
The current documentation is spartan: https://docs.godotengine.org/en/3.1/classes/class_panel.html

And other people have had my same question and have gone unanswered: https://www.reddit.com/r/godot/comments/8t4x1w/panel_custom_styles/

TheDuriel said on Discord when I asked there:
> Panel
> PanelFocus
> PanelInc
> (inc does nothing)

Should be a quick addition?

**Comment by bojidar-bg** [comment]
Suprise, suprise. Here is the code for Panel:
https://github.com/godotengine/godot/blob/46b6fb83efc8e021cf60502d1e42fdd912b020eb/scene/gui/panel.cpp#L34-L50
It doesn't even mention `panelf` and `panelnc`.
The only reason the two surplus styles show up in the documentation (and elsewhere) is because they are included in the default theme, ever since the open-sourcing of Godot:
https://github.com/godotengine/godot/blob/b2f6beb888d17b2a01779bba203067c0aba548c4/scene/resources/default_theme/default_theme.cpp#L841-L842

@akien-mga can this issue be moved over to the main repo? (bug, core, junior job)

**Comment by Galaxy613** [comment]
Ahhh, well this is definitely not a priority issue - I found PanelContainer and it does what I wanted even better - but it should be fixed eventually.
