### ISSUE TITLE
Update documentation regarding building godot for android

### ISSUE THREAD

**Issue by creikey** [godotengine/godot-docs#2599]
A per this issue and its comments on the godot repository: https://github.com/godotengine/godot/issues/28736
The documentation on how to build the android version of godot here: https://godot.readthedocs.io/en/stable/development/compiling/compiling_for_android.html is wildly incorrect, making it an order of magnitude more difficult to build for android. I still haven't figured out the correct way to do it. The documentation needs to be up to date at least before the 3.2 release

**Comment by neikeq** [comment]
I don't have the time to update the docs but if any one is interested, here is some information.

For the new custom builds system, as explained [here](https://github.com/godotengine/godot/issues/28736#issuecomment-492828654), you need to zip all the files and directories in `godot/platform/android/java/` -except the `build` folder- into `android_source.zip`. This folder must be placed in the templates directory, which is where the Godot editor will look for it when running `Install Android Build Template`.

For classic prebuilt apks the gradle commands are still the same, but the resulting apks are no longer copied to the output `#bin` directory as `android_debug.apk` and `android_release.apk`, unlike what the current documentation states. Instead, you can find them at `platform/android/java/build/outputs/apk/debug/java-debug-unsigned.apk` and `platform/android/java/build/outputs/apk/release/java-release-unsigned.apk`. I haven't tried this, but copying them to the templates directory with the names `android_debug.apk` and `android_release.apk` should be all that's needed.

It wouldn't hurt to have a python script in `platform/android` to take care of all this automatically...

**Comment by Coleim** [comment]
Hello,

I have a question regarding this new Android Build template.

[Here](https://github.com/godotengine/godot/blob/master/platform/android/java/build.gradle#L102) we saw that it has been commented, so I though both apk where not needed.

However, in the [3.2 export template](https://downloads.tuxfamily.org/godotengine/3.2/dev.00aabec8b/Godot_v3.2.dev.00aabec8b_export_templates.tpz), it's still present, and if we remove it the editor complains.
![image](https://user-images.githubusercontent.com/430679/65231651-275d7600-dad0-11e9-9843-09598304026b.png)

Maybe it should still be there ?

Thanks
Clement

**Comment by neikeq** [comment]
@Coleim We still support the old system of pre-compiled apks. In fact it's still the default, which is why it complains if you remove the export templates apks.

In order to use the new system, first you need to need to install the build template into your project with this option:

![img1](https://godotengine.org/storage/app/uploads/public/5cc/0d8/411/5cc0d8411779b991254760.png)

Then select _"Custom build"_ in the export options:

![img2](https://godotengine.org/storage/app/uploads/public/5cc/0d9/126/5cc0d9126190b091610560.png)

This process is described here: https://godotengine.org/article/godot-3-2-will-get-new-android-plugin-system

This issue ticket is about how to build the templates themselves. As a user you don't have to worry about that unless you're building the engine from source.

**Comment by Coleim** [comment]
Yep, I just discovered the new way to do by looking at the doc repo.
I am trying to build directly an android plugin now :)

Thanks for the precision.

**Comment by Calinou** [comment]
The Android export pages have received many updates over the years, so this issue is likely not relevant in its current state. Please open separate issues if you still encounter issues with the documentation.
