### ISSUE TITLE
Add "Shadow to Opacity" to Spatial Shader reference

### ISSUE THREAD

**Issue by clayjohn** [godotengine/godot-docs#2606]
https://github.com/godotengine/godot/pull/29031 Adds a new render mode, ``shadow_to_opacity``, and a new built-in, ``ALPHA``, to the light processor function. Both should be added to the [Spatial Shader doc](http://docs.godotengine.org/en/latest/tutorials/shading/shading_reference/spatial_shader.html)

_edit:_ Oh, and https://github.com/godotengine/godot/pull/24487 added ``UV`` and ``UV2`` to the the light processor function as well. So those two built-ins should be added.

**Comment by vortexofdoom** [comment]
Working on this now. Am I understanding correctly from godotengine/godot#24487 that the light's `UV` and `UV2` built-ins are passed from the vertex data if not modified like the fragment function? Will update that if so.

For godotengine/godot#29031 I'm unsure if the new `ALPHA` built in has functionality outside of the new render mode that should be documented.

Also, looking at the commits for these I noticed that some of the built-in entries are not in the same place in the documentation as in their code counterparts, since these are pretty much directly ported tables, should that be changed as well? It has no direct effect except in this exact kind of scenario.

Other than that this is ready for a pull request that fixes both issues.

**Comment by clayjohn** [comment]
>  light's UV and UV2 built-ins are passed from the vertex data

UV and UV2 cannot be modified in the fragment function currently. That is likely functionality that can be added later.

> I'm unsure if the new ALPHA built in has functionality outside of the new render mode that should be documented.

They are two different things but can be used together. ``ALPHA`` just lets you write to ``ALPHA`` in the light shader. The description should be more or less the same as for the fragment shader. 

> Also, looking at the commits for these I noticed that some of the built-in entries are not in the same place in the documentation as in their code counterparts, since these are pretty much directly ported tables, should that be changed as well?

It doesn't need to be the same as the code but it should be updated to have a logical order as per https://github.com/godotengine/godot-docs/issues/2605
