### ISSUE TITLE
Texture.get_data() should say returns copied/duplicated Image.

### ISSUE THREAD

**Issue by keenfoong** [godotengine/godot-docs#2609]
Texture.get_data() should say returns a duplicated `Image`. I was assuming get_data() was returning a reference to `Image`. 

I was wondering why Texture.get_data().resize() didnt resize the original image, and why there was a small performance hit.

**Comment by HaSa1002** [comment]
I'm a bit unsure about that. Since Image is a different DataType I personally wouldn't have tried to resize the underlying Image that way (I'd done this previously with the image file or, assuming you use a sprite, in the sprite), but your attempt shows that a description of the method(s) would be neat.
