### ISSUE TITLE
atan2 arguments inverted ?

### ISSUE THREAD

**Issue by Trois-as** [godotengine/godot-docs#263]
Hi,

I recently use atan2 function (with godot 2.01), and it is documented like this:

float atan2( float x, float y ) 

As the ATAN2 of libre office Calc or MS Excel. But when I use it, I get the correct 
result with:

float atan2( float y, float x ) like in C/C++.

So I propose this correction:

float atan2( float y, float x )
Arc-tangent that takes a 2D vector as argument, returns the full -pi to +pi range.
To get the angle corresponding to the vector (x, y) use atan2(y, x).

I hope I don't mistaken the actual documentation. Sorry if my english is not clear,
it's not my native language.

**Comment by bojidar-bg** [comment]
See also https://github.com/godotengine/godot/issues/2241

**Comment by Trois-as** [comment]
Hi,

Thanks for your reply, the link you post may be the explanation of the inversion in the doc.
Do you have the same behavior than me when you atan2() ?

**Comment by StraToN** [comment]
Actually the parameters of the atan2(x,y) function are indeed inverted compared to the standard atan2() function (from math.h for example), but this is on purpose. As explained in ``Vector2.angle()`` function doc (http://docs.godotengine.org/en/stable/classes/class_vector2.html?highlight=atan2#class-vector2-angle)

> Returns the result of atan2 when called with the Vector’s x and y as parameters (Math::atan2(x,y)).
>
> Be aware that it therefore returns an angle oriented clockwise with regard to the (0, 1) unit vector, and not an angle oriented counter-clockwise with regard to the (1, 0) unit vector (which would be the typical trigonometric representation of the angle when calling Math::atan2(y,x)).

The reason invoked by @reduz is that this usage could be easier to understand for beginners and not-so-experimented-in-maths users. That is, the clock analogy is used here instead of the trigonometric circle, so more precisely Godot's atan2() and angle() work clockwise, while standard function works anti-clockwise.

I guess we can close this one, as this behaviour shall not change for a moment, so we don't break compatibility for old projects.
