### ISSUE TITLE
Examples that instanciate objects in the update loop, is it a good habit to teach?

### ISSUE THREAD

**Issue by Nodragem** [godotengine/godot-docs#270]
Hello,

I am not sure of what I am saying, because maybe Godot optimizes the code behind the scene, but it seems to me that some code example in the documentation are teaching bad habits to the new users.

For instance:

```
extends Control

var tapped=false

func _draw():

    var r = Rect2( Vector2(), get_size() )
    if (tapped):
        draw_rect(r, Color(1,0,0) )
    else:
        draw_rect(r, Color(0,0,1) )

func _input_event(ev):

    if (ev.type==InputEvent.MOUSE_BUTTON and ev.pressed):
        tapped=true
        update()
```

It seems to me that the r variable should be created in outside the drawing function, that, I believe, is called at every frame!

So that:

```
extends Control
var tapped = false
var r = Rect2(Vector2(), Vector2())

func _ready():
    r.size = get_size()
    # Called every time the node is added to the scene.
    # Initialization here
    pass

func _draw():   
    if (tapped):
        draw_rect(r, Color(1,0,0))
    else:
        draw_rect(r, Color(0, 0, 1))

func _input_event(ev):
    if (ev.type==InputEvent.MOUSE_BUTTON and ev.pressed):
        tapped=true
        update()
```

**Comment by vnen** [comment]
`_draw()` is not called every frame, only when the node is updated. In this example, it'll be called only when a mouse click happens.

Also, your optimization assumes that the control size remains the same throughout the game, which might not always be the case. It's also a little harsher to understand what's going on (would improve a lot if `r` was defined on `_ready()` instead of just setting the size, likely better to make use of `onready` keyword).

Instantiation, especially of builtin types, is not that costly AFAIK.

**Comment by Nodragem** [comment]
ha, ok! I was just wondering, cause I also saw that in the pong tutorial, some Rect2 are created at each frame (in _process(delta)):
```
var left_rect = Rect2( get_node("left").get_pos() - pad_size/2, pad_size )
var right_rect = Rect2( get_node("right").get_pos() - pad_size/2, pad_size )
```

I thought that instantiation was costly :/ I was convinced that I needed to avoid it when using libGDX. 
I think that instantiation cost is maybe a myth coming from the early year of java... or maybe that was because libGDX tried to avoid to many Garbage Collection.

No idea, but happy to know that in Godot, I can instantiate without worrying.

**Comment by bojidar-bg** [comment]
@Nodragem built-in types like `Rect`, `Vector3`, `Dictionary` are not slow to instantiate at all (and that's why all except `Array` and `Dictionary` are passed by-value, not by-reference). This was done specifically for speed, so don't worry about it.

Finally, __never__ overoptimise. If you need to optimise, make game logic with C++. If you still have to optimise, change core code that's slow. If its still slow, drop SceneTree/Node classes. If still slow, go buy another CPU :laughing:.

**Comment by akien-mga** [comment]
Well I agree about not overoptimising, still, the docs should show the best practices. :)

**Comment by NathanLovato** [comment]
We should drop this article for 3.0 - the first part of the [new UI guide](https://github.com/GDquest/godot-3-guides/blob/master/design-user-interface/design-interfaces-with-the-control-nodes.md) already covers a bit more ground, comes with a [demo](https://github.com/GDquest/godot-3-guides/tree/master/demos/Responsive%20UI%20Design). The step by step code tut will follow, with a more practical example.

**Comment by Nodragem** [comment]
You are doing an amazing job, Nathan :) can't wait to see the new documentation.
