### ISSUE TITLE
Update VR starter tutorial for Godot 3.1

### ISSUE THREAD

**Issue by aaronfranke** [godotengine/godot-docs#2727]
https://docs.godotengine.org/en/latest/tutorials/vr/vr_starter_tutorial.html

The tutorial and demo project should be updated for Godot 3.1. I notice some problems running it in 3.0. When I try to run the demo project, I get this error in the debugger:

```
E 0:00:02:0992   Condition ' p_tracker_id == 0 ' is true. returned: __null
  <C Source>     servers/arvr_server.cpp:305 @ find_by_type_and_id()
```

Sometimes I get random crashes with the below error, with no other info printed. Sometimes it crashes immediately, sometimes if I leave my headset on the floor then it runs fine but then it crashes immediately when I put on my VR headset (note: it says Unix but I'm on Windows w/ a Vive).

```
ERROR: _get_socket_error: Socket error: 10054
   At: drivers/unix/net_socket_posix.cpp:190
```

Also, trying to open `addons/godot-openvr/scenes/ovr_first_person.tscn` fails because it's looking for a file in `addons/vr-common` which does not exist in the demo project.

Also, instead of a ZIP file, perhaps the demo project should be in [the demo projects repo](https://github.com/godotengine/godot-demo-projects).

Pinging @TwistedTwigleg and @BastiaanOlij

**Comment by TwistedTwigleg** [comment]
The error messages and the random crashes are probably due to changes to the VR/AR implementation since Godot 3.0 to Godot 3.1. Using the OpenVR addon for Godot 3.1 probably will fix most of the issues.

Other than that, I *think* most everything should still be compatible with Godot 3.1, though I have not looked through the VR tutorial recently so I'm mainly just guessing from what I remember.

_____

As for moving the finished project to the demo repository, I think it is fine either way. Whatever the documentation team wants to do is cool with me. The sky panorama might need to be changed due to its license, but everything else should be compatible.
If the sky panorama needs to be changed, there are some nice HDRI maps on [HDRI haven](https://hdrihaven.com/) that are licensed under CC0 that might serve as a nice replacement.

**Comment by BastiaanOlij** [comment]
I'm all for having the project hosted on Github and will gladly put it on GodotVR if you're ok with that @TwistedTwigleg, I can give you full rights to the repo.

I think it would be worth our while to go through the project one more time and make sure it's updated for Godot 3.1 with the latest plugins. Loads of improvements have been made

**Comment by TwistedTwigleg** [comment]
> I'm all for having the project hosted on Github and will gladly put it on GodotVR if you're ok with that @TwistedTwigleg, I can give you full rights to the repo.

I'm totally cool with the project being hosted on GitHub and/or on GodotVR. You have my full permission to do whatever you see fit with the project.

( As far as rights to the repository goes, I'm fine either way. I do not know how much help I'll be able to provide outside of working in Godot. My C++ skills are a tad rusty... )

> I think it would be worth our while to go through the project one more time and make sure it's updated for Godot 3.1 with the latest plugins. Loads of improvements have been made

Agreed. I'll try to give the project a pass soon, ideally sometime later today, and start to help fix things up for Godot 3.1. Once the project is fixed up and ready to go, I'll make a PR to update the tutorial with the changes if needed.

Should the project should be migrated to GLES2 for better performance? I think only the Particles and WorldEnvironment Nodes might need changes if the project goes from GLES3 to GLES2.

______

Kinda off-topic, but ideally I'd like to redo some parts of the project and tutorial in the future once I have the time.
Things like updating the visuals, making an extendable class for the weapons/objects, and other minor tweaks to help improve the overall quality of the project.

Updating the visuals and refactoring the code should be fairly minor and easy to integrate into the tutorial so long as nothing too major was changed. I don't know how much time I can dedicate to it, but if there is interest then I can see about polishing things up a bit.

**Comment by TwistedTwigleg** [comment]
I've done some minor improvements and changes so the finished project works with Godot 3.1. The main changes were undoing some of the Viewport rotation stuff so it renders correctly and some minor changes to the code because of function/property name changes.
I have not tested the project actually in VR yet, but I plan to give it a run this weekend.

I tried converting the project to GLES2 and it didn't seem to have any issues. I decided to switch it back to GLES3, at least for now, because post-processing like Bloom isn't implemented in GLES2. Depending on how hard it is, I might try to write a really simple Bloom shader in Godot's shader language so the project can use GLES2 without any visual quality loss.

Assuming everything works in VR, should I make a PR with the changes here or should I make a PR on the GodotVR repository?
I will also make a PR to update the written tutorial with the (minor) changes, so everything is still in sync.

**Comment by TwistedTwigleg** [comment]
I tested the project and everything is working now. There are a few minor issues in the Godot debugger due to using Godot generated collision shapes, seems to be an issue with the quick_hull.h file, but it is nothing that prevents the project from running.

All that is left is just updating the starter project and touching up the tutorial. 👍

**Comment by BastiaanOlij** [comment]
@TwistedTwigleg send me an email on mux213 at gmail, I'll get a repo setup for your on GodotVR and you can push it in there
