### ISSUE TITLE
PopupMenu's set_item_accelerator methods description is confusingly unhelpful.

### ISSUE THREAD

**Issue by Megalomaniak** [godotengine/godot-docs#2760]
As per https://godotforums.org/discussion/21202/what-is-an-accelerator-for-the-popupmenu-node

> https://docs.godotengine.org/en/3.1/classes/class_popupmenu.html#class-popupmenu-method-set-item-accelerator
> - void set_item_accelerator ( int idx, int accel )
> 
> Set the accelerator of the item at index “idx”. Accelerators are special combinations of keys that activate the item, no matter which control is focused.

Does not sufficiently explain how an accelerator is supposed to be used or for that matter how it works.

**Comment by goblinJoel** [comment]
I ran into this today in Godot 3.5.1 while looking for a way to have clicking a button (for a spell in an RPG) trigger another menu to further specify the selection (what level to cast the spell at). I saw all the accelerator params, but the instructions are, "See [get_item_accelerator](https://docs.godotengine.org/en/stable/classes/class_popupmenu.html#class-popupmenu-method-get-item-accelerator) for more info on accelerators." That method has the same vague text quoted by Megalomaniak.

It tells us what an accelerator is for but not how to make one. How do I decide what `int` to pass for `accel`? I only found out from Googling [old forum posts](https://godotengine.org/qa/51896/what-is-an-accelerator-for-the-popupmenu-node).

**Comment by Calinou** [comment]
Note that even once this is documented, you may run into https://github.com/godotengine/godot/issues/40836 unless that issue was fixed a while ago.

**Comment by goblinJoel** [comment]
Thanks for adding an explanation to the docs! Based on what you wrote there:
> Sets the accelerator of the item at the given [param index]. An accelerator is a keyboard shortcut that can be pressed to trigger the menu button even if it's not currently open. [param accel] is generally a combination of [enum KeyModifierMask]s and [enum Key]s using boolean OR such as [code]KEY_MASK_CTRL | KEY_A[/code] ([kbd]Ctrl + A[/kbd]).

That issue is still on 3.5.1 using the test project provided. Pressing A never does anything, whether the item is visible or not. Clicking works.

The quote above indicates it should work even without opening the menu. Am I misunderstanding that? It _does_ do that if I replace the PopupMenu with a MenuButton and connect the pressed signal in code with `get_popup().connect("id_pressed", self, "_on_PopupMenu_id_pressed")`. As long as the MenuButton is visible, pressing A will trip the `id_pressed` signal, whether I've opened the menu or not. It just doesn't work if you use a PopupMenu node directly.

It's pretty weird that there's no way I can see to use the editor to connect to a MenuButton's PopupMenu's signals. The editor does let you add items to that menu, but you can't set accelerators or shortcuts that way, or the signal you need for it to do anything. Technically separate issues, I guess.
