### ISSUE TITLE
Add an article on how to upload addon code to GitHub.

### ISSUE THREAD

**Issue by willnationsdev** [godotengine/godot-docs#2814]
Many beginner users are not familiar with how to get involved with the online ecosystem of making plugins. As such, I recommend we add a tutorial on how to...

1. Install git.
1. Create a GitHub account.
1. Create a repository on GitHub.
1. Clone their repository through git.
1. Add code to their repository.
1. Push their changes to GitHub.
1. Create an account on the Asset Library.
1. Submit their addon repository to the Asset Library.

**Comment by skyace65** [comment]
This really doesn't seem necessary for Godot's documentation. There's already plenty of online resources for how to use github, making a tutorial for Godot's docs seems like a waste of time. And there's already a page on how to submit your addon to the asset library(Though the submission guidelines still need to be made).

**Comment by willnationsdev** [comment]
@skyace65 I can't tell you the number of times I've come across people who don't know where to begin when publishing their code as an addon. The fact that the individual steps are not very complicated or that they are well documented elsewhere is irrelevant. The steps, together, need to be presented as a group to users so that they know where to begin and what steps to take.

We don't necessarily need to re-iterate all of the instructions that are documented elsewhere. For example, when creating a GitHub account, it's pretty cut-and-dry. You just need an email address. And the process for doing so [documented here](https://help.github.com/en/articles/signing-up-for-a-new-github-account). We can just direct people there and then send them along the next step of the process when they get back.

But if we *don't* give people a starting place and help them connect the dots, then they frequently don't know what to do.

**Comment by Vennnot** [comment]
I agree with steps 7. and 8. I don't feel Godot documentation should seek to concatenate so much information that already exists out there to have it "in one place". This can easily get out of hand with other topics if it's the road we choose to go down. Additionally the steps you outlined don't include other important points like releases, forks, pr's, external contributors, etc. I would recommend users learn this from better and more senior resources and apply that same knowledge here.

**Comment by tetrapod00** [comment]
Yeah, this isn't in scope for the official docs. 

Since this issue was made, there is more of a clear policy of only documenting *Godot* and not general programming topics. So while we do document the process of [submitting to the asset library](https://docs.godotengine.org/en/stable/community/asset_library/submitting_to_assetlib.html), and we also have a bit of [documentation on git usage](https://docs.godotengine.org/en/stable/contributing/workflow/pr_workflow.html) in the context of making changes to the engine, I don't think we should add another page about how to use GitHub in the context of making plugins. It's redundant.
