### ISSUE TITLE
Document how to use VCS (Version Control System e.g. git) editor functionality

### ISSUE THREAD

**Issue by follower** [godotengine/godot-docs#2838]
AFAICT the new Version Control functionality available via `Project > Version Control > Set Up Version Control` does not have any documentation on how to set it up.

Out of the box 3.2.alpha1 only displays an error dialog with this message:

    No VCS addons are available.

At a minimum it would be good if the Changelog/Release Notes mentioned that it won't work out of the box. (And that the functionality requires a per-OS compiled addon.)

Related links:

 * https://github.com/godotengine/godot-git-plugin
 * https://github.com/godotengine/godot-git-plugin/releases
 * https://github.com/godotengine/godot/issues/32135 (and https://github.com/godotengine/godot/commit/6df03fe61f8b25f932e0666cfd873e563e8cf1ed)
 * https://github.com/godotengine/godot/blob/ddc42be1dbb66e8ae7e7e13deace0c59fea91abd/editor/plugins/version_control_editor_plugin.cpp#L101
 * https://github.com/godotengine/godot/pull/31461
 * https://gist.github.com/IronicallySerious/1ac3e3ae4a51e6f739c31dd7c46f2566

**Comment by IronicallySerious** [comment]
I agree that there needs to be either documentation present in the editor or a link should be provided. 

@follower How about using we convert [the documentation present here](https://godotengine.org/article/gsoc-2019-progress-report-3#vcs-integration) to one of the tutorial pages and link it in the dialog box for selecting a VCS.

**Comment by Calinou** [comment]
If we were to link it in the dialog box, we'd probably have to roll a custom one so we can use BBcode to add a link in the error message. Alternatively, we can make the dialog displayed by `show_warning()` use a RichTextLabel instead of a Label, but that's a larger change that will require more testing.

**Comment by mellogrand** [comment]
Git integration is essential for serious work and I suggest closing this issue when possible.
Frankly, after all the work done sofar I find a bit surprising that we should rebuild the plugin for every Gotod Project just because of directory paths. Moreover, for a normal user the build process with SCons etc. is quite unusual. 
I could not find any binaries as s stated in #31461 :Currently the GDNative plugin is available at https://github.com/IronicallySerious/godot-git-plugin. And it requires the user to build the plugin themselves. **### A release will be made soon that provides binaries for all platforms.**

**Comment by IronicallySerious** [comment]
@mellogrand The binaries are available in the [release section](https://github.com/godotengine/godot-git-plugin/releases).

**Comment by IronicallySerious** [comment]
Could you link the source that says 'A release will be made soon that provides binaries for all platforms.'? We can remove that now if it gathering much attention

**Comment by follower** [comment]
Based on the discussions in https://github.com/godotengine/godot-git-plugin/issues/16 the current plan is to keep the plugin docs in the wiki there for now and add a link from the official Godot docs.

Adding a version control page/section to one of these seems like the best option:

 * Editor Manual
 * Project Workflow > Project setup
 * Project Workflow > Best practices
 * New tutorial page?

Any preferences/alternate suggestions?

**Comment by IronicallySerious** [comment]
> Project Workflow > Project setup
This seems to be the best suited out of them. It would just be a small tip that points to the wiki of this repo.

**Comment by cgeadas** [comment]
Is there any progress for a macOS port of this plugin?
The compilation way is way out my league. I've looked at the source and the script stoped, complaining for the lack of cmake, and it tried to compile for x11...

**Comment by IronicallySerious** [comment]
You can track the MacOS port here
https://github.com/godotengine/godot-git-plugin/issues/12

I admit that it has has been quite a while

**Comment by cgeadas** [comment]
Thank you for your answer. I've deleted my comment because right after posting it, I've found the thread you mention.
Meanwhile I've downloaded the source and tried to compile it. Even after installing cmake and tweaking the x11 build script a little I get an error related to a missing Godot.hpp header file. Lost some hours with it but, since git is something I would like to use for my current project but never used before, I'll just stick with the basic "one folder per version" approach until there is port.
