### ISSUE TITLE
problemas driver video intel 3000

### ISSUE THREAD

**Issue by jhamil1222** [godotengine/godot-docs#2873]

**Comment by jhamil1222** [comment]
he notado problemas con el sistema windows sea 7 8 o 10 de 32 bits que tienen un ligero problema con los drivers de los intel de segunda genracion la cosa es que no te deja usar godot de 32 bits con open gl 3.0 pero probe en mi pc con ubuntu de 64 bits y el broblema desaparecio  no note ningun problema con este sistema con godot mas bien una mejora del rendimiento para el pc

**Comment by jhamil1222** [comment]
mi solucion si tienen este problema es migrar a ubuntu de 64 bits con el problema de drivers que molesta  mucho windows es caro y no te brinda un buen soporte :v
nota: no probe windows 64 ya sea 7,8,10 ya que es comprar un licencia para ello pero mi consejo es votar por lo libre

**Comment by jhamil1222** [comment]
el problema biene en el driver que biene de intel para usar en 32 bits 
:v

**Comment by clayjohn** [comment]
I can see that you have put some thought into this. But bug reports must be in English. And they really should follow the template if at all possible. 

In it's current state this issue is not helpful for other contributors, which is the purpose of bug reports. If you want to still open a bug report feel free, but please do so in a way that communicates effectively for other users. :)
