### ISSUE TITLE
GDScript array operator is missing documentation

### ISSUE THREAD

**Issue by aaronfranke** [godotengine/godot-docs#2952]
I noticed that there's no documentation for the array operator on structures. For example:

	var v = Vector2(1, 2)
	print(v[0])
	print(v[Vector2.AXIS_X]) # Alternatively, using enum

This is needed for [Vector2](https://docs.godotengine.org/en/latest/classes/class_vector2.html), Vector3, Color, Basis, Transform, and Transform2D structures. Particularly it would be useful for the latter three, since the order is column-row (in `t[0][0]`, really `t[0]` is accessing the column vector, then the rest is accessing that vector's components).

Furthermore, it doesn't seem that things like [Array](https://docs.godotengine.org/en/latest/classes/class_array.html) or the PoolTypeArrays have documentation for this either, except that Array does have a section with example usage.

**Comment by jynus** [comment]
Array operator [] seems to be documented on latest now: Array: https://docs.godotengine.org/en/latest/classes/class_array.html#class-array-operator-idx-void Vector2: https://docs.godotengine.org/en/latest/classes/class_vector2.html#class-vector2-operator-idx-float etc Probably fixed with the above patch + https://github.com/godotengine/godot/pull/43419 (and related).

Like godotengine/godot-docs#4315, it may need a backport + doc regeneration, though.
