### ISSUE TITLE
Legacy API

### ISSUE THREAD

**Issue by CyberFoxHax** [godotengine/godot-docs#3004]
So watching a video on YouTube. He uses set_pos(Vector2). I search Godot official documentation for "set_pos". No results.
I ask in Discord. Wait an hour. Function is deprecated, i should use "translation = Vector2"

Newcomers like me have no idea when a function is considered legacy or not. All we can do it look it up. I would prefer that the official documentation would show results for deprecated API's. Put a warning in the top of the page and optionally link us to the new API that replaced it.

**Comment by Calinou** [comment]
I think this could be solved by adding an alias system to the editor help. I proposed this in https://github.com/godotengine/godot/issues/29286#issuecomment-497135808, but the original issue was closed.

**Comment by NathanLovato** [comment]
This function isn't just deprecated, it doesn't exist in Godot 3.0 and up.
It's the old API from Godot 2, and it is documented in the Godot 2 documentation: http://docs.godotengine.org/en/2.1/

In a sense, what you encountered is already documented in Godot. If you write `set_pos` in Godot 3.1, you will get an error telling you the function does not exist.

In this case, to me, a solution to the problem would be having a migration guide in the documention that would list all the breaking changes between major releases. There was a big one between Godot 2 and Godot 3: the API used to rely on setter and getter functions, while in Godot 3 it relies on properties (still with optional set/get methods).

While adding extra metadata to the class reference would certainly enhance the experience while doing searches, it would also take quite a bit of work to set up, as you'd have to add the metadata to the source XML files.

Then, I think that tags or aliases may not solve this specific issue unless the docs would explicitly tell the user that the function they're looking for does not exist anymore. Searching for `set_pos (function)` and finding `position (property)`.

By the way, your issue has been partly addressed in recent versions of Godot: the version number is now displayed in the editor, so that when you watch a video, you can see if it was recorded in an old version of the engine.

**Comment by CyberFoxHax** [comment]
ok, thanks regardless.
