### ISSUE TITLE
Add a comprehensive overview of JoyPad mappings for popular devices

### ISSUE THREAD

**Issue by willnationsdev** [godotengine/godot-docs#3031]
I just saw [this reddit post](https://www.reddit.com/r/godot/comments/ej6tpq/i_did_some_research_on_gamepad_behaviour_that_id/) and it occurred to me that documenting this information in a more permanent, findable place would be a good idea.

Specifically, adding a page to the docs that refers to *particular*, popular controller devices and what users can expect the JoyPad button IDs to map to on those controllers.

What do you all think?

**Comment by vnen** [comment]
AFAIK all the mappings come from https://github.com/gabomdq/SDL_GameControllerDB, so maybe this could be contributed upstream (if they don't have it already).

**Comment by insomniacUNDERSCORElemon** [comment]
@vnen Also as I noted in the linked thread, there is SIAPI (Steam Input API) which has support for detecting what controller layout you have (like Xbox, PS4, Switch, etc) and assigning the correct in-game glyphs for that (including for what the player has mapped). Either Steam-made glyphs OR custom art.

See info here: https://partner.steamgames.com/doc/features/steam_controller/steam_input_gamepad_emulation_bestpractices (not the emulation stuff, but that's the most in-depth descriptions of the glyph stuff I could find... also some links still go to pages listed as depreciated)

Though SIAPI support in general is a good idea, as it allows games to provide actions to map keys to (rather than just mapping to Xbox or KB/M controls) and provides action layers... both of those allow for easier mapping (particularly without needing to know the default mappings) and greater control (because actions should no longer be hardcoded, and so you can tweak things further).

Although SIAPI and even likely detecting controller mappings is probably not really a documentation-specific issue... though I suppose maybe if SIAPI is ever added (even in the asset library) then maybe if would be relevant to recommend using it (instructions really only if it was added directly).

**Comment by skyace65** [comment]
This doesn't seem necessary in the docs since the input map tells you which button is which on PS, Xbox and Nintendo controllers.

**Comment by vnen** [comment]
I feel this is issue is not really the point of the reddit thread. As @skyace65 mentioned, you can already see the actual controller button on the input map window.

The main issue is that you may want to use more semantic buttons on different controllers, like using A on Xbox to confirm but also use A on a Nintendo Pro controller even though those map to different button ids (since they are in different physical locations on the controllers).

**Comment by insomniacUNDERSCORElemon** [comment]
@vnen Yes what I'm saying is not directly related, but a comprehensive list of gamepad hardware is something that SIAPI has already done (you might even be able to get said list and just use that). Past that they're just similar problems and probably could be their own issues but I'm just a lurker.

A big point of mine is that if a developer designs their game and UI for one controller even if the buttons are properly detected (A is A) the button glyphs can hinder player experience if the color mismatches what's on their controller.

Documentation aside, there are likely a few ways of going about some of the functionality I mentioned. Getting SIAPI working for Godot is probably possible (it seems to support C++). If not, glyph colors could probably be re-colored dynamically and be driven by custom profiles (depending on the developer adding them, or allowing users custom colors/profiles). Action layers (normal, vehicles, menus, minigames) likely could be done just via meticulous prefix naming (and never reusing the same action in different contexts) and your mapper detecting each prefix as a sets of controls (but a controller visual like Steam offers is probably not viable for most people/projects). Though custom solutions to fix small things like this are probably things people don't want to spend any time on, particularly for small projects.

There might still be room in documentation for "best practices"(/advanced guidance) but I fully expect something like that will only come about organically after it has been done dozens of times in big-ish projects and maybe when there are existing resources (tutorials, templates, plugins etc) that can be pointed to.

-----

Also the button options (at least via the 3.X input map) are rather limited, for instance I'm not sure if the Steam Controller itself can have stuff like the grip buttons. I mean I'm sure it's *possible* via code (with button detection especially) but that seems clunky that the input map can't do it. 

It'd also make things easier (particularly if you want different button usage on different controllers) if the input map supported different profiles (both for different input types and for different input styles) that could be either detected or selected by the user.

**Comment by Calinou** [comment]
> Getting SIAPI working for Godot is probably possible

As far as I know, SIAPI is a proprietary library. We can't officially integrate it in Godot unless it's installed via third-party means somehow. (That said, nothing prevents someone from writing a C++ module to add support for it.)

**Comment by insomniacUNDERSCORElemon** [comment]
@Calinou Sorry if I didn't make it clear, but yes I was referring to a 3rd-party plugin at least for Godot games on Steam, just as I was talking about how some things could be manually added per-game (albeit with extra work for *correct* functionality).

I agree that controller support is useful outside of Steam, but Steam's configuration is extremely powerful. However a little will go a long way, as I've said it'd be useful if input maps were more powerful. What I suggested w/profiles would not fix the issue of this post directly but would not require developers to manually add a button override via code, rather just a different profile for that controller.

**Comment by Calinou** [comment]
There is now a [dedicated page on controller support in Godot](https://docs.godotengine.org/en/stable/tutorials/inputs/controllers_gamepads_joysticks.html), closing.
