### ISSUE TITLE
issues with the "your first game" tutorial

### ISSUE THREAD

**Issue by justchen1369** [godotengine/godot-docs#3075]
1. There is a discrepancy between filenames between the dodge_assets.zip download and what the tutorial says.
   - > On the left is a list of animations. Click the “default” one and rename it to “right”. Then click the “Add” button to create a second animation named “up”. Drag the two images for each animation, named playerGrey_up[1/2] and playerGrey_walk[1/2], into the “Animation Frames” side of the panel:
   - However, the filenames of the relevant files are as follows:
      `playerGrey_walk1.png`, `playerGrey_walk2.png`, `playerGrey_up1.png`, and `playerGrey_up2.png`.
2. within `func _process(delta)`, `speed` is not used for `velocity` changes. `velocity` is instead set to a value of one pixel, which when run gives the impression that the character is not moving and therefore "broken".
   - Example: `if Input.is_action_pressed("ui_right"): velocity.x += 1`
3. > The boolean assignments in the code above are a common shorthand for programmers. Consider this code versus the shortened boolean assignment above:
   - This example code is not shorter. Perhaps a result of the code in the "longer" code not being updated along with the "shorter" code?

**Comment by Rudigus** [comment]
1. There is no issue with the tutorial, but rather they used a notation that can be misunderstood. By mentioning "playerGrey_up[1/2]" and "playerGrey_walk[1/2]", they used a bracket notation "[]" to indicate the different filenames that only differ by one character, and the bar symbol "/" was used to indicate that you should append "1" to the rest of the filename for one of the files, and "2" to the rest of the filename for the other file. That applies to both cases. The notation makes sense, but I had some trouble to get it too. Perhaps being more verbose, but clearer would be better.

2. I don't understand this issue. Speed is a multiplier and velocity is the rate which the player's position change. At first, velocity focuses on getting the direction of the vector, and after getting that, it is multiplied by speed (the multiplier) in order to it be complete as the velocity we know.

3. "Consider this code versus the shortened boolean assignment above" - According to that phrase, what is compared are the boolean assignments, not all the code.

```
$AnimatedSprite.flip_h = velocity.x < 0
$AnimatedSprite.flip_v = velocity.y > 0
```
is smaller than:
```
if velocity.x < 0:
    $AnimatedSprite.flip_h = true
else:
    $AnimatedSprite.flip_h = false
```
In the end, I think those are understanding issues. But perhaps something could be done to make everything clearer.

**Comment by justchen1369** [comment]
that still leaves the issue of velocity being set to a value of +-1px, which gives the appearance of the character not moving.

**Comment by justchen1369** [comment]
that still leaves the issue of velocity being set to a value of +-1px, which gives the appearance of the character not moving.

**Comment by Nathan-P-B** [comment]
I checked the [3.1](https://docs.godotengine.org/en/3.1/getting_started/step_by_step/your_first_game.html#moving-the-player) and [3.2](https://docs.godotengine.org/en/stable/getting_started/step_by_step/your_first_game.html#moving-the-player) tutorial, and the velocity seems correct. Here is one block of sample code:
```GDScript
func _process(delta):
    var velocity = Vector2()  # The player's movement vector.
    if Input.is_action_pressed("ui_right"):
        velocity.x += 1
    if Input.is_action_pressed("ui_left"):
        velocity.x -= 1
    if Input.is_action_pressed("ui_down"):
        velocity.y += 1
    if Input.is_action_pressed("ui_up"):
        velocity.y -= 1
    if velocity.length() > 0:
        velocity = velocity.normalized() * speed
        $AnimatedSprite.play()
    else:
        $AnimatedSprite.stop()
```
The first part essentially adds all the movement keys together. This is not in any particular unit (such as pixels), and its purpose is to just determine the **direction** to move, but not **how much** to move at this point. Using [``velocity.normalized()``](https://docs.godotengine.org/en/stable/classes/class_vector2.html#class-vector2-method-normalized) returns a unit vector (length of exactly 1) in the appropriate direction. (If this is not done, the player would move faster moving diagonally than straight right, left, down, or up.) This is still not in pixels.
This vector with length exactly one is then multiplied by the player's speed in pixels per second. This determines the player's velocity, which is both in the correct direction and is the correct speed.

The next block of sample code takes care of moving the player by the appropriate amount.
```GDScript
position += velocity * delta
position.x = clamp(position.x, 0, screen_size.x)
position.y = clamp(position.y, 0, screen_size.y)
```
The velocity is then multiplied by the elapsed time since the last frame to determine how many pixels the player should actually be moved this frame. (The [``clamp``](https://docs.godotengine.org/en/stable/classes/class_@gdscript.html#class-gdscript-method-clamp) lines ensure that the player can't move off-screen.)

**Comment by justchen1369** [comment]
That’s true, my bad. I appear to have misread the tutorial :)
Closing now.
