### ISSUE TITLE
Android export: Document size requirements for adaptive icon foreground and background on Android 10+

### ISSUE THREAD

**Issue by bigbic127** [godotengine/godot-docs#3076]
**Godot version:**
   3.2 rc1

**OS/device including version:**
window10 / android

**Issue description:**
I upgraded from beta 5 but the size of the Android Launcher icon is strange. The outline is cut off and enlarged.

![image](https://user-images.githubusercontent.com/26403388/72677719-d5127d00-3ae2-11ea-9d5c-20e1986058be.png)
<3.2 beta5>

![image](https://user-images.githubusercontent.com/26403388/72677722-e2c80280-3ae2-11ea-9839-5a539c404e00.png)
<3.2 rc1>

**Comment by Anutrix** [comment]
But default Godot icon shouldn't stay weird, right? Is something gonna be done about it?

**Comment by Calinou** [comment]
@Anutrix I guess we could tweak the default project icon to account for the Android adaptive icon margins. It will look a bit weird on desktops, though.

**Comment by bigbic127** [comment]
Do you have to create two icons based on 9 version and build separately?

**Comment by MadEqua** [comment]
> BTW, does it keep working as it used to (without adaptive icon support) on both Android <= 9 and Android 10 if one only specifies the main icon, and nothing for the adaptive fg/bg?

The way it's implemented right now will always use adaptive icons when Android supports it (Android 8 Oreo, not 10). Even if one doesn't specify adaptive icons. In that case, the fallback system will kick in.

Perhaps we should have a boolean option to allow people to disable the adaptive icon and let it be just like before, if one has no problem with Android's default "ugly" ones, like many people were having.

Also it's probably a mistake to have the project icon as a fallback for the adaptive foreground, since it will look bad with the default project icon. That's on me :(

> Do you have to create two icons based on 9 version and build separately?
> Like the top picture, the beta5 was fine.
> the device version i tested was the same.

You don't have to build separately, but have to create the adaptive icons to look good on Android >= 8, at least for now. The regular icon will be used on Android < 8.

**Comment by Calinou** [comment]
This was implemented in #3083, closing.

**Comment by anisc** [comment]
Still have the same issue with 3.2.3 
Was this fixed ?

**Comment by Calinou** [comment]
@brainsick This was fixed by adding documentation, but the exporter currently doesn't have complex validation logic to check that your icon sizes at indeed correct.
