### ISSUE TITLE
Centering the text pane in docs.godotengine.org

### ISSUE THREAD

**Issue by regakakobigman** [godotengine/godot-docs#3139]
To make the docs more readable on widescreen monitors, the docs were centered. However, this also includes the sidebar, which means the text itself isn't centered. This makes it harder to read on smaller screens.

![Centered](https://user-images.githubusercontent.com/42157525/73615262-4880b800-45d4-11ea-9988-54ff7d7c071b.png)

It would be easier to read if the text pane was perfectly centered, and the sidebar was directly to the left of it.

**Comment by ericrybick** [comment]
to achieve this, just change `max-width` to `1400px` in `.wy-body-for-nav`. (add the size of the navbar to total width of body)

also add `padding-left: calc(100vw - 100%);` to `:root` to avoid scroll-bar repositioning

**Comment by mhilbrunner** [comment]
>This makes it harder to read on smaller screens.

On which kind of smaller screens?

Note that for most smaller screens, a different layout is already used.
Trying around with with different screen sizes and resolutions, there is only a very small gap between big, high-resolution widescreen displays and the treshold in which the page switches to it's mobile-ish layout.

Even in that gap, I actually prefer having the whole content centered, instead of moved to the left with a larger gap on the right, which looks more unbalanced. - Even if I had to have that pointed out by a design person, as I personally don't care that much :P 

So I'm not sure if this would be an improvement. Maybe you can expand on the problems the current layout causes?

**Comment by mhilbrunner** [comment]
I'm going to close this for now, as the current layouts (desktop + "mobile") work fine with all display sizes, browsers and resolutions I could test.

I think this is more an issue of taste, and difficult to gauge consensus for. I'm open to reopening/discussing this if there appears to be more demand for it; currently, it doesn't look that way to me.

Please ping me to reopen if/once there is more demand or if you can show a case where this is an objective improvement.

Thanks for opening the issue :)
