### ISSUE TITLE
I rebuilt the pdf version.  How can I submit it for consideration?

### ISSUE THREAD

**Issue by meatballcoder** [godotengine/godot-docs#321]
https://godotdevelopers.org/forum/discussion/18124/would-it-be-useful-to-bookmark-the-documentation-pdf#latest

I rebuilt the wiki .pdf so all the bookmarks and images were included.  Not all encoding for all languages worked in LaTeX, but the rest is there.  20MB.  I attached it.
[GodotEngine.zip](https://github.com/godotengine/godot-docs/files/679859/GodotEngine.zip)

**Comment by bojidar-bg** [comment]
I'm not sure if we can do anything about it, as it is generated by ReadTheDocs....

**Comment by meatballcoder** [comment]
I figure I could upload it for whoever wanted it?  Should I just put it in my own GitHub, the pdf only?

**Comment by akien-mga** [comment]
The PDF is auto-generated by Sphinx and Read The Docs, so we can't use a custom one in place of it. But you could dig into the Sphinx documentation and see how to tweak our `conf.py` to achieve what you're looking for. Right now the PDF output is the factory default.

**Comment by meatballcoder** [comment]
That's what I"m saying.  I generated it from Sphinx with make.  Make gave me a choice of outputs.  I chose LaTeX.  After I did that, I generated the PDF.

**Comment by akien-mga** [comment]
IMO a PDF of the docs is useful only if autogenerated (as done currently by Sphinx), so that it gets updated when we modify the documentation. As mentioned above, if the current PDF generated by Sphinx is not good enough, that can likely be improved with the proper settings in `conf.py` and/or the Makefile, but I wouldn't add a manual process of LaTeX -> PDF conversion for this.
