### ISSUE TITLE
FPS Tutorial gun mesh broken

### ISSUE THREAD

**Issue by MeikelLP** [godotengine/godot-docs#3217]
![image](https://user-images.githubusercontent.com/11669846/75609113-3d06ab00-5b06-11ea-972b-19f1290314cf.png)
![image](https://user-images.githubusercontent.com/11669846/75609164-9969ca80-5b06-11ea-80e2-64d2219112b9.png)

Seems like some faces are wrong in the assets ?

using:
Godot Engine v3.2.stable.mono.official - https://godotengine.org
OpenGL ES 3.0 Renderer: GeForce RTX 2080/PCIe/SSE2

**Comment by Calinou** [comment]
cc @TwistedTwigleg

**Comment by TwistedTwigleg** [comment]
I opened up the project and can reproduce the issue with Windows 10, OpenGL 3 renderer.

It looks like it may be a Godot engine bug. The issue seems to be because of the `Depth Draw Mode` being set to `Opaque Pre-Pass` in the material uses for the guns (second material attached to `GodotBattleBot` in `Player.tscn`). Changing the `Depth Draw Mode` to `Opaque Only` fixes the rendering issue, but then the transparent parts of the texture, like the "sights" in the rifle model, will not be transparent.
However, it was working in Godot 3.1 just fine, and the material, textures, and 3D models have not changed since then.

Not sure what the best fix would be. Short term, the best solution is to set the `Depth Draw Made` to `Opaque Only` in the second material in `GodotBattleBot`. That should fix the issue, at the cost of there no longer being any transparency in the 3D gun models.
(I can make this change in #3174, if desired)

**Comment by Calinou** [comment]
Opaque Pre-Pass seems to be broken in 3.2, see https://github.com/godotengine/godot/issues/36669

**Comment by TwistedTwigleg** [comment]
> Opaque Pre-Pass seems to be broken in 3.2, see godotengine/godot#36669.

Seems that is the case. I guess the solution for this bug depends on how the linked issue is handled. If it is intended functionality, then changing `Depth Draw Mode` to `Opaque Only` should be the fix, that or redoing the materials in the 3D models,

**Comment by MeikelLP** [comment]
Thanks. I will wait for a fix :)
