### ISSUE TITLE
'cl' is not recognized as an internal or external command

### ISSUE THREAD

**Issue by GittyGrubHub85** [godotengine/godot-docs#3311]
I'm currently on the Plugin Compile section https://docs.godotengine.org/en/3.2/tutorials/plugins/gdnative/gdnative-cpp-example.html#compiling-the-plugin

Here's the build log:

> E:\GODOT\Godot 3.2\Projects (Own)\GDNative C++ based on Documents\gdnative_cpp_example\godot-cpp>scons platform=windows
scons: Reading SConscript files ...
scons: done reading SConscript files.
scons: Building targets ...
cl /Fosrc\gdexample.obj /c src\gdexample.cpp /TP /nologo -W3 -GR -EHsc -MDd -ZI /DWIN32 /D_WIN32 /D_WINDOWS /D_CRT_SECURE_NO_WARNINGS /D_DEBUG /I. /Igodot-cpp\godot_headers /Igodot-cpp\include /Igodot-cpp\include\core /Igodot-cpp\include\gen /Isrc
'cl' is not recognized as an internal or external command,
operable program or batch file.
scons: *** [src\gdexample.obj] Error 1
scons: building terminated because of errors.

I'm getting an error of cl what is cl I don't know the name of this command.

**Comment by akien-mga** [comment]
`cl` is `cl.exe`, the Visual Studio C++ compiler. Did you install Visual Studio?

**Comment by GittyGrubHub85** [comment]
> `cl` is `cl.exe`, the Visual Studio C++ compiler. Did you install Visual Studio?

I use Visual Studio Code

**Comment by Calinou** [comment]
@GittyGrubHub85 Visual Studio Code doesn't include the C/C++ compilers. You need to install [Visual Studio Community](https://visualstudio.microsoft.com/) with the C/C++ workflow enabled.

**Comment by GittyGrubHub85** [comment]
> @GittyGrubHub85 Visual Studio Code doesn't include the C/C++ compilers. You need to install [Visual Studio Community](https://visualstudio.microsoft.com/) with the C/C++ workflow enabled during the installation process. See [Compiling on Windows](https://docs.godotengine.org/en/latest/development/compiling/compiling_for_windows.html) for more information.

Will that work when using with Visual Studio Code?

**Comment by Calinou** [comment]
@GittyGrubHub85 Yes, you can use the C++ compiler without using the full-fledged Visual Studio IDE.

**Comment by GittyGrubHub85** [comment]
Here's a link to a screenshot of Visual Studio I'm trying to download
[https://i.imgur.com/v6OuKio.png](url)

Is this the correct option to download?

**Comment by Calinou** [comment]
@GittyGrubHub85 That should work. If it doesn't, I would recommend checking the C++ workflow and not unchecking any items on the right (though you definitely won't need the C++ profiling tools or CMake integration to build Godot or GDNative modules).

**Comment by Calinou** [comment]
@GittyGrubHub85 Did you get it to work?

**Comment by kone9** [comment]
Godot Engine Gdnative Solution cl is not recognized as an internal or external command "
Godot Engine C ++ Solution  cl is not recognized as an internal or external command 

``` ruby
 "cl" is not recognized as an internal or external command ".
```


# It was because you had to put the path in the windows environment variables.

Sorry there are some things in Spanish,
but I leave the screenshots.

Edit the environment variables for this account.
![Screenshot_1](https://user-images.githubusercontent.com/12847027/131401788-0bff6b2d-d1b4-4dcb-9399-54ff5d519c6b.jpg)

go to path then edit
![Screenshot_2](https://user-images.githubusercontent.com/12847027/131401882-b39f0292-f246-4193-badc-d774d4222442.jpg)

add a new
![Screenshot_3](https://user-images.githubusercontent.com/12847027/131401939-95e7ee39-fb18-422a-95f9-e364eb9f9983.jpg)

look for it in the installation folder, in my case, it is in the default folder.
![Screenshot_4](https://user-images.githubusercontent.com/12847027/131402004-179b6165-3ff5-4c04-9037-206633d8e412.jpg)

So this would be the address of the default folder
``` ruby
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\bin\Hostx64\x64
```
After doing all that, accept the options and restart the computer

As we can see, it now compiles correctly.
![Screenshot_6](https://user-images.githubusercontent.com/12847027/131402877-8436658d-a98a-4417-ae07-9a57c8d2adcd.jpg)

And so spin the cube using C ++ within Godot Engine.
[https://github.com/kone9/Godot_Engine_GDNative_CPP_Proyect_Config](url)

![Godot Engine GDnative](https://user-images.githubusercontent.com/12847027/131403646-8145c825-ff8f-4792-96d2-a1e3b8877eb7.gif)

**Comment by LucasColas** [comment]
Hello, 
I can't find :
`C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\bin\Hostx64\x64`

I have Microsoft Visual Studio. But the only available folders in Microsoft Visual Studio are  : Installer and Shared.

**Comment by aaronfranke** [comment]
@LucasColas You need to install Visual Studio using the Visual Studio Installer, it sounds like you only have the Visual Studio Installer app.

**Comment by LucasColas** [comment]
Yes I have done it but I have another issue. I think I should open another issue of find by myself a solution.

**Comment by Dziamid-Harbatsevich** [comment]
Just lefting this to update with the current release 
`C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.29.30133\bin\HostX64\x86`

**Comment by pfaraji87** [comment]
'cl' is not recognized as an internal or external command, operable program or batch file.
Hello, this is the problem I have.
I installed the cl , it was added in the patch section, I also had a file in the program file section , and I added the program file x86 section, I have the same problem.

**Comment by LucasColas** [comment]
Ok got it
