### ISSUE TITLE
Update VR starter tutorial for Godot 3.2

### ISSUE THREAD

**Issue by aaronfranke** [godotengine/godot-docs#3363]
Well, [here we are again](https://github.com/godotengine/godot-docs/issues/2727). With the release of Godot 3.2, the VR starter tutorial is again outdated and needs updating for Godot 3.2.

https://docs.godotengine.org/en/latest/tutorials/vr/vr_starter_tutorial/vr_starter_tutorial_part_one.html
https://docs.godotengine.org/en/latest/tutorials/vr/vr_starter_tutorial/vr_starter_tutorial_part_two.html

For example, there are notes such as "HDR support will be available for VR in Godot 3.2".

Also, instead of hard-coding the target framerate and physics framerate to 90, is there a way to detect the headset's framerate? For example, the Oculus Quest is 72 Hz, the Rift S is 80 Hz, and the Valve Index can do either 120 Hz or 144 Hz.

Hopefully less will need to be redone compared to last time, but I think it would be best for someone who's aware of all the VR changes to look over the whole thing (@BastiaanOlij @TwistedTwigleg).

**Comment by TwistedTwigleg** [comment]
Right now my schedule is *really* busy and it looks like it is going to be for quite a bit. When I have time (and energy), I will try to give the VR tutorial another pass, but it will probably be quite awhile before that happens.

As far as notes go, I think it is just the "HDR support will be available for VR in Godot 3.2" that is out of date. I did a super quick glance through it, and I didn't see any other notes or wording that would need adjusting for Godot 3.2, though it is possible I missed something.

If the note is the only thing that needs updating (outside of the minor thing I listed below), then someone should just make a quick PR making these changes and the issue should be closed.

If there are other bugs, issues, or something else causing the project to no longer work, can you please share what those are so they can be fixed? The issue linked implies there are more problems than just a simple note being out of place, but if it is just a note, then a simple PR should fix the issue.

___________

As noted in [this commit](https://github.com/GodotVR/godot_openvr_fps/commit/9619ff778da3fa02414cbf898c0e85fa3a7e7b39) on the OpenVR repository, `Engine.iterations_per_second` is what needs to be updated/adjusted rather than `Engine.target_fps`. It is not a huge thing and does not make a big difference overall, but it would sync the repository with the tutorial.

As far as getting the target frame-rate, I do not think there is anything that passes that information that I know of. The [ARVRServer](https://docs.godotengine.org/en/stable/classes/class_arvrserver.html#class-arvrserver) and [ARVRInterface](https://docs.godotengine.org/en/stable/classes/class_arvrinterface.html#class-arvrinterface) classes do not expose a target frame rate.

Regardless, since this is an addition/enhancement to the project itself, this should be a feature request on the [OpenVR repository](https://github.com/GodotVR/godot_openvr_fps), rather than lumped in with this issue on GitHub. I opened an [feature request](https://github.com/GodotVR/godot_openvr_fps/issues/6) on the repository so we can track it there.
