### ISSUE TITLE
Keep 3.x stable for localization instead of latest

### ISSUE THREAD

**Issue by eon-s** [godotengine/godot-docs#3392]
**Your Godot version:**
3.x

**Issue description:**
Before changes are made towards 4.0 docs, we need to keep the 3.x versions for localization, translations will never reach completion if these continue behind latest, also the differences on 3 and 4 will make all the localization useless for a long time for users of 3.x.

Also 4.0 docs will probably be completely different in content and structure, that will make impossible to use current translations on it so all the efforts will be wasted for a version that has more than a year to reach stable and localized 3.x docs will disappear.

**Comment by akien-mga** [comment]
Yeah I agree, that's what I do for the editor localization (currently synced from the `3.2` branch).

**Comment by akien-mga** [comment]
Fixed by https://github.com/godotengine/godot-docs-l10n/commit/e2c108f8b2d4194ab18d5df1607b74f3c4f13867.

There's now a `/stable` subdomain which has the same content as `/latest`, both including the docs from the `stable` branch.

Once we want to start translating the `master` branch again for 4.0, I'll create the `/3.2` branch to keep the old translations as an archive.
