### ISSUE TITLE
C# example should state GD.Print not GD.print

### ISSUE THREAD

**Issue by puthre** [godotengine/godot-docs#3505]
Godot 3.2
https://godotengine.org/article/introducing-csharp-godot has an example with GD.print but in fact it should be GD.Print
GD.print throws an error.

**Comment by akien-mga** [comment]
`GD.print` was valid back then. We can't go back and fix old blog posts when the engine evolves, any technical blog post older than a year will almost always be outdated.

**Comment by puthre** [comment]
Shouldn't this be part of the documentation that changes in line with the engine?

**Comment by akien-mga** [comment]
It is: https://docs.godotengine.org/en/stable/getting_started/scripting/c_sharp/c_sharp_basics.html

Such blog posts pre-date documentation and are often use as base material for more in-depth documentation. They're only meant to give users a first glimpse of pre-release material while it's fresh out of the oven.

**Comment by pycbouh** [comment]
@akien-mga I don't know if it's reasonable or not, but since the article is likely to pop up for some in search results and there are code samples in there, can we add a block at the top of it stating that the information is/may be outdated and link the docs in there? There is an obvious date up in there, but an explicit statement can be more obvious for some people and prevent issues such as this one.

**Comment by Vennnot** [comment]
Was this done?

**Comment by YuriSizov** [comment]
Actually, yes, we now have a note at the top of old blog posts:

![image](https://user-images.githubusercontent.com/11782833/234358373-335427d7-c8e8-48ee-a6da-ca3a809aa4c4.png)
