### ISSUE TITLE
Latest version of Texture page is empty?

### ISSUE THREAD

**Issue by Haledire** [godotengine/godot-docs#3531]
**Your Godot version:**
3.2
**Issue description:**
The link to the Texture documentation on the latest version is mostly empty.  I'm assuming someone was working on it for the latest version and pushed a page early?  It doesn't seem like a typical situation where the page doesn't exist at all, it's just that it's lacking information regarding linking types and any properties.

**URL to the documentation page:**
https://docs.godotengine.org/en/latest/classes/class_texture.html
as opposed to
https://docs.godotengine.org/en/3.2/classes/class_texture.html

**Comment by clayjohn** [comment]
This is intentional. The new version of ``Texture`` in 4.0 has no properties exposed. It is just a parent to ``Texture2D`` (the new regular "Texture") and ``TextureLayered``.

You seem to be browsing "latest" by mistake. I think you meant to look at "stable" which contains the docs for the newest released version. "latest" contains the docs for the master branch and is thus unstable.

https://docs.godotengine.org/en/stable/classes/class_texture.html
