### ISSUE TITLE
move_and_slide uses a delta-multiplied velocity in a couple places

### ISSUE THREAD

**Issue by nanodeath** [godotengine/godot-docs#3612]
**Issue description:**

Multiple places recommend NOT multiplying the velocity vector by delta when using `move_and_slide` ([here](https://docs.godotengine.org/en/stable/classes/class_kinematicbody.html#class-kinematicbody-method-move-and-slide) and [here](https://docs.godotengine.org/en/stable/tutorials/physics/using_kinematic_body_2d.html), in the second tip near the top). However, the URLs I list below do actually use `move_and_slide` with a delta-multiplied vector, which is confusing to new users.

**URL to the documentation page:**

* https://github.com/godotengine/godot-docs/blob/master/tutorials/physics/kinematic_character_2d.rst last code example
* https://docs.godotengine.org/en/stable/tutorials/physics/using_kinematic_body_2d.html also last code example

**Comment by cbscribe** [comment]
In neither of these examples is velocity multiplied by `delta`. Perhaps you are confused by the fact that `gravity`,  an *acceleration*, is multiplied by `delta` in order to properly calculate the velocity.

**Comment by nanodeath** [comment]
So...to clarify, for move_and_collide, you should multiply your gravity acceleration by delta twice, and for move_and_slide you should multiply it once?

**Comment by cbscribe** [comment]
Where are you seeing gravity multiplied twice? Acceleration and velocity are separate quantities.

Acceleration measures the change in velocity per unit time. Its units are pixels/s^2. To find how much your velocity changes in a certain amount of time, multiply by the time. The result is in pixels/s, a velocity. Velocity is a measure of change in position per unit time. To find out how much your position changes, multiply velocity by the time. Your result is in pixels.

In practical terms, consider these examples:

If you are moving a Sprite (no kinematic movement methods), you would do:

```
velocity += gravity * delta  # calculate change in velocity
position += velocity * delta  # calculate change in position
```

If you are using `move_and_collide()` that becomes:

```
velocity += gravity * delta  # calculate change in velocity
move_and_collide(velocity * delta)  # changes the position, while considering collision
```

If you are using `move_and_slide()`:

```
velocity += gravity * delta  # calculate change in velocity
move_and_slide(velocity)  # because it is done internally
```

Just because `move_and_slide()` handles applying `delta` to the velocity internally, you still need to apply `delta` to any *other* time-based quantities such as gravity, friction, etc.

**Comment by nanodeath** [comment]
Alright, I get it. If you have an acceleration, like gravity, that's pixels/s/s, and `move_and_collide` expects pixels, while `move_and_slide` expects pixels/s. I wasn't thinking too much about the units when clearly I needed to.

Thanks for explaining!
