### ISSUE TITLE
enum Align section needs prefix 'H'

### ISSUE THREAD

**Issue by 1shevelov** [godotengine/godot-docs#3665]
**Your Godot version:**
3.2.1-stable and 3.2.2-beta4

**Issue description:**
enum Align section in embedded docs and on site needs update to reflect prefix H for constants ALIGN_LEFT, ALIGN_CENTER, ALIGN_RIGHT and may be ALIGN_FILL (not sure) as currently implemented in Godot

**URL to the documentation page:**
godot-es-docs.readthedocs.io/en/latest/classes/class_label.html
and others (see screenshots)

![ALIGN-enums](https://user-images.githubusercontent.com/30589388/84028273-17a4fb00-a999-11ea-96ce-823014014c2a.png)
![ALIGN-enums-articles](https://user-images.githubusercontent.com/30589388/84028277-196ebe80-a999-11ea-9142-fc5dd839a724.png)
![ALIGN-enums-error](https://user-images.githubusercontent.com/30589388/84028281-1a9feb80-a999-11ea-8945-0e50c2dfb9bb.png)

**Comment by akien-mga** [comment]
I'm not sure I understand, but the API reference matches the Godot API, it can't be wrong per se as it was generated.

You get an invalid identifier because your scene does not inherit any class that implements `ALIGN_CENTER`.

You should use `Label.ALIGN_CENTER`, assuming that `game_results_popup_label` is a `Label`. (Or `game_results_popup_label.ALIGN_CENTER` would work too, but it's more verbose.)

**Comment by 1shevelov** [comment]
Thank you, akien-mga.
You are certainly right. I see now that HAlign is a @GlobalScope's enum that's why it worked in the first time.
