### ISSUE TITLE
Why do you add warning for Linux/BSD?

### ISSUE THREAD

**Issue by DeafMan1983** [godotengine/godot-docs#3716]
Hello everyone, 

Why do you say about warning? 
![image](https://user-images.githubusercontent.com/57066679/85233501-2bc01200-b407-11ea-8b37-d0550ae75379.png)

God you forget to add "-no-pie" for Ubuntu 18.04 or later when you compile at status.

Because I use with -no-pie since Ubuntu 18.04 and linux binary will be clickable.

Thanks for adding if later version of GCC or Linux fails with pie support. 
Look out [resolve of "-no-pie"](https://stackoverflow.com/questions/47778099/what-is-no-pie-used-for)!

Thank you for my support!

**Comment by akien-mga** [comment]
This warning has nothing to do with `-no-pie`, which is only necessary on Ubuntu 18.04 because of a Nautilus bug which can't recognize binaries from libraries.

The warning is true, because when you build a Linux binary on a Linux distro, it will link against its glibc API, and will not be compatible with distros that run an older glibc version. You can confirm that by building on Ubuntu 18.04 and then trying this binary on Ubuntu 16.04.

**Comment by DeafMan1983** [comment]
Okay I understand thanks @akien-mga  
I think sure you would like to have a lot of work with glibc version - if you try to resolve with [link](https://stackoverflow.com/questions/725472/static-link-of-shared-library-function-in-gcc) then executable runs without problem.

Thanks for everyone and stay safe at home!
