### ISSUE TITLE
Google Analytics

### ISSUE THREAD

**Issue by resynth1943** [godotengine/godot-docs#3792]
## Remove Google Analytics

If you must have an analytics system, might I suggest either:
- Plausible: https://plausible.io (offers a 50% discount for FOSS projects)
- Goatcounter: https://goatcounter.com
- Matomo: https://matomo.org
- Fathom: https://usefathom.org

These solutions are all well-tested and open-source. This, of course, means they
can be independently audited for privacy and security. Instead of using a proprietary
nonfree system such as Google Analytics, perhaps we could work together to replace
it with something slightly more ethical?

Furthermore, the majority of privacy features in evergreen browsers *block* Google
Analytics from being run. I can not say the same for solutions such as Plausible,
which suggests they are trusted for their privacy by independent persons.

If you need any more information, please contact me!

**Comment by clayjohn** [comment]
This looks like an accidental copy-paste from somewhere else. 

Did you intend to post here? If so, can you clarify what commit you are talking about?

**Comment by YeldhamDev** [comment]
I'm quite sure that the docs don't use Google Analytics, and thank goodness for that!

**Comment by resynth1943** [comment]
I'm pretty sure I saw a Godot website using Google Analytics. Can't find it now. Strange.

Maybe I'm just tired. Sorry.

**Comment by resynth1943** [comment]
Ahh, I was talking about [this](https://godotengine.itch.io/godot). In retrospect, that was very silly lol

**Comment by akien-mga** [comment]
For the reference, the Godot website did have GA until mid 2016, and then the docs website had GA until a few weeks ago (and it was wrongly set up so the docs analytics nuked the homepage analytics, hence no data there since 2016).

I removed the non-working footer from the website and the working GA token from the ReadTheDocs config a few weeks ago when finalizing Godot's privacy policy. We weren't using this data much and it's simpler not to collect than to have to put a wall of text in the privacy policy to justify it.
