### ISSUE TITLE
Slider class API docs is missing it's signals

### ISSUE THREAD

**Issue by golddotasksquestions** [godotengine/godot-docs#3837]
**Your Godot version:** 3.2, stable, latest

**Issue description:** Signals category is missing here https://docs.godotengine.org/en/latest/classes/class_slider.html
Both Hslider and Vsider nodes have signals "changed" and "value_changed(value)", but they can't be found here or there
https://docs.godotengine.org/en/latest/classes/class_hslider.html
https://docs.godotengine.org/en/latest/classes/class_vslider.html

**Comment by Calinou** [comment]
This is because they're defined in the [Range class](https://docs.godotengine.org/en/latest/classes/class_range.html#class-range). Unfortunately, we can't display them in other classes as that would be inconsistent (doing for for all nodes would result in dozens of signals being visible on every page).

**Comment by golddotasksquestions** [comment]
Um, how about adding a link to the Range class then within the description? @Calinou
