### ISSUE TITLE
Add an API skill level indication

### ISSUE THREAD

**Issue by boukew99** [godotengine/godot-docs#3871]
**Your Godot version:**
3.2.2

**Issue description:**
I was trying to use and learn the high-level networking code, while not having any experience in it. I tried to learn it by looking at demos , tutorials and the documentation, but still I did not seem to get it. Eventually I gave up, because I did not know whether I missed something or because it was more difficult than I expected. 

It would be nice to be able to know what classes are in my skill level, so a smoother learning experience can happen.
A good metaphor for my solution are ski slopes. There are many slopes you can take to go down and some are more difficult than others, but everyone gets access to all the slopes (also the difficult ones). Still beginners can take routes for there skill level, because color indications are used for difficulty (green: Beginner, blue: Early Intermediate, red: Advanced Intermediate, black: Expert). This enhances accessibility for beginners.

I was thinking of coloring the Class name or adding a colored square, but more ways are possible to provide this solution.

![Annotation 2020-08-04 150757](https://user-images.githubusercontent.com/49942484/89297610-72d72f00-d664-11ea-9728-e8f3d6167ec0.png)

**URL to the documentation page (if already existing):**
.

**Comment by rjkilpatrick** [comment]
IMO adding a suggested learning path would be better. `NetworkMultiPlayerENet` is not specifically a difficult API (in and of itself) and is well described with the documentation. It is difficult to learn however, because of the required knowledge to understand how to use the API. Networking is a difficult topic, but Godot makes it really easy to use.

I propose introducing a worked example as a part 7 in the [FPS tutorial](https://github.com/godotengine/godot-docs/tree/master/tutorials/3d/fps_tutorial), as that's the closest thing the docs currently have to a linear progression.

I would also add to the [high-level networking tutorial](https://docs.godotengine.org/en/stable/tutorials/networking/high_level_multiplayer.html), to better explain what a `NetworkedMultiplayerPeer` is.

**Comment by boukew99** [comment]
That makes sense. Could indeed be a better place to put it.
