### ISSUE TITLE
AnimationPlayer "Duplicate Transposed" needs better documentation

### ISSUE THREAD

**Issue by noidexe** [godotengine/godot-docs#3967]
**Godot version:**
b101726

**OS/device including version:**
Win 7 64

**Issue description:**
Expected: "Duplicate Transposed" duplicates keyframes in reverse order. 
Actual: No apparent difference between choosing "duplicate selection" and "duplicate transposed"

**Steps to reproduce:**
- open Animation Dock
- add a channel
- add some keyframes
- select keyframes
- Right click-> Duplicate Transposed 

**Minimal reproduction project:**

**Comment by akien-mga** [comment]
Moved to godot-docs.

**Comment by skyace65** [comment]
@GDQuest I believe this functionality was removed so you can close this issue. I tried following the OPs instructions and couldn't get the "Duplicate Transposed" option to show up. I checked the code and something related to it is still in there but what I think is the keyboard shortcut isn't working.

**Comment by NathanLovato** [comment]
It's been removed, yes, closing.

**Comment by KoBeWi** [comment]
The duplicate transposed option still exists in the Edit menu and it even has a default shortcut:
![image](https://user-images.githubusercontent.com/2223172/145126244-f985985a-9f7e-4f95-9a98-96ea7823f8f4.png)
I opened a new issue, because I think it should be renamed or something: https://github.com/godotengine/godot/issues/55713
