### ISSUE TITLE
Undocumented CLAYER GraphEdit child transform useful for GraphNode offset calculation

### ISSUE THREAD

**Issue by Rubonnek** [godotengine/godot-docs#3985]
**Your Godot version:**
3.2 branch at commit 784e854e580f8a9335c8dc738bbc8b83ea0fdd65
Also applies to current master branch.

**Issue description:**
`GraphEdit` nodes have an [intrinsic `CLAYER` child](https://github.com/godotengine/godot/blob/2a5d4b246dfec9a731a693d4408010e00d48c07a/scene/gui/graph_edit.cpp#L1300-L1305) whose transform can be used to calculate `GraphNode.offset` when, for example, using an `ItemList` to drag and drop a `GraphNode` into the `GraphEdit` node.

The correct way to do this calculation under `GraphEdit.drop_data` is the following:

```gdscript
func drop_data(p_position : Vector2, p_data : String):
    var offset_calculation = self.get_node("CLAYER").get_transform().xform_inv(p_position) / self.get_zoom()
```
Assuming `self` above represents the `GraphEdit` node.

An example project that can be used to quickly test this is [Whiskers](https://github.com/LittleMouseGames/whiskers).

**URL to the documentation page (if already existing):**
It's undocumented.

**Comment by NathanLovato** [comment]
Considering the child node isn't exposed explicitly as a property or via a getter method, it's not an intended use. While you can technically access any node in the editor by path, for instance, if they're not exposed through the API, they're not meant to be accessed or modified. You could say doing so is a "hack" (even though sometimes it's useful).

Rather than documentation, if you need access to some data the node provides, you'll want to add a property or method in the engine and write the corresponding reference.

I'll close the issue for now as this isn't about docs. I'm not sure if the next step should be a proposal or direct PR on the godotengine repo but it's either of those.

**Comment by Rubonnek** [comment]
Welp, you are right.

I didn't realize the `CLAYER` transform data needed was already exposed in `GraphEdit.get_scroll_ofs()` so there's no need to access this internal node directly.

The equivalent offset calculation using the available API is:

```gdscript
func drop_data(p_position : Vector2, p_data : String):
    var offset_calculation = (p_position + self.get_scroll_ofs()) / self.get_zoom()
```

assuming `self` above represents the `GraphEdit` node.
