### ISSUE TITLE
Undocumented shebang usage

### ISSUE THREAD

**Issue by Rubonnek** [godotengine/godot-docs#3990]
**Your Godot version:**
3.2 branch
4.0 master branch

**Issue description:**
The command line tutorial has the following script, but it's not showcasing a shebang users could also use like the following:

```gdscript
#!/usr/bin/godot -s
extends SceneTree

func _init():
	print("Hello World!")
	quit()
```

This way users only need to do:

```shell
chmod 755 hello_world.gd #once
./hello_world.gd # onwards, and not have to type "godot -s" every time.
```

**URL to the documentation page (if already existing):**
https://docs.godotengine.org/en/stable/getting_started/editor/command_line_tutorial.html

**Comment by Calinou** [comment]
[Looking into it](https://stackoverflow.com/questions/4303128/how-to-use-multiple-arguments-for-awk-with-a-shebang-i-e), using `!#/usr/bin/env` with multiple arguments requires using the following syntax:

```bash
#!/usr/bi/env -S godot -s
```

This is only supported since coreutils 8.30, which is only in Ubuntu 20.04 and later. (This feature has been available on *BSD for years now.)

**Comment by Rubonnek** [comment]
I see. Thanks for the information! I'll keep this in mind when I submit a PR sometime at the end of the week.

**Comment by Rubonnek** [comment]
I dusted off  my Mac Mini, and turns out `env -S` also works there which is nice!

I'll shoot a PR soon.
