### ISSUE TITLE
AudioStreamMicrophone has no description

### ISSUE THREAD

**Issue by robbertzzz** [godotengine/godot-docs#3997]
**Your Godot version:**
3.2.2

**Issue description:**
There is no description of the AudioStreamMicrophone class

**URL to the documentation page (if already existing):**
https://docs.godotengine.org/en/stable/classes/class_audiostreammicrophone.html

**Comment by synalice** [comment]
@Calinou

Issue is already fixed by [c6461d3](https://github.com/godotengine/godot/commit/c6461d31d2a9717dfac76aa102ba9bf97433abb9) and can be closed.

Although, for some reason this doc page exists only for documentation of [version 3.5](https://docs.godotengine.org/en/3.5/classes/class_audiostreammicrophone.html) not any other [previous version](https://docs.godotengine.org/en/3.4/classes/class_audiostreammicrophone.html). Godot 3.5 is an LTS, so it probably doesn't matter.

**Comment by Calinou** [comment]
Thanks for bringing it to my attention :slightly_smiling_face: 

> Although, for some reason this doc page exists only for documentation of [version 3.5](https://docs.godotengine.org/en/3.5/classes/class_audiostreammicrophone.html) not any other [previous version](https://docs.godotengine.org/en/3.4/classes/class_audiostreammicrophone.html). Godot 3.5 is an LTS, so it probably doesn't matter.

The documentation in question was only merged in 3.5, so older versions won't list it.
