### ISSUE TITLE
How to translate docs

### ISSUE THREAD

**Issue by rolfpancake** [godotengine/godot-docs#4]
I don't get how to translate files.

> To translate an existing page, simply copy its original content. Then, create the new page **in the section of your language**, copy the English content in it and start translating.

Where to find/place the sections?
Sorry if I overlooked something.

**Comment by akien-mga** [comment]
Hi @rolfpancake 

As I wrote [on the page](http://docs.godotengine.org/en/latest/contributing/doc_and_l10n_guidelines.html#translating-existing-pages), its contents are outdated as they were written for the OpenProject wiki, and need to be adapted to the new system based on sphinx-doc.

Translating the docs is not possible right now, but I'm planning to work on it this week and some porting of the existing translations in the OpenProject wiki will be done over the week-end. If you were already translating content there, I'll gladly use your help to port the content.

Basically the new translation workflow will be:
- each language will have its own branch in this repo, at first a 1:1 copy of the (English) master branch (minus the ``classes/`` folder, as it should not be translated this way - and IMO not be translated at all for the time being).
- the files will keep their English name so that we can easily match translated content with the English source, to check e.g. for new content that needs to be translated (\*)
- the contents of each file will then be replacing by the translated content; for the languages that already at some translation on the OpenProject wiki, I have a local copy of the database and all this content. So the first task after the branching will be to copy paste the translated content in the corresponding files.
- the translated branches will then be use to power their own readthedocs.org instances, with some fallbacks to the English website for missing contents (like the class reference).

See http://docs.readthedocs.org/en/latest/localization.html#project-with-multiple-translations and the example given for more info on how it would be like.

(\*) The big advantage of keeping the same file names is that we could then write a custom script that checks the timestamp of "some_file.rst" in the translation branch, then checks the timestamp of the equivalent file in the master (English) branch. If the English page is newer, it will then generate a report with links to the relevant diffs, so that translators can see easily what was added to the English page, and propagate the changes in their translation.

**Comment by rolfpancake** [comment]
Okay, so I was a bit impatient.

> If you were already translating content there, I'll gladly use your help to port the content.

I wasn't translating content there but will gladly help where I can.

> If the English page is newer, it will then generate a report with links to the relevant diffs [...]

This would be an outstanding feature!

**Comment by solfen** [comment]
Is this still going on? I would love to help by translating content.

**Comment by popenke** [comment]
I could help with a Brazilian portuguese translation, @akien-mga.

**Comment by Omaranwa** [comment]
i will add arabic if you want?

**Comment by NathanLovato** [comment]
Closing for now, we'll open an issue to discuss localization when the docs are ready for it.

**Comment by akien-mga** [comment]
Translations are now possible, see my comment at the end of #1057 for details.
