### ISSUE TITLE
Document ProximityGroup

### ISSUE THREAD

**Issue by NathanLovato** [godotengine/godot-docs#4134]
I’m unsure whether this best fits in Physics or Performance / Optimization

**Comment by Calinou** [comment]
I documented ProximityGroup in the class reference in https://github.com/godotengine/godot/pull/60636. However, since ProximityGroup was removed in 4.0alpha in favor of a more efficient VisibilityNotifier (now VisibleOnScreenNotifier), I don't think it's worth creating a full manual page for it. Relying on the feature will impede projects that wish to upgrade to 4.0 once it's released.
