### ISSUE TITLE
Document why it's not possible to create projects with spaces at the end of the name with Project Manager

### ISSUE THREAD

**Issue by me2beats** [godotengine/godot-docs#4287]
**Your Godot version:**
3.2.3 Windows

**Issue description:**
![Invalid project name](https://user-images.githubusercontent.com/16458555/96366585-dea83e80-1161-11eb-9fa8-9607289385f9.JPG)

It seems in Project Manager it's not possible to create a project with spaces at the end of the `Project Name` like `new `, `new game ` etc
I think this should be documented because the user may not expect this behavior, at least on Windows

**URL to the documentation page (if already existing):**

**Comment by haxanthometer** [comment]
On GNU/Linux, I can confirm I get the same results as well. It's a minor thing, but I suppose it should be documented anyways.

**Comment by Calinou** [comment]
It would probably be better to trim whitespace in the field to ignore it, and allow project creation anyway.

**Comment by Sslaxx** [comment]
https://github.com/godotengine/godot/issues/32330 is related.

**Comment by skyace65** [comment]
Just checked and the editor will automatically trim whitespace at the end of project names now. And since I can't think of a use case where you'd intentionally want white space at the end of a file I think this issue can be closed. The issue Sslaxx brings up still happens but shouldn't be documented. The proper solution is for the engine to stop you from adding a `.` to the end of a project name. There's no good place in the documentation where everyone would see that information.
