### ISSUE TITLE
Doc needs improvement ( Simple 2D game )

### ISSUE THREAD

**Issue by mrwanashraf** [godotengine/godot-docs#435]
after following [this doc](http://docs.godotengine.org/en/stable/learning/step_by_step/simple_2d_game.html) and after trying many times and even coping the code there.

the simple pong game doesn't function well.

the ball is not moving at all.

the pads are working yes but i can't know if other features are working without testing the ball collision and without the ball moving then there would be no collision.

so i think that the script in this doc needs to be improved so that the ball would move.

**Comment by Noshyaar** [comment]
I don't think there are any changes to GDScript that would break it on stable branch? You're using Godot 2.x, right?

**Comment by mrwanashraf** [comment]
yes I'm  and here is the code
```
extends Node2D

# Member variables
var screen_size
var pad_size
var direction = Vector2(1.0, 0.0)

# Constant for ball speed (in pixels/second)
const INITIAL_BALL_SPEED = 80
# Speed of the ball (also in pixels/second)
var ball_speed = INITIAL_BALL_SPEED
# Constant for pads speed
const PAD_SPEED = 150

func _ready():
    screen_size = get_viewport_rect().size
    pad_size = get_node("left").get_texture().get_size()
    set_process(true)

func _process(delta):
    var ball_pos = get_node("ball").get_pos()
    var left_rect = Rect2( get_node("left").get_pos() - pad_size*0.5, pad_size )
    var right_rect = Rect2( get_node("right").get_pos() - pad_size*0.5, pad_size )
    # Integrate new ball position
    ball_pos += direction * ball_speed * delta
    # Flip when touching roof or floor
    if ((ball_pos.y < 0 and direction.y < 0) or (ball_pos.y > screen_size.y and direction.y > 0)):
        direction.y = -direction.y
    # Flip, change direction and increase speed when touching pads
    if ((left_rect.has_point(ball_pos) and direction.x < 0) or (right_rect.has_point(ball_pos) and direction.x > 0)):
        direction.x = -direction.x
        direction.y = randf()*2.0 - 1
        direction = direction.normalized()
        ball_speed *= 1.1
    # Check gameover
    if (ball_pos.x < 0 or ball_pos.x > screen_size.x):
        ball_pos = screen_size*0.5
        ball_speed = INITIAL_BALL_SPEED
        direction = Vector2(-1, 0)
        get_node("ball").set_pos(ball_pos)
    # Move left pad
    var left_pos = get_node("left").get_pos()

    if (left_pos.y > 0 and Input.is_action_pressed("left_move_up")):
        left_pos.y += -PAD_SPEED * delta
    if (left_pos.y < screen_size.y and Input.is_action_pressed("left_move_down")):
        left_pos.y += PAD_SPEED * delta

    get_node("left").set_pos(left_pos)

    # Move right pad
    var right_pos = get_node("right").get_pos()

    if (right_pos.y > 0 and Input.is_action_pressed("right_move_up")):
        right_pos.y += -PAD_SPEED * delta
    if (right_pos.y < screen_size.y and Input.is_action_pressed("right_move_down")):
        right_pos.y += PAD_SPEED * delta

    get_node("right").set_pos(right_pos)
```

yet the ball is not moving , pads are working just fine but the problem is with the ball.

**Comment by Noshyaar** [comment]
Line 40

```
    # Check gameover
    if (ball_pos.x < 0 or ball_pos.x > screen_size.x):
        ball_pos = screen_size*0.5
        ball_speed = INITIAL_BALL_SPEED
        direction = Vector2(-1, 0)
    get_node("ball").set_pos(ball_pos)          <--------- Move it one tab to the left
    # Move left pad
```

The docs is kinda unclear because it's not in the same codeblock.

**Comment by mrwanashraf** [comment]
it worked! thanks alot :)

i have a suggestion:

maybe the docs should have an indicator for tabs or spaces like this 
```
# Check gameover
>>if (ball_pos.x < 0 or ball_pos.x > screen_size.x):
    >>ball_pos = screen_size*0.5
    >>ball_speed = INITIAL_BALL_SPEED
    >>direction = Vector2(-1, 0)
```

**Comment by toger5** [comment]
I think this is kind of unavoidable. When adding >> to the code examples than copy pasting gets really hard...
Maybe it would be useful to add a spoiler at the end with the complete script?
Those kind of issues will always occur wheb coding. For beginners and more advanced programmers. And each times it happens you will find a new thing to watch out for...
But that is what a community is for ;).
Basic debugging paddern: the ball does not move > what line moves the ball > is that line called? > first go through the logic how it should be called line bey line, than add a breakpoint see if it gets called.than move the breakpoint upwards in the call tree and see when it gets hit. Now you only need to figure out why it doesnt go from the hit breakpoint to the line whuch should move thw ball. By steppoing over you would see how the debugger jumps over the game over if statement and by doing so also over the set_pos function.

Probably you are alrwady aware of that or have your own mehtod for debugging. Just had some time and wanted to give some tips. Because as i said you cant avoid running into those issues, but its helpful to be good at spotring them!

**Comment by mrwanashraf** [comment]
thanks alot for your valuable tips, ya i already spotted that the ball is not moving so i thought that the bug was with the ball movement but i didn't know what to do since I'm new to godot and to game dev anyways so i thought of reporting it so that someone new like me won't be stuck in the same problem I'm and maybe then the person will think the code is bad or the engine has a bug or overthinking something that's not true and i really care for godot reputation because i feel that this engine will be the best engine soon :)

**Comment by pwab** [comment]
It's true that this tutorial could lead to this situation because the if-block before the concerned line leads to automatic indentation plus the newbie game developer aspirant may not have used a programming language which is based on syntactical indentation (like python).

The suggested solution of adding extra chars (like >>) is impractical. It is more common to use a specific codeblock theme which supports this kind of things. (See the attached example image taken from VS Code. You can clearly see the indentation levels because of the autogenerated lines on the left.)

![vscode_sample_syntax](https://user-images.githubusercontent.com/19271185/29063637-c23a258e-7c26-11e7-9074-32d5475c9cf3.jpg)

To my knowledge unfortunately there is no such codeblock theme on readthedocs. 😔
(And also this would not prevent this problem because the concerned line isn't indented at all.)

> toger5:
> Maybe it would be useful to add a spoiler at the end with the complete script?

This is the most common way of providing a complete overview of the code structure and should be considered for every tutorial in the docs. I vote for this!

It is also possible to create a teaching video for every lesson in the docs (as with [programarcadegames](http://programarcadegames.com) or [gamesfromscratch](http://www.gamefromscratch.com/post/2015/01/04/A-Closer-Look-at-the-Godot-Game-Engine.aspx)) but this means a lot of work and could lead to differences between the docs and videos (if the docs are changes but the videos aren't updated).

**Comment by NathanLovato** [comment]
Hey there. I'll be redoing the getting started section in the docs, and we're going to rewrite demos with other contributors. This tutorial is going to be re-written from scratch for the 3.0 docs, so don't worry too much about it.

And yes, the next version will link to the full sources so you can copy and paste code snippets if yours doesn't work - or load the example project in Godot directly.

**Comment by NathanLovato** [comment]
Chris wrote a new step by step game tutorial to replace the Pong game. See https://github.com/godotengine/godot-docs/issues/444
