### ISSUE TITLE
Feature request: Show images for docs.godotengine.org

### ISSUE THREAD

**Issue by GhbSmwc** [godotengine/godot-docs#4375]
Not sure if this is the appropriate place to ask, but this is the closest.

Anyway, I was thinking of showing pictures rather than just texts and code to give the user a better understanding, here is an example: https://docs.godotengine.org/en/stable/classes/class_styleboxflat.html

I mean if you look at other documentations of something else, at least they also show examples as images: https://developer.mozilla.org/en-US/docs/Games/Techniques/3D_collision_detection

Unless this is already done and that the web version is outdated.

**Comment by pycbouh** [comment]
What you've linked over at MDN is a guide/an overview, and what you've linked on Godot's documentation is a class references. It may not be a good idea to overload the latter with imagery as it is a reference and is used more for quick lookups for methods and properties rather than detailed explanations on how things work or look.

But we also have guides in the documentation, though maybe not as detailed in this particular case. Related articles are located here: https://docs.godotengine.org/en/stable/tutorials/gui/gui_skinning.html. Maybe it will give you some idea, but I do see that examples on styleboxes are lacking. Also, the stylebox class reference should link to these articles for greater discoverability.

**Comment by skyace65** [comment]
Closing per Yuri's comment
