### ISSUE TITLE
Saving games docs should mention PackedScene or ConfigFile

### ISSUE THREAD

**Issue by nightblade9** [godotengine/godot-docs#4393]
**Your Godot version:** 3.2.4

**Issue description:** The "Saving games" documentation page currently only mentions how you can load/save with JSON. This is very tedious (has to be done recursively on all classes/scenes/data saved) and brittle (changing your game can break things without you noticing).

I would like to recommend amending this page to include a reference to `PackedScene` as an alternative method. From what I can understand (just learned about this today), you can easily save a scene by:

- Creating a new instance via `PackedScene.new`
- Setting the `owner` of everything you want to serialize in the current scene (can be done with a quick loop through `get_children()`
- Calling `packed_scene.pack(self)` and then `ResourceSaver.save('user://...', self)`
- Can be loaded back by calling `add_child(ResourceLoader.load('user://...').instance())`

This is both easier (less boilerplate code required) and more flexible (automatically saves new changes). I don't know why it's not mentioned (and recommended above using JSON).

**URL to the documentation page (if already existing):** https://docs.godotengine.org/en/stable/tutorials/io/saving_games.html

**Comment by pycbouh** [comment]
JSON is an easy format to understand and quite widespread at that, which is probably why it was chosen. But if you want a Godot-specific way to save games, `PackedScene` is definitely not the most reasonable way to do it. Custom Resources and ConfigFiles are.

**Comment by Calinou** [comment]
See https://github.com/godotengine/godot-demo-projects/pull/517.

**Comment by nightblade9** [comment]
Both JSON and `ConfigFile` require you to write code to serialize field-by-field, which is very error-prone (not to mention tedious). Regardless, if that's the preferred method, maybe the `ConfigFile` method should be mentioned in the saving docs.

It looks like Godot doesn't have an easy way to (de)serialize an entire object, like C#'s Json.NET or Python's `pickle`. To me, that's more important than the file format and structure, because you have to keep updating your serialization code as you add/remove things from your game code.

**Comment by pycbouh** [comment]
@nightblade9 But it has. That's what custom Resources are good at. You can easily serialize and deserialize them without any manual work.

**Comment by nightblade9** [comment]
> @nightblade9 But it has. That's what custom Resources are good at. You can easily serialize and deserialize them without any manual work.

Are you suggesting something like an MVC pattern (scene being the view and controller) where all your model/data goes in resources instead of scripts that just extend Node?

Can you give a concrete example of how this should work in terms of loading and saving - both the structure/architecture of the scene, and the actual serialization/deserialization?

**Comment by pycbouh** [comment]
No, I'm not suggesting anything like it, but you are welcome to do it this way if you want. It's completely up to you.

I am merely pointing out that Resources already allow for easy serialization and can even store Godot specific types and data structures natively. In my own opinion, saving *the whole* of anything is counter productive. You probably don't need to store some big runtime model completely. Most of it can probably be restored or approximated from a lot less of data.

So when a game save file is required, I still generate an object that only has the necessary fields and fill it out in a sensible manner semi-manually. But since that object is a Resource derivative in my case, it can have helper methods that can convert runtime models into more compact data needed for saving. So even that semi-manual logic is compactly located inside of the related script. And then it's just one [`ResourceSaver.save()`](https://docs.godotengine.org/en/stable/classes/class_resourcesaver.html#class-resourcesaver-method-save) away from being written to a disk this way. You can then restore it using [`ResourceLoader.load()`](https://docs.godotengine.org/en/stable/classes/class_resourceloader.html#class-resourceloader-method-load).

**Comment by nightblade9** [comment]
I am not sure what to do with this issue, so I'm going to close it.

Feel free to re-open if you think the docs for saving can be amended to include some other options (ideally mentioning trade-offs).
