### ISSUE TITLE
Texture.get_size() limitation not documented

### ISSUE THREAD

**Issue by CitrusWire** [godotengine/godot-docs#4530]
**Your Godot version:**
3.2.3

**Issue description:**
Per this:
https://github.com/godotengine/godot/issues/44996
I would suggest adding a note to Texture.get_size()
> Note: This will ignore any regions you have set on the Sprite. If the Texture is using a region and you want the size of the resulting sprite, use: `get_node("Sprite").get_rect().size`

**URL to the documentation page (if already existing):**
https://docs.godotengine.org/en/stable/classes/class_texture.html#class-texture-method-get-size

**Comment by pycbouh** [comment]
As I mentioned in #4529 there is no point documenting such specific problems that an individual user faced. `Texture` has nothing to do with the `Sprite` node and any idea that a method of a `Texture`, or any other resource or data object, would somehow be aware of something that is beyond its own class is a misconception.

This is something that is solved by getting more experience with programming.

**Comment by akien-mga** [comment]
Indeed, `Texture` is a more generic than just the texture that you use specifically in `Sprite`. You may think otherwise as you start and mostly interact with `Sprite`, but that doesn't mean that `Texture` should document Sprite-specific features. In fact, the type you're likely using in `Sprite` is even `StreamTexture` (which inherits `Texture`). Other texture types like `AtlasTexture` or `AnimatedTexture` could behave differently.

There's no limitation of `Texture.get_size()` - it's returning the size of the Texture, which does not change if you enable regions in `Sprite`, as said in godotengine/godot#44996.

On the other hand, the documentation for `Sprite.region_enabled` could be improved to make it clear that enabling `region_enabled` does not actually create a new Texture resource with the given region, but it displays only the part of the texture specified by `Sprite.region_rect` (and the size of that texture region is... `region_rect.size()`).

**Comment by CitrusWire** [comment]
>You may think otherwise as you start and mostly interact with `Sprite`

... Which is exactly when you need the documentation the most!

> There's no limitation of Texture.get_size()

Technically it's not and I appreciate that, but it's still behaviour I expect a lot of new users will find unexpected.

> On the other hand, the documentation for Sprite.region_enabled

Which would be useful too, but this assumes the user comes at the docs from the Sprite perspective rather than the Texture perspective (where I came from).
In particular given various online resources say to use texture.get_size():
https://godotengine.org/qa/22996/how-to-view-a-node2ds-height-and-width
https://www.davidepesce.com/2020/06/26/sprite-stacking-in-godot/

**Comment by pycbouh** [comment]
> Which would be useful too, but this assumes the user comes at the docs from the Sprite perspective rather than the Texture perspective (where I came from).

But you did actually come from the `Sprite` perspective, because you started with an assumption that *within a `Sprite`* a `Texture` by itself must behave differently. If you believe that you came from the `Texture` perspective, you are misidentifying the problem. From the `Texture` perspective, there is no `Sprite`. From the `Texture` perspective, it can be used by a dozen of `Sprite`s and `TextureRect`s each of which have different clipping settings. Your problem is precisely in the fact that you assume there is a relationship with `Sprite` that has some internal effect on the `Texture`.

So Akien is correct, we should add a note for the `Sprite`'s region properties as this is the only possible source of confusion.

**Comment by CitrusWire** [comment]
> But you did actually come from the `Sprite` perspective, because you started with an assumption that _within a `Sprite`_ a `Texture` by itself must behave differently.

Nope. I came from a tutorial much like the ones linked, and that tutorial was using `get_texture.get_size`, so that's what I used. No interest in learning the intricacies of textures versus sprites at this point; I'm simply prototyping. The fact that you, akien, and KoBeWi have all felt the need to explain the disparity between them only exemplifies my point: This isn't going to be obvious/clear to new users.

I'm afraid I don't understand the resistance to making the documentation clearer. It'll benefit some new users, and there are no good reasons not to that I can see. If "document bloat" is a thing it's never a thing I've ever seen given how much most programmers hate writing docs. I'd be surprised if the average length of a method explanation across the class docs is much more than 10 words. Brevity has its place (though neither of us would know anything about that ;-) ), but it shouldn't be at the expense of clarity, especially not in docs.

**Comment by CitrusWire** [comment]
> I see sometimes people unfamiliar with coding reading it like that

I very much appreciate the kindness of the suggestion, but I've been programming for 20+ years, including professionally. ;-) In this case I hadn't realised that in the Editor>Inspector I was fiddling with the Sprite and not the Texture. This is more a not-groking-Godots-Nodes-yet-and-how-they-work-with-Resources thing.

**Comment by pycbouh** [comment]
> Nope. I came from a tutorial much like the ones linked, and that tutorial was using `get_texture.get_size`

But that's exactly it. You are getting the texture property of some object. We assume it was a Sprite object, because you've claimed as much, but whatever that object may be, you still are accessing its property by calling `get_texture()`. 

> No interest in learning the intricacies of textures versus sprites at this point

There is no intricacies. Sprites are nodes, textures are resources (data) that you assign to, among other things, properties of nodes such as Sprite. It's pretty clear from the moment you actually use it. And if it's not clear, it is not a problem of the `get_size` method.

> I'm afraid I don't understand the resistance to making the documentation clearer.

We proposed to make it clearer where it actually matters, in the `Sprite` documentation, but you want us to add unrelated information to the `Texture` class, which will confuse people who are not coming into it with exactly the same confusion as yours. And the only source of this confusion is misunderstanding of programming principles and object relationships, which is not solved by adding unrelated things to individual methods, but rather by teaching CS in general. And this is beyond the scope of *our* documentation.

> I've been programming for 20+ years, including professionally

I'm sorry, but I fail to see in this case how you can misinterpret what `get_texture().get_size()` actually does. The only way the texture could be aware of its owner is if it was put into it explicitly and this goes against most OOP and programming patterns you'd meet in your career. Doubly so because the texture is assigned by reference and can be used by multiple users, so it cannot have a single owner and there cannot be aware of clipping regions of each particular owner when you call a method like that.

**Comment by CitrusWire** [comment]
At this point I'd like to suggest that you're telling me how I should be thinking; and what I'm thinking is something I happen to be much more of an expert on than you ;-) .

Again you have to remember not everyone knows what you do, and nor are things that are obvious to you clear to everyone else. Different people will come to Godot with different backgrounds.

> Doubly so because the texture is assigned by reference and can be used by multiple users

Not something I knew until you just told me. Thanks.

> You are getting the texture property of some object. [it] was a Sprite object ... you still are accessing its property by calling get_texture()

Indeed, but what I didn't know until now is that the texture was passed by reference. I just assumed it was a static valued property of a Sprite. It's a very reasonable assumption to make when you come from my background which includes a lot of raster images but used in very different ways.

> I'm sorry, but I fail to see in this case how you can misinterpret what `get_texture().get_size()` actually does.

Again, I didn't. I knew exactly what it did; the mistake was not knowing about how Textures related to Sprites.

**Comment by pycbouh** [comment]
> Not something I knew until you just told me. 

Textures do extend the `Resource` type which in term extends the `Reference` type. Basically, everything but built-in types is passed by references in Godot. Maybe it is not made exactly clear in the [GDScript basics docs](https://docs.godotengine.org/en/stable/getting_started/scripting/gdscript/gdscript_basics.html), but it's probably not something worth mentioning next to every property of every object in the class references.

> Different people will come to Godot with different backgrounds.

And we try to equalize it by requiring people to take a look at the introductory course at Harvard. It's free and not that long. Also, keep in mind, that the same logic applies to your reports: just because you have an issue doesn't mean that everyone or even a significant amount of people will.

**Comment by skyace65** [comment]
Closing per Yuri and Akien's comments
