### ISSUE TITLE
Adjust Reference and Resource class description to remove any notion that they are unrelated to Objects

### ISSUE THREAD

**Issue by pycbouh** [godotengine/godot-docs#4531]
**Your Godot version:**
3.x

**Issue description:**
It was brought up on Discord that `Reference`s and `Resource`s have a potentially confusing wording in their description. Both of those classes have statements starting with "*Unlike Objects ...*", which can be interpreted to mean that they are not actually `Object`s and are something unrelated instead. This can be worded better to make it clear that those types are built upon `Object` instead.

**URL to the documentation page (if already existing):**
https://docs.godotengine.org/en/stable/classes/class_reference.html#class-reference
https://docs.godotengine.org/en/stable/classes/class_resource.html#class-resource

**Comment by name-here** [comment]
I'd suggest something like "Unlike plain `Object`s, `Reference`s…" for the `Reference doc, and in the `Resource` doc, replace "Unlike `Objects`, they are reference-counted and freed when no longer in use." with "Since they inherit from `Reference`, Resource`s are reference-counted and freed when no longer in use."
