### ISSUE TITLE
Properties/methods only added in 3.2.4 betas/RCs are listed in the stable documentation

### ISSUE THREAD

**Issue by jtiai** [godotengine/godot-docs#4616]
**Your Godot version:**

3.2.3

**Issue description:**

`Array` documents `append_array` method which is not in stable version.

**URL to the documentation page:**

https://docs.godotengine.org/en/stable/classes/class_array.html?highlight=append_array#class-array-method-append-array

**Comment by pycbouh** [comment]
This is not a bug. This is a new method coming in Godot 3.2.4 (godotengine/godot#43398). We are [getting ready for 3.2.4 release](https://godotengine.org/article/release-candidate-godot-3-2-4-rc-1) and the docs has been synchronized already.

**Comment by jtiai** [comment]
Unfortunately people get confused that and are asking why their code don't work even docs says it's there. 
Probably it should state for the function as in many other docs "New in 3.2.4" or documentation otherwise indicate that "stable" doesn't mean 3.2.3 but 3.2.4 to avoid confusion.

**Comment by Calinou** [comment]
> Probably it should state for the function as in many other docs "New in 3.2.4" or documentation otherwise indicate that "stable" doesn't mean 3.2.3 but 3.2.4 to avoid confusion.

We don't have a way to track this in the XML class reference.

**Comment by aaronfranke** [comment]
Based on [this Twitter thread](https://twitter.com/Akien/status/1371430127545020417), it seems that 3.2.4 being renamed to 3.3 is a strong possibility. If done, this rename would be a very nice solution to this problem, because then the new 3.3 additions would be under a 3.3 branch of the docs, and the 3.2 branch of the docs would be for things in 3.2.3 or 3.2.5+ (skipping 3.2.4 because it would be confused with 3.3).

**Comment by akien-mga** [comment]
Fixed, the 3.2.4 changes are removed from the 3.2 branch.
