### ISSUE TITLE
Rename default branch

### ISSUE THREAD

**Issue by MrBrain295** [godotengine/godot-docs#4625]
**Your Godot version: Any**

**Issue description: Rename default branch from master to main.**

**URL to the documentation page (if already existing):**

**Comment by akien-mga** [comment]
It would be good to provide some context and motivation for such request, otherwise it's unlikely to be well-received when just asking folk to do work without a justification for why that work should be done.

Luckily I'm aware of the context which likely prompts this request, which is GitHub (and other components of the Git ecosystem) changing the default branch name for *new projects* from `master` to `main`: https://github.com/github/renaming

My stance on this issue is that:

- It's a good change for new projects. `main` makes more sense `master` for the main development branch, and is less controversial.
- It's a significant change for an established project with 1.5k forks, and likely more local Git clones, which we can't rename remotely. I prefer to wait for tooling to be mature enough to make this potential switch as smooth as possible for all users, contributors, and external tooling. https://github.com/github/renaming shows that GitHub has done some good work already, but as of Git 2.30.0 the default branch name is still `master`, so I don't see a need for us to go faster than Git itself.
- It's of a much broader scope than just this repository, as if we're changing it it should be done consistently for all repos, including `godotengine/godot`, and then the next request would likely be to completely nuke the `master` world from our codebase (used in `master`/`puppet` networking keywords, and "Master" audio bus). That would break compatibility *again* after doing it just a few years back when removing the `slave` keyword, which was IMO orders of magnitude more problematic than `master` when taken alone.

So for the time being I don't see a strong justification for us to do the significant amount of work (and more significant disruption in the work of Godot contributors and users) that this proposed change would require. I'm happy to re-evaluate this in the future as tooling evolves and more of the industry settles on `main` or another option as the de-facto default Git branch name.
