### ISSUE TITLE
Clarify difference between variant and variable

### ISSUE THREAD

**Issue by ghost** [godotengine/godot-docs#4691]
**Your Godot version:**
3.2.4-rc3

**Issue description:**
Because they both start with var, people may confuse them. For example, someone might think that str2var converts a string into a variable instead of a variant if they don't know what a variant is.

**URL to the documentation page (if already existing):**
https://docs.godotengine.org/en/stable/classes/class_@gdscript.html?highlight=str2var#class-gdscript-method-str2var

**Comment by golddotasksquestions** [comment]
Godot has no "variable" return type, but there is a "Variant" return type. Also the method states what it returns in the beginning, where it says "Variant".

I would agree however the description could be a lot better, because (just as the example code shows) the String does not have to be a value that has been previously converted with var2str.

Maybe something along these lines:
"Converts a formatted string to a value of such a format. Can be used to return a String returned by var2str to the original value."

**Comment by Mickeon** [comment]
https://github.com/godotengine/godot/pull/67208 should have addressed this, by changing "value" to "**Variant**".

**Comment by tetrapod00** [comment]
Yeah, this is resolved now; the description mentions "variant" rather than "value". Notably it also moved to [here](https://docs.godotengine.org/en/4.3/classes/class_%40globalscope.html#class-globalscope-method-str-to-var)
