### ISSUE TITLE
Custom Module tutorial 

### ISSUE THREAD

**Issue by winter5un** [godotengine/godot-docs#4921]
**Your Godot version:**
3.3
**Issue description:**
C++ flags for compiler should be c++14 not c++11 as c++11 is not supported and does not build.
module_env.Append(CXXFLAGS=['-std=c++11']) should be module_env.Append(CXXFLAGS=['-std=c++14'])
![image](https://user-images.githubusercontent.com/18107346/118438902-c1365580-b6ed-11eb-8655-cedae5a744a4.png)

**URL to the documentation page:**
https://docs.godotengine.org/en/3.3/development/cpp/custom_modules_in_cpp.html

**Comment by akien-mga** [comment]
The flag should be removed, there's no reason to redefine it since Godot already sets it - it only leads to bugs when actually using a version lower than Godot's.

It was put initially as Godot used `c++03` and many users wanted to use `c++11` in their modules for their own code or thirdparty libraries that need it. But now this example is harmful.

Another, harmless example of a `CXXFLAGS` would be useful (though I suspect many module authors don't get that those are examples and seem to just copy paste the whole block as is).
