### ISSUE TITLE
Link of HTML copy (3.3) for offline use is 404

### ISSUE THREAD

**Issue by EduardoLemos567** [godotengine/godot-docs#4926]
**Your Godot version:**
3.3
**Issue description:**
Link to download of HTML copy of documentation is broken (404)
**URL to the documentation page:**
URL page: https://docs.godotengine.org/en/stable/
At this phrase: "You can also **download an HTML copy** for offline reading (updated every Monday). Extract the ZIP archive then open the top-level index.html in a web browser."
Broken link: https://nightly.link/godotengine/godot-docs/workflows/build_offline_docs/3.3/godot-docs-html.zip

**Comment by Calinou** [comment]
This needs https://github.com/godotengine/godot-docs/pull/4896 to be completed and merged to be fixed on the stable branch. The link should work if you check the `/latest` branch of the documentation.

**Comment by Calinou** [comment]
Fixed by https://github.com/godotengine/godot-docs/pull/4896 and https://github.com/godotengine/godot-docs/commit/382d6235413b2cd9ca5b6bc6a2673e45400a9c57.

I tested the download link and it works: https://nightly.link/godotengine/godot-docs/workflows/build_offline_docs/master/godot-docs-html-stable.zip
