### ISSUE TITLE
Dark mode is broken in the JavaScript class reference

### ISSUE THREAD

**Issue by pycbouh** [godotengine/godot-docs#4940]
**Your Godot version:**
stable

**Issue description:**
It seems one update or another changed something with the layout and the styling for dark mode class reference sections broke:

![image](https://user-images.githubusercontent.com/11782833/119998749-ad3a0000-bfd9-11eb-8f54-a389b81c3fc9.png)

**URL to the documentation page:**
https://docs.godotengine.org/en/stable/tutorials/platform/html5_shell_classref.html

**Comment by hpnrep6** [comment]
The background colour of the code blocks appears to  be the not only issue related to dark mode. Certain elements either still appear as they would have in light mode, or their dark mode colours have not been set correctly, since they aren't very visible against the dark mode background.

Example:
![Screenshot from 2021-06-17 00-23-30](https://user-images.githubusercontent.com/57055412/122331515-f5767f00-cf02-11eb-8892-4de8fac63afb.png)

In this case, the permalink icon and the comma in "path, buffer" are practically invisible.
