### ISSUE TITLE
Standards for documenting VisualScript* nodes

### ISSUE THREAD

**Issue by cbscribe** [godotengine/godot-docs#501]
I'm looking at documenting the VisualScript* nodes in the class ref, and I think there's a need for a common description standard for them. In the description text, it seems useful to describe the node's input and output ports.

For example, the VisualScriptCondition node (http://docs.godotengine.org/en/latest/classes/class_visualscriptcondition.html), which has no methods or member variables, only has the description field for information.  So this node:
![screen shot 2017-10-01 at 3 18 38 pm](https://user-images.githubusercontent.com/3812514/31059712-dbae26ae-a6bb-11e7-91d1-3826700c7c8c.png)

would have something along the lines of:
```
<description>
        Conditional (if statement) node. 
        Input Ports:
        - Sequence: [code]if (cond) is[/code]
        - Data (boolean): [code]cond[/code]
        Output Ports:
        - Sequence: [code]true[/code]
        - Sequence: [code]false[/code]
        - Sequence: [code]done[/code]
</description>
```
Alternative suggestions:
- A new `<ports></ports>` xml tag for describing these. 
    - can be populated directly from the source code.
    - can be styled
    - requires coding on the export and doc generation

- Include an image in the description of each node's default state. 
    - More "visual", so perhaps more in line with the nature of VS

Please post your thoughts here so we can come to a consensus.

**Comment by cbscribe** [comment]
@bojidar-bg Pinging you because you have a bunch of the VisualScript* nodes locked on https://hackmd.io/s/H1es51Oeqb

**Comment by bojidar-bg** [comment]
@cbscribe I'm open to giving them to someone else, in case he/she really wants. See https://github.com/godotengine/godot/pull/11653 for what I had done so far (there are some stylistic errors, but I'll make sure to fix them).

About your suggestions:
The description option seems to be the most-doable, <ports> is an additional tag for something we have bundled in a module, and images are still not a part of the classref.

Just make sure to describe the node as a "visual script node" clearly, so that nobody would confuse it.
We might have to include some additional documentation about the exact function of the node as well.

**Comment by cbscribe** [comment]
Alright, I'm going to do a few with the `<description>` tag and we can go from there.

**Comment by NathanLovato** [comment]
Seems the discussion's settled for now. Can we add an example to the writing guidelines maybe and close this issue for now?

**Comment by cbscribe** [comment]
Closing this as we're moving forward with the first suggestion. We can reopen discussion if significant VS changes occur.
