### ISSUE TITLE
Dodge the Creeps tutorial / touchscreen input / animations

### ISSUE THREAD

**Issue by daveTheOldCoder** [godotengine/godot-docs#5226]
Godot 3.3.3-stable

In the Dodge the Creeps tutorial, the instructions for modifying the code in Player.gd for touchscreen (or mouse) input omit a change that's needed to make the "walk" and "up" animations toggle based on the input.

Documentation page:
https://docs.godotengine.org/en/stable/getting_started/step_by_step/exporting.html#overview

Related discussion:
https://godotforums.org/discussion/27293/dodge-the-creeps-up-down-animations-not-working-with-touch-support

I created a Pull Request that fixes the issue:
https://github.com/daveTheOldCoder/godot-docs/pull/1

**Comment by Calinou** [comment]
Please open a pull request on this repository's `3.4` branch 🙂

**Comment by daveTheOldCoder** [comment]
Done. New PR: https://github.com/daveTheOldCoder/godot-docs/commit/060afb47654f091636aee3edcb5c20a44aefe8a9

**Comment by skyace65** [comment]
> Done. New PR: [daveTheOldCoder@060afb4](https://github.com/daveTheOldCoder/godot-docs/commit/060afb47654f091636aee3edcb5c20a44aefe8a9)

You can't make the PR for your fork of the godot-docs repository. In fact you should never do that because it causes issues. Have you done much work with Git before? We have a guide in the docs for how to use it to make pull requests for the doc and engine repository [here](https://docs.godotengine.org/en/stable/community/contributing/pr_workflow.html). If you have any questions feel free to ask.
