### ISSUE TITLE
Tutorial: 1st Person Shooter

### ISSUE THREAD

**Issue by cbscribe** [godotengine/godot-docs#538]
From the Aug Patreon poll.

Ideally, these tutorials should have written and video versions.

**Comment by MoraleMuffin5** [comment]
I am very glad that Patreon users (paid) get to decide on what gets added to the docs for a FLOSS project!

**Comment by TwistedTwigleg** [comment]
I've been wanting to make video tutorials for Godot for awhile now... Why not start here? Should be fun making an FPS and it'll give me some experience making tutorials :smile:

(If someone else is already working on this, please let me know. No reason to have two FPS tutorials in the documentation)

**Comment by TwistedTwigleg** [comment]
Alright, I've finished the project for part 1! (Phew!)

Now I'm ready to start writing the tutorial. A few things:
(NOTE: because they are rather wordy, I've split them using horizontal lines)
___
I've broken the tutorial down into several parts. Two parts for a beginner project that will serve as solid base to build a more complex FPS. I'm hoping to make it beginner friendly while also providing a base for more experienced Godot users.

Part 1 will be making the main scripts (the player, animation handling, firing the guns) with part 2 adding turrets, grenades, and polishing up some of the code for better usability (like making a pooling system for bullets, for example). I've finished the project for part 1, and I still need to make the project for part 2.
___
Ideally I'd like to make another set of tutorials for making a FPS with an IK system. This will allow for more dynamic animations inside the editor, and should make adding things like gun sway/recoil much easier. From what I've seen, it looks like most AAA games (Halo 4 and Halo Reach, Call of Duty, Destiny) use some form of IK to handle their FPS animations (so they don't have to animation a 3rd person model and a 1st person model).

It will likely be a more advance tutorial for more advance Godot users. Not sure if they should be added to the official documentation or not. I'll probably make the tutorial anyway (just because I find it interesting), but I'm curious to know if you guys would want a tutorial like that on the official documentation or not.

What do you guys think? (Of course, I cannot guarantee get it done in a timely manner, but I'd like to.)
___
How should I upload the video tutorial?

I plan on making the written tutorial first (which I still need to write 😅) and then making a video tutorial of the same, after that.

Will I need to give you guys the video so you can upload it to the official Godot Youtube channel? Should I upload it on my Youtube channel?
___
Should I also add the finished FPS project to the demo repository?

I plan on uploading it to my Github later (once I have the majority of the written tutorial finished) but I can also make a PR to add the finished project to the demo repository if you guys want.
___

I'm hoping to get both the written tutorial and the video tutorial for part 1 out by the end of February. I should have a PR for adding part one of the FPS tutorial out in a week or so (assuming everything works out 😄 ).

Part 2 will likely come out sometime in March (as I still need to code it, then write the tutorial, and then make the video tutorial)

**Comment by NathanLovato** [comment]
Great news!

> How should I upload the video tutorial?

Your channel and linking to it in the docs is fine. Right now the rule is no embed, only text links.

> Should I also add the finished FPS project to the demo repository?

Right now the companion demos for the tutorials are zipped in the files/ folder in any given category. Nothing prevents you from adding the final demo to the godot-demos repo.

**Comment by pwab** [comment]
> I'll probably make the tutorial anyway (just because I find it interesting), but I'm curious to know if you guys would want a tutorial like that on the official documentation or not.

Absolutly yes. I always read negative comments about the lack of tutorials in the godot docs and outdated stuff spread across multiple blogs. I would like to have all of them into one main repository (at this time the godot docs seem to be the best fit) so they can be version controlled and have the possibility to get issues filed.

> Should I also add the finished FPS project to the demo repository?

IMHO every project created in the docs should be added to the demo repository. In fact they are demos. Ideally it should be the other way around: Every demo could/should have a dedicated tutorial page that explains **why** things are done the way they are. This would help a lot of newcomers who are not familiar with reading other peoples code without getting an explanation in prosa form.

**Comment by TwistedTwigleg** [comment]
Thanks guys!

I'll start working on the written tutorial then, and later add the project to the demo repository.
(Once I have part 2 of this tutorial done I'll see about working on the IK FPS demo 😄 )
