### ISSUE TITLE
Cannot build scene with C# script

### ISSUE THREAD

**Issue by rifftual** [godotengine/godot-docs#5443]
**Your Godot version:** _v3.4.stable.mono.official [206ba70f4]_

**Issue description:**

The documentation says: _In summary, you must have installed .NET Core SDK and the Mono-enabled version of Godot._

I have tried both _dotnet-sdk-6.0_ and _dotnet-sdk-3.1_ but when I try to build my scene with a C# script I get the following error: _Cannot find binary 'MSBuild (Mono)'

BTW selecting _Edit on GitHub_ in the documentation site opens this page with 404: https://github.com/godotengine/godot-docs/blob/master/getting_started/scripting/c_sharp/c_sharp_basics.rst

**URL to the documentation page:** https://docs.godotengine.org/en/stable/getting_started/scripting/c_sharp/c_sharp_basics.html

**Comment by Calinou** [comment]
> BTW selecting Edit on GitHub in the documentation site opens this page with 404: master/getting_started/scripting/c_sharp/c_sharp_basics.rst

This is expected, as URLs have changed in the `master` branch but redirects can't be set up on GitHub. The URL reorganization was backported to the `3.4` branch, but it hasn't been merged on `stable` yet because redirects need to be set up first.

**Comment by raulsntos** [comment]
It seems you have not installed Mono (only the .NET SDK) and you need to install Mono too in order to use `MSBuild (Mono)` as build tool.

Alternatively you can change the build tool to `dotnet CLI` (which is the default and recommended build tool since at least 3.2).

The build tool can be configured in `Editor > Editor Settings... > Mono > Builds > Build Tool`.

**Comment by rifftual** [comment]
> It seems you have not installed Mono (only the .NET SDK) and you need to install Mono too in order to use `MSBuild (Mono)` as build tool.
> 
> Alternatively you can change the build tool to `dotnet CLI` (which is the default and recommended build tool since at least 3.2).
> 
> The build tool can be configured in `Editor > Editor Settings... > Mono > Builds > Build Tool`.

Ok, but the instructions don't say so?

**Comment by raulsntos** [comment]
Installing Mono used to be a requirement until support for the .NET SDK was implemented in 3.2.3 so the documentation says:

> From Godot 3.2.3 onwards, installing Mono SDK is not a requirement anymore, except it is required if you are building the engine from source.

The default Build Tool should automatically be set to `dotnet CLI` so there should be no need to install Mono, unless of course you change it to `MSBuild (Mono)` which given the name I think one can assume Mono needs to be installed.

Since the default is `dotnet CLI` and the documentation assumes you haven't changed this setting it doesn't specify that you might need to install Mono, though this could be more explicit.

---

I'm hesitant to change the documentation to recommend installing Mono since I'd prefer everyone moved to the .NET SDK, the `MSBuild (Mono)` Build Tool option will likely be removed in the future (4.0?) as this build tool tends to cause many issues.

**Comment by rifftual** [comment]
I haven't changed the defaults but when I click on the reset button in Editor settings, it is indeed set to dotnet cli and now the build works with only DotNet SDK installed.

**Comment by raulsntos** [comment]
If you didn't change it, did you perhaps use Godot before 3.2.3? Since the default was `MSBuild (Mono)` before then and therefore I think your settings will have been saved with that option selected.

**Comment by skyace65** [comment]
Can we consider this issue resolved? Or should we add a note about resetting editor settings if you used Godot before 3.2.3?

**Comment by rifftual** [comment]
> Can we consider this issue resolved? Or should we add a note about resetting editor settings if you used Godot before 3.2.3?

I'm pretty sure I have only installed Godot once. So maybe not a good idea to add that note if nobody else has had such problems.
