### ISSUE TITLE
We want to request getting our company added to Third-party support on consolesupport in Gadot documentation

### ISSUE THREAD

**Issue by Tyrionski** [godotengine/godot-docs#5925]
**Your Godot version:**
We would like our company to be added to Third-Party supported companies for porting 

**Issue description:**
We are Another Moon Games- a game studio that specializes in porting, co-development and QA services for other game studios for Switch, PC, Playstation, Xbox and mobile games (Android & IOS) . It would be great if we can be included as part of your providers for porting Gadot. Our developers recommended your engine as we are also able to port games based on your engine. Our website link: https://anothermoon.games/

PS: we are updating our website design layout to make it more professiona and intuitive. It should go live within the next 2 weeks. 

**URL to the documentation page (if already existing):**
https://docs.godotengine.org/en/stable/tutorials/platform/consoles.html?highlight=Console#third-party-support

**Comment by YuriSizov** [comment]
Hey, nice to hear that you're thinking about using Godot!

Do you already have experience porting Godot to other platforms? Because that's the tricky part for most game developers, the part that requires signing NDAs and integrating with proprietary SDKs and creating platform-specific code for low-level stuff. The list in the documentation is of companies that have a proven track record of integrating Godot with other platforms. It's not a list of companies experienced in creating ports of games.

**Comment by skyace65** [comment]
Closing this issue due to the lack of a response. If you would like to be featured on that page and do have experience porting Godot to other platforms you can open a pull request.
