### ISSUE TITLE
GDscript 2.0

### ISSUE THREAD

**Issue by yeet227** [godotengine/godot-docs#6190]
**Your Godot version:**
4.0 Beta 1
**Issue description:**
Adding Documentation for GDscript 2.0, I am fully aware that GDscript is constantly changing with the updates being added but it makes it hard to use the new versions without some kind of documentation to use it with to code in further functions with the functions being renamed and being unaware on how to use it
**URL to the documentation page (if already existing):**

**Comment by clayjohn** [comment]
Could you be more specific about what you think is missing? The GDScript docs have been continually updated since the creation of GDScript 2.0. The first GDScript 2.0 pages were added almost 2 years ago in https://github.com/godotengine/godot-docs/pull/4247.

The class reference is also kept in sync with master so if you are using beta 1 it should be up to date.

**Comment by yeet227** [comment]
Where is the GDscript 2.0 Docs because every time I search for it I keep getting 1.0

**Comment by clayjohn** [comment]
Here: https://docs.godotengine.org/en/latest/tutorials/scripting/gdscript/index.html

Note in the URL you can see that it says "latest" this indicates that it is for the unstable development branch (i.e. the beta). You can change the version you are reading with the menu in the lower left corner.

**Comment by yeet227** [comment]
I was not aware that, the latest was the updated I thought it was 3.5 not 4.0 so thanks for enlightening me with this
