### ISSUE TITLE
Provide examples for clarity on proper syntax

### ISSUE THREAD

**Issue by Tolly24** [godotengine/godot-docs#6209]
**Your Godot version:**
3.5
**Issue description:**
I'm learning Godot(came from Gamemaker Studio 2) and I love it and GDScript but what I'm always struggling with the docs is having examples of how to use anything in. There are pages with examples but not not consistently. As someone without programming knowledge beforehand. It's really hard to know how to use something properly when you don't have a background knowledge. That's what I loved about the docs in GMS2, there's a detailed explaination in text for everything and at the end there's always an example to show the proper syntax.
![image](https://user-images.githubusercontent.com/65282021/191503570-f4649e6c-d7a2-4159-aa57-bc976087d2fe.png)

**URL to the documentation page (if already existing):**

**Comment by Calinou** [comment]
Code samples are only added for methods whose usage is not trivial (for example, adding new items to a Tree, or making an HTTP request).

Calling one-liner methods should not have code samples to avoid bloating the class reference.

**Comment by tetrapod00** [comment]
I do sympathize with the desire to have code samples for more methods. But with the current structure of the class reference, I agree with Calinou here that not *every* method should have a code example.

I'm going to close this since the class reference, as a rule, currently does not require code samples for each method, and I don't think that is likely to change soon. However, if there are some specific functions that you think should be better documented with code samples, feel free to open up another issue to track that.

As a side note, some methods/operators *do* currently have code examples that are IMO pretty marginal inclusions, like https://docs.godotengine.org/en/4.3/classes/class_vector3.html#class-vector3-operator-sum-vector3. So the bar for inclusion of code examples is not that high. Again, if you feel that there are some methods that need more documentation, please feel free to open another issue with a list.
