### ISSUE TITLE
Add more information about Ubershader to ProjectSettings documentation

### ISSUE THREAD

**Issue by ztc0611** [godotengine/godot-docs#6217]
**Your Godot version:** 3.5.stable

**Issue description:** Upon launching the project after tweaking settings related to Asynchronous Shader Compilation with/without caching, the Editor can report the message `Async. shader compilation: OFF (enabled for project, but not supported)` on launch. There is no information about what this means or what platforms/types of hardware are supported in the docs. (Is it just Windows? Does it work on Intel MacOS but just not ARM Based M1 devices?) I presume this is a hardware issue that Godot can't change, but maybe this is not the case...? I've been trying to understand this for hours and it was even difficult to find the code in the engine that prints this message.

Updating this documentation with more information feels like it could avoid headaches for developers who expect this feature to "just work" because there are no specific warnings to cases where it will be disabled in the docs, besides for mobile and 2D projects. In general I think the "Ubershader"/Async Shader is really lacking in documentation currently, considering how major a feature it can be.

**URL to the documentation page (if already existing):** https://docs.godotengine.org/en/stable/classes/class_projectsettings.html?highlight=ubershader#class-projectsettings-property-rendering-gles3-shaders-shader-compilation-mode

**Comment by Calinou** [comment]
>  Does it work on Intel MacOS but just not ARM Based M1 devices?

Ubershaders require the `GL_PROGRAM_BINARY` extension to be supported. This is not available on HTML5 for instance, and it's not 

> I presume this is a hardware issue that Godot can't change, but maybe this is not the case...?

This is a hardware issue that won't change over time.

>  In general I think the "Ubershader"/Async Shader is really lacking in documentation currently, considering how major a feature it can be.

Unfortunately, I wouldn't expect too much from this feature. It's more of a bandaid than a real fix, due to OpenGL support being so spotty across platforms. In Godot, ubershaders didn't turn out to be as effective as we'd hope. The manual approach to shader caching (showing all objects for 1 frame at game start and ensuring they're not freed) will still give players a better experience, as it'll result in less stuttering and will work on all platforms.

For reference, UE4/5 also struggle with shader compilation stutter ([example](https://www.youtube.com/watch?v=FbFMafKzJyY)), and the manual Godot fix is also the best way to fix this in UE4/5.

**Comment by ztc0611** [comment]
> The manual approach to shader caching (showing all objects for 1 frame at game start and ensuring they're not freed) will still give players a better experience, as it'll result in no performance penalty while shaders are compiling in the background and will work on all platforms.

I've been trying to get this working for a few days now, and have had no luck. Is there any tutorial for the proper setup for this? I've put them all in an autoload, shown those objects with a camera for 10 frames, then swapped to the full scene (without unloading the autoload, all objects appear in the remote node list) and still the first copy of an object that appears in that autoload scene causes a shader lag spike.

**Comment by Calinou** [comment]
> Also, does Godot 4's Vulkan rendering fix this?

The Vulkan renderer features shader caching, but not ubershaders: https://github.com/godotengine/godot/issues/61233

**Comment by tinmanjuggernaut** [comment]
Both gd3 and gd4 stutter, even with caching, when there are a lot of assets. You need to force precompilation of shaders by showing the materials on screen, not the objects, behind a loading screen.

https://github.com/godotengine/godot/pull/53411#issuecomment-935537126

https://github.com/godotengine/godot/pull/46330#issuecomment-786280648

**Comment by akien-mga** [comment]
Fixed by https://github.com/godotengine/godot/pull/76321.
