### ISSUE TITLE
Be more specific about when deferred calls are executed (`call_deferred`, `queue_free`, ...)

### ISSUE THREAD

**Issue by 31** [godotengine/godot-docs#6488]
**Your Godot version:**
4.0 beta 8

**Issue description:**
The `call_deferred` doc says:

> Calls the method on the object during idle time.

It's not clear in the manual what "idle time" is, however. It's commonly assumed in the community that the deferral will happen at the start of the next frame, but that doesn't seem to be true when looking at the Godot source code. [scene_tree.cpp](https://github.com/godotengine/godot/blob/c7c561ffd5d0e46cd1db3dbb583c6ca3841ab894/scene/main/scene_tree.cpp) calls `MessageQueue::get_singleton()->flush();`, `_flush_delete_queue();`, and `_call_idle_callbacks();` at the end of `process` *and* at the end of `physics_process`.

This can be quite a puzzle to someone trying to run things in the right order. I think the doc should be more specific. I don't think I have a firm grasp on what the true intent is here, though, so I'm not sure if I can write it myself.

**URL to the documentation page (if already existing):**
https://docs.godotengine.org/en/latest/classes/class_object.html#class-object-method-call-deferred
Although perhaps this should be added to this page, and the classdoc could just link to it:
https://docs.godotengine.org/en/latest/tutorials/scripting/idle_and_physics_processing.html

**Comment by belzecue** [comment]
I'm attempting to correct this fairly common misunderstanding wherever I come across it on the web, e.g. [here](https://www.reddit.com/r/godot/comments/gbqee7/comment/j2mx88f/?utm_source=reddit&utm_medium=web2x&context=3).  For a long time, I too [assumed it meant "next frame"](https://www.reddit.com/r/godot/comments/uk7kzz/call_deferred_is_for_idle_frames_but_why_not_also/) due to things I'd read on the web outside of the official documentation, plus my conflation of "idle frame," "idle time", and _process.

I very much support an additional sentence in the doco pages (online and in-engine) for call_deferred and set_deferred, stating something like:

"The deferred action will execute in the current frame during idle time _after_ _process and _physics_process finish."
