### ISSUE TITLE
Singletons (Auto-Load) Example Project May Have a Bug

### ISSUE THREAD

**Issue by wangaustin** [godotengine/godot-docs#6540]
**Your Godot version:**
v3.5.1.stable.official [6fed1ffa3]

**Issue description:**
I downloaded autoload.zip provided and followed the tutorial step by step. Once all scripts are finished, I encountered the following error:

`
emit_signal: Error calling method from signal 'pressed': 'Control::_on_Button_pressed': Method not found..
`

I realized that the scripts may not have been attached to their respective scenes. So I attached Scene1.gd to Scene1's root node and attach Scene2.gd to Scene2's root node. Then, I reconnected the pressed() signals to their respective scripts. These steps fixed the error.

I opened a [PR](https://github.com/godotengine/godot-docs/pull/6506), but the reviewer said it should be reported as an issue instead.

**URL to the documentation page:**
https://docs.godotengine.org/en/stable/tutorials/scripting/singletons_autoload.html

**Comment by Piralein** [comment]
I downloaded the project, the scripts and signals are attached correctly and work with the tutorial.
Could you recreate the project with the zip and check again on your end? Maybe you disconnected the script on accident.

**Comment by Piralein** [comment]
Closing due to no response.
I rechecked the files in the [project-starters repository](https://github.com/godotengine/godot-docs-project-starters), the connected signal and script assignment looks correct.
[Scene1.tscn](https://github.com/godotengine/godot-docs-project-starters/blob/3.x/src/singleton_autoload_starter/Scene1.tscn), [Scene1.gd](https://github.com/godotengine/godot-docs-project-starters/blob/3.x/src/singleton_autoload_starter/Scene1.gd)

If you encounter this problem with the provided project again, please create a new issue or reopen this issue.
Thank you for the report.
