### ISSUE TITLE
What do draw passes mean in GPUParticles3D?

### ISSUE THREAD

**Issue by jmdejong** [godotengine/godot-docs#6605]
The GPUParticles3D node can have up to 4 draw passes (and associated meshes) for its particles.
I can not find in the documentation what these draw passes are actually doing and when/why you'd need more than one.

By trying to set 2 draw passes with different meshes it I just saw both meshes drawn at the same location. 

https://docs.godotengine.org/en/latest/classes/class_gpuparticles3d.html

**Comment by Calinou** [comment]
Having multiple draw passes is useful if you want several meshes to display for each particle.

**Comment by jmdejong** [comment]
What makes it more useful when using custom particle shaders?  Do they have a way to differentiate between the different meshes?

**Comment by clayjohn** [comment]
Draw passes are meshes that are used to draw the particle. 

They are useful as they allow you to have multiple meshes receive data from the same particle. For VFX this is used often as you may have ovelapping effects that should follow the same particle. 

Imagine a magic spell that has multiple components, i.e. an energy beam, a bright glow-y aura, swirls of color around the beam etc. You can use draw passes so that each component has its own mesh and material but they all follow the same particle

**Comment by jmdejong** [comment]
Do we have a good place to put this information in the documentation?

**Comment by Calinou** [comment]
There's a pull request adding 3D particles documentation: https://github.com/godotengine/godot-docs/pull/5535

**Comment by Calinou** [comment]
This is now documented here: https://docs.godotengine.org/en/latest/tutorials/3d/particles/creating_a_3d_particle_system.html#draw-passes

**Comment by Mohammad9760** [comment]
is there a way I can access the different draw passes in a particle shader?
eg: I want to create moths, each moth is a particle, each wing is a quad that I rotate around a pivot using a sine wave.
how can I process each draw pass separately so that in the particle shader's process function I could give them the same position and movement, but rotate each wing differently.
