### ISSUE TITLE
Outdated minimal example in websocket page

### ISSUE THREAD

**Issue by f8122dac91** [godotengine/godot-docs#6631]
**Your Godot version:** 4.0 beta 13

**Issue description:** Minimal example in main websocket page is outdated.

**URL to the documentation page:** https://docs.godotengine.org/en/stable/tutorials/networking/websocket.html?highlight=websocket#minimal-client-example

**Comment by magikmw** [comment]
@f8122dac91 How far outdated? I see you linked to stable docs, the latest page has different code (haven't checked if it runs yet).

**Comment by f8122dac91** [comment]
> @f8122dac91 How far outdated? I see you linked to stable docs, the latest page has different code (haven't checked if it runs yet).

Oops, yeah I did linked the stable docs didn't I?

But the latest page here is still outdated: https://docs.godotengine.org/en/latest/tutorials/networking/websocket.html#minimal-client-example
For one, it's using old export syntax, for example.

**Comment by hgouveia** [comment]
I  encounter the same issue in https://docs.godotengine.org/en/stable/tutorials/networking/websocket.html , for stable 4.0, where all example are still referring to `WebSocketClient` instead of the ` WebSocketPeer` 

an update documentation example is available on : https://github.com/godotengine/godot/blob/0a0132ccf40b14d2ca8987193b3b07a5fe03a674/modules/websocket/doc_classes/WebSocketPeer.xml

**Comment by aGuyWhoMadeGames** [comment]
It seems like the websocket server referenced in the code snippet doesn't work. I'm working on a PR to fix this, but trying to connect to `wss://libwebsockets.org` just gives a generic cannot connect error.
