### ISSUE TITLE
Shader tutorial outdated info

### ISSUE THREAD

**Issue by MagmaGuy** [godotengine/godot-docs#6724]
**Your Godot version:**
Godot 4 beta 11 mono edition

**Issue description:**
This passage:
> "Notice how there is already error? This is because the shader editor reloads shaders on the fly. The first thing Godot shaders need is a declaration of what type of shader they are. We set the variable shader_type to spatial because this is a spatial shader."

Is not accurate in the current Godot version. In the current version, new shaders initialize with the following contents:

```c#
shader_type spatial;

void fragment() {
	// Place fragment code here.
}

```

**URL to the documentation page:**
https://docs.godotengine.org/en/latest/tutorials/shaders/your_first_shader/your_first_3d_shader.html

**Comment by Mishari713** [comment]
Will the change be done in this [file](https://github.com/godotengine/godot-docs/blob/master/tutorials/shaders/your_first_shader/your_first_3d_shader.rst)
or is there an XML that we should change?

**Comment by paddy-exe** [comment]
@Mishari713 The outdated info is that that the shader compiler will throw an error immediately after opening the shader editor. This doesn't happen in 4.0 anymore since it automatically fills the contents of a new shader with a "working" shader (which doesn't do anything). This should be changed in the docs (seems to be the file you mentioned)
