### ISSUE TITLE
2D Navigation Overview Uses Potentially Problematic Logic In Demo Code

### ISSUE THREAD

**Issue by azterior** [godotengine/godot-docs#6776]
**Your Godot version:**
4.0 Latest Docs

**Issue description:**
Having a return statement at the start of a function prevents it from being expanded and would require the user to implement the same change I suggest below in order to expand the script. This removes an unnecessary step a new user may struggle with.

```gdscript
func _physics_process(delta):

    if navigation_agent.is_target_reached():

        return

    ...
```

this logic should be replaced with 

```gdscript
func _physics_process(delta):

    if not navigation_agent.is_target_reached():

        ...
```

Apologies for any issues in this reques, this is my first.

**URL to the documentation page (if already existing):**
https://docs.godotengine.org/en/latest/tutorials/navigation/navigation_introduction_2d.html

**Comment by Calinou** [comment]
PS: Code blocks should use triple backticks like this (with an optional language name for syntax highlighting):

\`\`\`gdscript
code here
\`\`\`

I edited your post accordingly, but remember to do this in the future :slightly_smiling_face:

**Comment by smix8** [comment]
In fact all the agent script examples should properly have a `is_navigation_finished()` check and return instead of `is_target_reached()` which is unreliable as it only checks the distance to the final target compared to `is_navigation_finished()` that actually checks if the loaded path array was processed to the end.

```gdscript
func _physics_process(delta):
    if navigation_agent.is_navigation_finished():
        return
```

It is a common beginner problem to always process path following even while the navigation ended and this can cause some jitter when agents should stand in place, especially in 2D that uses a large scale and has more precision problems compared to 3D.

**Comment by skyace65** [comment]
Closing this issue per Calinou's explanation on why the scripts are like this, and the changes in #6780.
