### ISSUE TITLE
a place for contibuted useful GDScripts to copy paste and personalize

### ISSUE THREAD

**Issue by vsrinu26f** [godotengine/godot-docs#68]

**Comment by StraToN** [comment]
I guess this will not be part of the documentation, but included in the approaching Assets Sharing platform. The reason is that, IMO, if we include only a few "useful" scripts, we shall include ALL of them which are found "useful". 

I see 2 problems : 
- "Useful" is a subjective notion. What is useful to me may not be useful to you, and the inverse. The risk is to have a bloated section.
- Hard to manage ! See nex paragraph.

"Useful" scripts will emerge every day, for multiple topics. Every author could thus propose his script in the documentation, which would then become a scripts repository. This is not documentation's purpose. And on the contrary, while a LOT of scripts may emerge, it is possible that no one cares about inserting them in the documentation (if we ever decide to manage them) and then we would be missing a lot of interesting scripts.

So, instead of having to manage them in the documentation, I propose to let them be contributed in the Asset Sharing platform, which is made for that.

**Comment by akien-mga** [comment]
I fully agree with @StraToN.
