### ISSUE TITLE
Singletons (Autoload) page seems to be wrong for C#

### ISSUE THREAD

**Issue by BigZaphod** [godotengine/godot-docs#6981]
**Your Godot version:**
v4.0.stable.mono.official [92bee43ad]

**Issue description:**
I've been assured by my own attempts (and by folks on Discord) that accessing a GDScript Autoload from C# doesn't work quite the way the C# samples on the Autoload page seem to suggest for Godot 4 because the "Global Variable" checkbox in Godot doesn't apparently apply to C#.

I don't know if it worked this way in Godot 3.x or not, though, so it's possible the real issue is incomplete C# support in Godot 4?

For example, this C# sample shown on the page:
```
var playerVariables = GetNode<PlayerVariables>("/root/PlayerVariables");
playerVariables.Health -= 10; // Instance field.
```

That code seems to suggest that a type named `PlayerVariables` should exist in my C# code that was presumably autogenerated by Godot. The screenshot above this example clearly shows "PlayerVariables" is an autoload of a *GDScript*, but that doesn't seem to make any names exist over on the C# side. As far as I can tell, named classes in GDScript don't show up as types in C# so using `GetNode<PlayerVariables>()` can't possibly work. It'd be super handy if they did (and maybe they did in 3.X?) but they don't at the moment, anyway, as far as I can tell. Unless I'm doing something wrong.

The next C# sample also seems impossible for those same reasons:

```
// Static members can be accessed by using the class name.
PlayerVariables.Health -= 10;
```

I have no idea at this point if this documentation is just totally wrong and made up of wishful thinking, or if it used to work and now doesn't! I do wish it worked, though, and if it's supposed to work, I'd love to know what the heck I'm doing wrong. 😛

**URL to the documentation page:**
https://docs.godotengine.org/en/latest/tutorials/scripting/singletons_autoload.html

**Comment by raulsntos** [comment]
The documentation is mainly written with GDScript in mind, excerpts of code are often translated to C# but the rest of the documentation (text and images) can't be changed.

You are looking at the documentation page for _Singletons (Autoload)_, assuming you are using GDScript the image describes how to add a GDScript to the list of autoloads and then the code to retrieve it.

The code to retrieve an autoload is also provided in C#, this code assumes the autoload is also implemented in C#. However, the image still shows GDScript because images can't be changed based on the selected language.

> I've been assured by my own attempts (and by folks on Discord) that accessing a GDScript Autoload from C# doesn't work quite the way the C# samples on the Autoload page seem to suggest for Godot 4 [...]

This documentation page is not meant to show how to access GDScript autoloads from C#, it's just about accessing autoloads in general (usually in the same language, no interop, since most users use only one language for their whole project).

> That code seems to suggest that a type named `PlayerVariables` should exist in my C# code [...]

That's correct, the documentation page assumes your autoload is also implemented in C#. Pretend that the image shows a path to the .cs file that defines the `PlayerVariables` type.

> As far as I can tell, named classes in GDScript don't show up as types in C# so using `GetNode<PlayerVariables>()` can't possibly work.

Also correct, GDScript types are not available as C# types. This is also true for 3.x. To access GDScript instances from C#, use a less-specific type such as `Godot.Node` or `Godot.Resource`. For more information about how to interop between GDScript and C# see the [_Cross-language scripting_](https://docs.godotengine.org/en/stable/tutorials/scripting/cross_language_scripting.html) documentation page.

**Comment by skyace65** [comment]
The issues with the C# code on this part of the page have been fixed over several PRs. The first C# example you mentioned with ``GetNode`` was removed in #8900. And the health example was removed in #7604 and replaced in #8852.
