### ISSUE TITLE
Export in c# not work

### ISSUE THREAD

**Issue by 0xNunoMiranda** [godotengine/godot-docs#7014]
I try to make a simple example with c# but for example, when I use [Export] and click 'Build', nothing happens.
I don´t see it in the inspector.

Thanks for your attention.
Anyway, Good Work!

**Comment by raulsntos** [comment]
I'm not sure what this issue is reporting. Are you saying some documentation page is not clear enough about how to use `[Export]` attributes? If so, please include a link to the documentation page.

Also, can you expand on what you mean by _nothing happens_. Do you not see a popup like this?

![image](https://github.com/godotengine/godot-docs/assets/3903059/f2bb3c3b-b876-4096-9ac8-2f3fc889a439)

And what does the output say in the MSBuild panel in the bottom dock?

![image](https://github.com/godotengine/godot-docs/assets/3903059/33f99466-904b-4634-b467-4f9c9c197254)

Also, it seems you didn't fill the issue template. Could you specify the Godot version that you are using?

**Comment by raulsntos** [comment]
Closing due to lack of response.
