### ISSUE TITLE
InputEvent doesn't list every type that inherits it

### ISSUE THREAD

**Issue by IfgiU** [godotengine/godot-docs#7114]
Hi!
[InputEvent](https://docs.godotengine.org/en/stable/classes/class_inputevent.html) doesn't list every type that inherits it, for example [InputEventMouseAction](https://docs.godotengine.org/en/stable/classes/class_inputeventmousemotion.html) isn't listed in "inherited by" on the InputEvent page but says it inherits InputEvent on its own page. I noticed that because I wanted to find a suitable InputEvent for my case. Or is there maybe somewhere else a list with all of the objects?

**Comment by Maran23** [comment]
That is because in general the `Inherited By` section only lists classes that directly inherits the given class.
The inheritance chain of `InputEventMouseMotion` is: 
`InputEventMouseMotion` < `InputEventMouse` < `InputEventWithModifiers` < `InputEventFromWindow` < `InputEvent`
So `InputEventMouseMotion` is not directly inheriting from `InputEvent`, therefore not inside the list.

Note that you also wrote `InputEventMouseAction`, while you probably mean `InputEventMouseMotion`.

**Comment by skyace65** [comment]
Closing per Maran23s comment.
