### ISSUE TITLE
Info whether article is outdated should be color coded

### ISSUE THREAD

**Issue by Foxysen** [godotengine/godot-docs#7196]
**Your Godot version:**
4.0.2

**Issue description:**
I am currently re-reading documentation. I have expectation that this is a good intended time to do so, now that 4.0 is not in beta anymore and had a big release party. 
Having read many pages that were up to 4.0 version, I stopped paying attention to the "work in progress" section. A human thing. It took me a while to notice that something was strange in one of the articles and scroll to the beginning.

I suggest that any "this article is outdated" info section be colored yellow. Green if up to date. 

**URL to the documentation page (if already existing):**
"Work in Progress" section on https://docs.godotengine.org/en/stable/about/troubleshooting.html as an example

**Comment by YuriSizov** [comment]
I think the reason I made it one color was because it makes it stand out more. We rarely use green notes in the docs, but we do use other colors, especially notes and warnings, quite a lot.

**Comment by Foxysen** [comment]
Ah. I read every yellow warning section on docs. They all say unique thing on each page.

The text for article being up to date has text repeat on each page. Obviously my brain gets lazy and finds a shortcut of merely skimming. Version where text is not up to date looks similar, so easy to miss in this mode. Color coding or making visual icons for both version would do wonders.

Though I just saw that the text in these sections just got shortened to one / two lines, so it's easier to notice difference in bold text placement.

So guess it's fine enough now. Could use those tho. But not a hill I would die on.

**Comment by Twads9816** [comment]
I have to agree with @Foxysen here. I just ran into this issue while looking at the audio docs. It didn't take me too long to notice because the longer "Work in progress" message wraps to a second line, but now I'm always going to be second-guessing myself and rereading the header to make sure the doc is up to date. I think using yellow makes a lot of sense because it's the ubiquitous "warning" color, and the "Work in progress" message is a warning that the page may or may be up-to-date. Green is universally the "all good no problems" color, and I think many people, like myself, are likely to miss the "Work in progress" message because of this, especially because the "Up to date" message looks _so_ similar, and _every_ page has a green message at the top. It think it's important that the "Work in progress" message draws the user's attention.

**Comment by tetrapod00** [comment]
I agree! I made a PR: https://github.com/godotengine/godot-docs/pull/10411.
