### ISSUE TITLE
Godot 4 Array Methods .Erase() vs .Remove()

### ISSUE THREAD

**Issue by VestedGrammar** [godotengine/godot-docs#7364]
**Your Godot version:**
v4.0.stable.mono.official [92bee43ad]
**Issue description:**

The manual page for Godot.Collections.Array class has issues with C# support for various methods lists.

The noteworthy examples is erase (Variant value), which in the C# would be array.Erase(Variant value). Using Erase() returns an error while using Remove() behaves as erase(), and RemoveAt() works normally. If the Erase/Remove method naming has been changed, the manual needs to be updated to reflect this. 

There are a few other Methods on the Array class that struggle in C# (for example the sort_custom (Callable func) has a code snippet which for C# just says "here is no custom sort support".

The hope is that when eventually doing a pull request to update C# support on the Array class manual page to address the Remove() issue, we could also address some of the other support issues. I will be  messing around with the Array class in C# and commenting when I find explicit problems with the page in this issue.

**URL to the documentation page:**

https://docs.godotengine.org/en/stable/classes/class_array.html

If you know how to fix the issue you are reporting please
consider opening a pull request. We provide a tutorial on
using git here: https://docs.godotengine.org/en/stable/community/contributing/pr_workflow.html,
writing documentation at https://docs.godotengine.org/en/stable/community/contributing/docs_writing_guidelines.html
and contributing to the class reference here: https://docs.godotengine.org/en/stable/community/contributing/updating_the_class_reference.html

**Comment by VestedGrammar** [comment]
label:topic:dotnet

**Comment by raulsntos** [comment]
Godot arrays in C# follow the .NET collections more closely than the GDScript API in order to be more idiomatic and fulfill the expectations of .NET developers. The differences in the C# API is documented in https://docs.godotengine.org/en/stable/tutorials/scripting/c_sharp/c_sharp_collections.html#doc-c-sharp-collections-array.

The class reference documents the Core API which matches the GDScript API. As such, the method to remove an element from an array is `Array.erase`. But, as explained earlier, the C# API follows .NET collections so it doesn't implement `Array.Erase`, instead it implements `Array.Remove` like every other .NET collection (e.g.: [`List.Remove`](https://learn.microsoft.com/en-us/dotnet/api/system.collections.generic.list-1.remove)).

Other methods, such as the ones that end with `_custom` are not implemented in favor of using existing .NET APIs. In this case [LINQ](https://learn.microsoft.com/en-us/dotnet/standard/linq/) already supports the same APIs and would be more familiar to .NET developers.

**Comment by VestedGrammar** [comment]
That certainly explains my confusion. I think it would be prudent to direct people on the Godot.Collections.Array page to the C# collections page with an explanation.
