### ISSUE TITLE
Instructions about how to setup export templates are misleading

### ISSUE THREAD

**Issue by akien-mga** [godotengine/godot-docs#74]
See http://docs.godotengine.org/en/latest/tutorials/asset_pipeline/exporting_projects.html#export-dialog

A user on Facebook assumed that the end of this section meant that he had to look for the export templates on the wiki.

**Comment by pwab** [comment]
Well I am not sure what changed since this issue was created but I don't think that the docs are misleading here. The docs are quite clear (now):

- If you want to export something follow the guide at [Exporting projects](http://docs.godotengine.org/en/latest/learning/workflow/export/exporting_projects.html).
- If you want to create your own export templates follow the [buildsystem guide](http://docs.godotengine.org/en/latest/development/compiling/introduction_to_the_buildsystem.html#export-templates)

... Still the whole export docs need a revision as stated in #963. _(Hmm is #963 a duplicate then?)_
