### ISSUE TITLE
Warning for NavigationMeshInstance adding navmesh to tree as MeshInstance node

### ISSUE THREAD

**Issue by mackatap** [godotengine/godot-docs#7534]
**Your Godot version:**
3.6

**Issue description:**
NavigationMeshInstance has a NavigationMesh resource which can be set in the editor.  The documentation does not state that this NavigationMesh is added to the tree as a MeshInstance node.  This MeshInstance can be accidentally queue_free()'d which causes the game to crash when attempting to bake the navmesh.  The documentation should have a warning that the navmesh is added to the tree as a MeshInstance. There should probably also be a way to easily reference that new node, but a warning would be a good start.
**URL to the documentation page (if already existing):**
https://docs.godotengine.org/en/3.6/classes/class_navigationmeshinstance.html

**Comment by smix8** [comment]
If you delete the last object that holds a reference to a Resource, in this case the NavigationMeshInstance Node the NavigationMesh Resource, the Resource gets deleted because nothing is using it anymore. If you do not want that you need to keep a reference to the NavigationMesh alive somewhere, e.g. stored into a persistent variable.

I don't think this requires an explicit warning because that is how the Godot Resource system works.
Every Resources is affected by it the same way, not just the NavigationMesh Resource.

**Comment by skyace65** [comment]
Closing due to a lack of followup information. If you respond to smix8s comment I'll re-open it.
