### ISSUE TITLE
Using NavigationLinks page is misleading

### ISSUE THREAD

**Issue by razcore-rad** [godotengine/godot-docs#7598]
**Your Godot version:**
v4.1.rc2.official.46424488e

**Issue description:**

All this info at the bottom of the page seems incorrect.
![image](https://github.com/godotengine/godot-docs/assets/1177508/81ddce1f-979d-462f-82ad-eb2533bbbd01)

What happens is the `NavigationLink*` nodes seem to provide a valid navigation path that the AI can traverse just fine.

**URL to the documentation page:**
https://docs.godotengine.org/en/stable/tutorials/navigation/navigation_using_navigationlinks.html

I don't know if I checked enough edge cases, but from my tests `NavigationLink*` nodes enable the AI to traverse using its own path strategy without the need to manually move the agents with animation or teleportation or any other way.

Here's a small demo showing how the navigation agent moves from island to island using `NavigationLink2D`.

https://github.com/godotengine/godot-docs/assets/1177508/9883f562-dd49-4b6d-98c4-9c00b5e67772

*Note* that in the latter half I'm trying to get the agent to move to the edge of the island by giving it unreachable targets and it doesn't do what I expect it to do. Some times it moves to the edge and others it does't. Seems to be dependent on the distance to the navigation region, but on the convex one to the right it goes to incorrect placements. I think this is related to https://github.com/godotengine/godot/issues/78943

[godot-4-dbg.zip](https://github.com/godotengine/godot-docs/files/11929479/godot-4-dbg.zip)

**Comment by smix8** [comment]
As mentioned in the linked issue there are a multitude of reasons why a navigation link need to be supported by a script or something else that facilitates the movement of agents through the positions. It will break quickly outside of very simplistic test cases and make agent move and act weird on path or map resets.

Moving an agent directly between link positions is also not very usable in a real project. The entire reason to use a navigation link in the first place is because there is no navigation mesh possible in that place and therefor no safe straight-line movement.

**Comment by razcore-rad** [comment]
Now that we fixed the bug with the closest-point-to-target-position outside of the navigation region I'll think about a way to explain navigation links cause I think for now it's confusing without not knowing the implementation details.
