### ISSUE TITLE
JSON Page is out of date with version in this reposititory

### ISSUE THREAD

**Issue by ValorZard** [godotengine/godot-docs#7608]
**Your Godot version:**
4.0.3
**Issue description:**
the current docs available on the website forget to mention you need to create a JSON object in order to parse JSON data. The version of the docs in the repository has that fixed.
**URL to the documentation page:**
https://docs.godotengine.org/en/stable/classes/class_json.html
If you know how to fix the issue you are reporting please
consider opening a pull request. We provide a tutorial on
using git here: https://docs.godotengine.org/en/stable/community/contributing/pr_workflow.html,
writing documentation at https://docs.godotengine.org/en/stable/community/contributing/docs_writing_guidelines.html
and contributing to the class reference here: https://docs.godotengine.org/en/stable/community/contributing/updating_the_class_reference.html

**Comment by raulsntos** [comment]
You linked to the `stable` documentation which is the documentation for Godot 4.0. When you say this is fixed in the repository, you are probably referring to the `master` branch. The `master` branch contains the documentation for the next Godot version, this documentation is under [`latest`](https://docs.godotengine.org/en/latest/classes/class_json.html).

The documentation page you linked is class reference documentation which is generated from the XML files in the [Godot engine repository](https://github.com/godotengine/godot)[^1].

This seems to be the PR that fixed the issue:
- https://github.com/godotengine/godot/pull/78541.

When 4.1 is released, the `stable` documentation will be the documentation for Godot 4.1 and will include this fix. Since the PR contains the `cherrypick:4.0` label, it will also be backported to the [`4.0`](https://docs.godotengine.org/en/4.0/classes/class_json.html) documentation eventually.

Since this issue is already fixed, I will close the issue.

[^1]: The XML documentation for the JSON class: https://github.com/godotengine/godot/blob/cdd2313ba27d0a2600a18e849b4c5d1fd6a6e351/doc/classes/JSON.xml
