### ISSUE TITLE
character respawn problem

### ISSUE THREAD

**Issue by supep3s** [godotengine/godot-docs#7657]
![Безымянный1](https://github.com/godotengine/godot-docs/assets/139386878/6188d03e-341f-45b0-b654-b44d417fef61)

I followed all the steps in the godot documentation for creating the first game, but the code doesn't work and throws this error.

**Comment by AThousandShips** [comment]
Please provide more information on your code, you are not showing all the code and it's unclear what might be wrong, it's impossible to tell if you've followed all instructions

**Comment by skyace65** [comment]
Closing this because it's been over 2 months with no additional information.

supep3s if you can provide your code in a zip project I'd be happy to take a look and re-open this if there's an actual problem with the docs. Based on the error you're getting I suggest you check that ``func start`` is spelled correctly in your player.gd file.
