### ISSUE TITLE
Document creating texture-based sky shaders by extending PanoramaSkyMaterial

### ISSUE THREAD

**Issue by Calinou** [godotengine/godot-docs#7773]
**Your Godot version:** 4.1.1

**Issue description:** We should document creating texture-based sky shaders by extending PanoramaSkyMaterial. This can be used to create texture-based sky shaders, which can be faster than per-pixel sky shaders while also relying on compute shaders. See https://github.com/godotengine/godot/pull/80192.

**URL to the documentation page (if already existing):** https://docs.godotengine.org/en/latest/tutorials/shaders/shader_reference/sky_shader.html

**Comment by clayjohn** [comment]
I'm not sure this is something that should be the subject of documentation. The linked PR is a hack to work around what the author thought was a lack of a built in feature (namely TextureRD). Since we have a textureRD resource, we can arbitrarily write to textures from a compute shader and display them using a PanoramaSky material. There is absolutely no need to extend PanoramaSkyMaterial
