### ISSUE TITLE
GoDot Docs include links to non-free non-open source software

### ISSUE THREAD

**Issue by duaneking** [godotengine/godot-docs#7804]
**Your Godot version:**
Current docs

**Issue description:**
The official docs link to "RPG in a box" that is not open source and that violates GoDot's stated ethos; You cant learn from it, you cant see the code, so why is it being linked to if it cant help the user learn godot? Its nothing less than an advertisement and that makes it spam imho.

**URL to the documentation page:**
https://github.com/godotengine/godot-docs/blob/4.1/getting_started/introduction/introduction_to_godot.rst

This seems like a big enough issue that my fixing it with a PR would only be part of the solution; the bigger issue is why are non-open source stuff in the docs when it explicitly violates the stated Ethos of GoDot?

**Comment by clayjohn** [comment]
Hi! 

As a game engine, most applications made with Godot are neither free nor open source (as games tend to be neither free nor open source). As a project, we have no issue with that. We are a free and open source game engine, not a "game engine exclusively for free and open source games". 

In fact, we chose to use the MIT licence so that our users would be free to license their products as they see fit. 

The docs typically lean towards highlighting resources for learning which are also free and open source. That being said, the particular section you link to is not pointing out further resources, it is highlighting cool projects made by the community! I don't see any reason why would only highlight free and open source games in this space. On that note, we also link to the showcase which includes free and non-fres games. 

Since the purpose of the section is to highlight what you can do with Godot. I think it would be a disservice to readers to only showcase free and open source projects, as it risks communicating that Godot is an engine for free and open source projects only.

**Comment by skyace65** [comment]
Closing due to support of clayjohn's comment
