### ISSUE TITLE
Add SneakyBox to the porting service provider list

### ISSUE THREAD

**Issue by AlgimaSB** [godotengine/godot-docs#7908]
Please add SneakyBox to porting service provider list. 

SneakyBox offers porting services for PlayStation 4, PlayStation 5, Xbox One, Xbox Series X|S, Nintendo Switch, various PC platforms and mobile. 
https://sneakybox.biz/

**Comment by YuriSizov** [comment]
Hey! You can simply open a PR if you think it should be added 🙂 

That said, we prefer to keep this list in the docs to the companies that have a track record porting Godot titles, since we are sending Godot developers their way. I can't tell from the website if you've worked with Godot before, or if you are only planning to do so. Do you have any Godot titles in the portfolio or currently in works?

**Comment by AlgimaSB** [comment]
> Hey! You can simply open a PR if you think it should be added 🙂
> 
> That said, we prefer to keep this list in the docs to the companies that have a track record porting Godot titles, since we are sending Godot developers their way. I can't tell from the website if you've worked with Godot before, or if you are only planning to do so. Do you have any Godot titles in the portfolio or currently in works?

Thank you. I will open a PR. Currently, we are in the works a title that has not yet been announced. However, we hope to work on more titles built using Godot in the future.

**Comment by AThousandShips** [comment]
Then notify here or on the PR when it is official, and some portfolio is available and it can be reviewed

**Comment by skyace65** [comment]
Closing this issue due to the lack of a response in the PR.
