### ISSUE TITLE
C# EditorPlugins for Godot 4.1 don't work

### ISSUE THREAD

**Issue by a2937** [godotengine/godot-docs#7937]
**Your Godot version:** 4.1-mono

**Issue description:**

I was trying to follow the tutorial with a minimum example, yet even by creating a new empty plugin didn't help things. I think it's possible that we can't use C# with it right now. 

**URL to the documentation page:** https://docs.godotengine.org/en/stable/tutorials/plugins/editor/making_plugins.html

If you know how to fix the issue you are reporting please
consider opening a pull request. We provide a tutorial on
using git here: https://docs.godotengine.org/en/stable/community/contributing/pr_workflow.html,
writing documentation at https://docs.godotengine.org/en/stable/community/contributing/docs_writing_guidelines.html
and contributing to the class reference here: https://docs.godotengine.org/en/stable/community/contributing/updating_the_class_reference.html

![Unable to load](https://github.com/godotengine/godot-docs/assets/9373245/bb8e0c68-5b83-4c30-bfa3-35fbb452b16d)

**Comment by raulsntos** [comment]
Making Editor plugins in C# is supported and should work in any 4.x version. Since C# is a compiled language, the project must be built before the plugin can be activated, there's a warning about this in page you linked:

![image](https://github.com/godotengine/godot-docs/assets/3903059/6043425f-be78-459b-a3cd-c35f82e2f20e)

**Comment by a2937** [comment]
Okay I'm just blind.
