### ISSUE TITLE
Update Godot 3.0 FPS tutorial to 4.1

### ISSUE THREAD

**Issue by IndustryStandrd** [godotengine/godot-docs#7946]
Godot 4.1

So Godot 3.0 has a tutorial that is definitely out of date across the board https://docs.godotengine.org/en/3.0/tutorials/3d/fps_tutorial/index.html

Could we get a tutorial for Godot 4.0 that follows a similar structure as the "Your first 2D/3D Game" tutorials?

**Comment by skyace65** [comment]
The short answer is no. a few years ago the docs stopped doing game specific tutorials to focus on manual style information.

The long answer is that tutorial was removed because the amount of time and effort required to maintain game specific tutorials and keep them up to date is huge, and that time and effort is better spent on manual pages applicable to many different types of games.

The first 2D and 3D games are exceptions to the rule and still exist in the docs because they're meant to introduce newcomers to how the engine works. Additionally the community is better served finding game specific tutorials on places like youtube, and that's one of the reasons we link to youtube channels in the docs.

**Comment by IndustryStandrd** [comment]
I don't disagree with the priorities and fully believe we should be focusing on the core documentation. But the reality seems to be that a lot of the community YouTube videos are either out of date as well or teach bad design practices for Godot specifically. 

I won't name/shame anyone but I've seen a very popular tutorial series that make 0 use of Godots signals which to me would be important for taking advantage of Godots workflow. A 3D series I watched last night about putting a world together disappointingly made 0 use of multimesh3D or a 3D tilemap which is best practice and way more performant. How would new people to Godot know of these things?

I understand the situation with not having enough contributors for the documentation to please everyone, but directing people to the community that not just won't always have answers but will even have the wrong answer is concerning. At the very least it feels like once the main docs are updated and the dust settles after new releases that it wouldn't hurt to have some of the tutorial ones updated, even if that's months later.
