### ISSUE TITLE
C# docs give invalid advice

### ISSUE THREAD

**Issue by devingoble** [godotengine/godot-docs#8007]
**Your Godot version:**
4.1.1
**Issue description:**
The code comment on one of the snippets is very strange.

> // Note: Normally it is best to use explicit types rather than the `var`
    // keyword. However, var is acceptable to use here because the types are
    // obviously Mob and PathFollow2D, since they appear later on the line.

This is not, and never has been, valid advice for c#. `var` is not a runtime construct. The type inference only happens at design time. During compilation, the type is fully resolved.

**URL to the documentation page (if already existing):**
https://docs.godotengine.org/en/stable/getting_started/first_2d_game/05.the_main_game_scene.html

**Comment by AThousandShips** [comment]
Cc @raulsntos

**Comment by raulsntos** [comment]
The comment is not meant to explain how `var` works. It's just saying that, since the type of the variable is clear (because the type appears later in the line), then you can use type inference here instead of repeating the type name. This is just about code style, different code bases will have different preferences, for example:

```csharp
Mob mob = new Mob();
var mob = new Mob();
Mob mob = new();
```

All of the previous lines are equivalent, so it's up to personal preference which one you prefer.

What I'm trying to say is that you are right about how `var` works, but I don't see how that's contradictory with the comment. Maybe the comment could be reworded if you think it's confusing, but keep in mind the Godot documentation is not meant to explain how C# works and we'll probably want to keep the comment concise.

**Comment by devingoble** [comment]
My only concern with statements like that are that I'm used to seeing that kind of stuff taken literally. The game industry seems more prone to accepting apocryphal descriptions of how to write performance code.

Anyway, thanks for having a look.

**Comment by paulloz** [comment]
My two cents (even if not asked for :v:). I don't really see how the comment could be read as "`var` means dynamic typing". At the same time, I don't understand why this comment is here altogether. We talk quickly about this topic in the [style guide](https://docs.godotengine.org/en/stable/tutorials/scripting/c_sharp/c_sharp_style_guide.html#implicitly-typed-local-variables), where IMHO it has its place. But it seems very random here in one code snippet in the middle of a tutorial. We even use `var` without saying a thing in earlier pages of the same tutorial. Feels quite odd.
