### ISSUE TITLE
Meaningless sentence in `String.capitalize`'s description

### ISSUE THREAD

**Issue by mieldepoche** [godotengine/godot-docs#8043]
**Your Godot version:** 4.1.1

**Issue description:**

![image](https://github.com/godotengine/godot-docs/assets/71937306/6a576eba-3e93-4648-9de4-9d82b379f78a)

**URL to the documentation page:**
https://docs.godotengine.org/en/stable/classes/class_string.html#class-string-method-capitalize

**Comment by skyace65** [comment]
@mickeon this was a change from when you overhauled string documentation [here](https://github.com/godotengine/godot/pull/68838). The note doesn't make sense to me either. Based on the method description I wouldn't expect it to capitalize fps and give you "FPS", I'd expect it to create "Fps". Is there something we're missing?

**Comment by Mickeon** [comment]
I remember seeing an user that was confused by this behaviour. Unfortunately you'd have to take my word for it because it has been way too long to find it.

What OP is pointing out is a missing "is", which is my typical oopsie.

The note felt important at the time, but do say if it could safely be removed. It is information that you can infer by reading the steps, but some Godot users may misunderstand this as working the way the editor does.
