### ISSUE TITLE
"Your first 2D game" skips over "Create new project" window

### ISSUE THREAD

**Issue by Stevoisiak** [godotengine/godot-docs#8554]
**Your Godot version:** 4.2

**Issue description:**
In the Getting Started documentation for Your First 2D game, the page on Setting up the project says to create a new project. The tutorial skips over the "Create New Project" screen.

![image](https://github.com/godotengine/godot-docs/assets/1330770/1a2af13b-918d-43c2-8f68-1442ac18f8e1)

Most of the options seem fairly straight-forward to explain, with the exception of Renderer. The default option is set to Forward+, but the description says it has slower rendering of simple scenes, which as a new user made me question if Mobile or Compatibility should be used instead.

**URL to the documentation page (if already existing):**
https://docs.godotengine.org/en/stable/getting_started/first_2d_game/01.project_setup.html

**Comment by AThousandShips** [comment]
As it says you're expected to have read the "Step by Step" guide, which in turn expects you to have read "Introduction", which goes over how to do this

**Comment by ericlathrop** [comment]
I ran into this missing information. It was confusing because the path box told me to pick an empty folder, and I typed one, but it complained it didn't exist, so I pressed "create project" but it did nothing. I had to put an existing folder in the path box, and press "create project" even though the path box had a red complaint. And It created a folder named after the title, which was in title case, but I wanted to folder to be lower cased with dashes, different from the title.

Plus picking a renderer was confusing because I don't know if I'm locked in if I pick the wrong one.

**Comment by skyace65** [comment]
Closing this per AThousandShips comment. We should not be repeating information that's already gone over in earlier parts of step by step which the documentation tells you to read first. In addition the page explicitly tells you to leave the default settings alone for this project, there's nothing to clarify.
