### ISSUE TITLE
Document supported texture types for decals

### ISSUE THREAD

**Issue by Grix** [godotengine/godot-docs#8614]
**Your Godot version:** 4.2

**Issue description:**

In the documentation, Decals are described as projecting Texture2D onto meshes, and this led me to believe that it supported any Texture2D. This is not the case, for example MeshTexture is not supported despite giving no error when attempted, as seen in this issue: https://github.com/godotengine/godot/issues/77564

The documentation page for Decals should specify what kinds of Texture2D's are supported, alternatively if MeshTexture is the only type that is not supported then perhaps this should be specified in its documentation instead.

**URL to the documentation page (if already existing):**

https://docs.godotengine.org/en/stable/classes/class_decal.html

https://docs.godotengine.org/en/stable/classes/class_meshtexture.html

**Comment by clayjohn** [comment]
We track class reference documentation issues in the main repo. Which is why we didn't move https://github.com/godotengine/godot/issues/77564 into this repo. 

Its best for us to only have one issue report per issue. So I am closing this in favour of https://github.com/godotengine/godot/issues/77564
