### ISSUE TITLE
Using signals timer tutorial

### ISSUE THREAD

**Issue by GameKhan13** [godotengine/godot-docs#8672]
v4.2.stable.official [46dc27791]

Timer has no variable timeout. instead use the signals connection timeout() function in the node menu.

this is the code shown:
```
func _ready():
	var timer = get_node("Timer")
	timer.timeout.connect(_on_timer_timeout) #<- this line is the problem
```

https://docs.godotengine.org/en/stable/getting_started/step_by_step/signals.html#

**Comment by jynus** [comment]
Hello, @GameKhan13 Thanks for your report. I cannot reproduce any issue with the given code. I have created a simple scene with a timer named "Timer" and set it to `autostart` and `one_shot`, like this:

```
extends Node2D

# Called when the node enters the scene tree for the first time.
func _ready():
	var timer = get_node("Timer")
	timer.timeout.connect(_on_timer_timeout) #<- this line is the problem

# Called every frame. 'delta' is the elapsed time since the previous frame.
func _process(delta):
	pass

func _on_timer_timeout():
	print("Timer and its signal timeout worked!")
```

The scene worked to me as expected:

```
Timer and its signal timeout worked!
--- Debugging process stopped ---
```

While timer has no variable timeout, it has a signal with that name ( https://docs.godotengine.org/en/stable/classes/class_timer.html#signals ), and that is the correct syntax to connect it by code in Godot 4 (it was a different syntax in Godot 3): https://docs.godotengine.org/en/stable/getting_started/step_by_step/signals.html#connecting-a-signal-via-code

Given it is on a section about connecting signals with code, I think it is appropriate to show how to do it like it is currently on the manual, rather than through the Nodes panel in the Editor.

Let me know if I am misunderstanding your report, otherwise to resolve this issue.

**Comment by skyace65** [comment]
Jynus and the existing code are correct. I'm going to guess you assume `timeout` doesn't exist for `timer` because it doesn't show up in autocomplete. The reason it doesn't show up is because `get_node()` is how it's connected to the script. If you actually run the code it will work.
