### ISSUE TITLE
Cross-language scripting documentation is confusing for beginners

### ISSUE THREAD

**Issue by TBlazeWarriorT** [godotengine/godot-docs#8898]
**Your Godot version:**
3.6

**Issue description:**
In short, the documentation page never directly mentions you can just directly access existing c# nodes without using load() and .new(), nor that using these can cause some functions to break.
The doc only mentions 
```
var my_csharp_script = load("res://path_to_cs_file.cs")
var my_csharp_node = my_csharp_script.new()
```
"Again, calling C# methods from GDScript should be straightforward. "
```
my_csharp_node.PrintNTimes("Hello there!", 2) # Hello there! Hello there!
```

This is bad because my_csharp_node.Something() will return constant null errors if that function has references to nodes that were declared from that script.
For example, if `LineEdit lineedit` is declared and fetched with GetNode() in C#, then lineedit.Text is printed on Something(), it will throw
C# (works only if called from itself)
```
LineEdit lineEdit;
public override void _Ready() {
    lineEdit = GetNode("myLineEdit") as LineEdit;
}
```
GDScript
```
    var csharp_main = load("res://Main.cs")
    var csharp_node = csharp_main.new()
    func _ready():
	csharp_node._Ready()
```
```
E 0:00:01.008   get_node: (Node not found: "myLineEdit" (relative to "Control").)
  <C++ Error>   Method failed. Returning: nullptr
  <C++ Source>  scene/main/node.cpp:1494 @ get_node()
  <Stack Trace> Node.gd:8 @ _ready()
```
Even if LineEditNode was a valid path and would work normally if called through that class itself. GetNode() simply behaves differently when called through GDScript on a new() node (I don't know if it's a bug or not, that's for a different issue that would require more investigation. Maybe it also breaks when called through a different C# class) and the documentation induces you to using it, leading you to a vague and misleading error.
It took me several hours of pure confusion to finally figure out I could and should just point to an existing node, completely ignore the load() and new() the documentations implies I should use, and just use my functions without null errors.

All of this could be avoided with a simple example somewhere on the page that would go something like this:

///
### Calling C# functions from an existing node through GDScript:
```
onready var csharp_node = $"../MyCsharpNode"
func _ready():
	csharp_node.MyCSharpFunction()
```
///

Yes, I know it was very likely just user error and my lack of knowledge causing the issue, but I went through the documentation exactly to figure out what I was doing wrong and how I should do it, and did not find it.

**URL to the documentation page (if already existing):** https://docs.godotengine.org/en/3.6/tutorials/scripting/cross_language_scripting.html

**Comment by paulloz** [comment]
Hi 🙂 I'm the person who initially wrote this page, and the overall structure didn't really change since. I kinda dislike it, a lot of sentences are weird, so I agree it could be way better. That being said, I'm quite confused by what you are saying. 

> the documentation page never directly mentions you can just directly access existing c# nodes without using load() and .new()

`load()` and `new()`, by definition, would create new instances of those nodes, not access existing ones.

> The doc only mentions
> 
> ```
> var my_csharp_script = load("res://path_to_cs_file.cs")
> var my_csharp_node = my_csharp_script.new()
> ```

Yes, we mention that in the "Instantiating nodes" section. Again, instantiating a node ≠ retrieving a node. The former creates a new one, the latter does not.

> "Again, calling C# methods from GDScript should be straightforward. "
> 
> ```
> my_csharp_node.PrintNTimes("Hello there!", 2) # Hello there! Hello there!
> ```
>
> This is bad

That is in an entirely different section named "Calling methods". Sections / chapters aren't sequential steps to follow, they indicate different topics. I'm unsure if this is unclear, or how we could make it better here.

> because my_csharp_node.Something() will return constant null errors if that function has references to nodes that were declared from that script.

This simply happens because you've created a new instance, probably didn't insert it in the tree, and now try to use tree references with it. This is not related to the content of the page, the same thing would happen if you did the same from GDS with another GDS script, or from C# with another C# script.

I feel like it burns down to "the page should explicitly say it's possible to call `get_node` on a node, whatever its attached script is"? Which... Might be fair? To me, it seems out of scope for this page. 

Let me know if I misunderstood your original message.

**Comment by TBlazeWarriorT** [comment]
> Yes, we mention that in the "Instantiating nodes" section. Again, instantiating a node ≠ retrieving a node. The former creates a new one, the latter does not.

Yes, now I see it was my fault for not realizing instantiating would never access the original one, simply because it is never even mentioned
> This simply happens because you've created a new instance, probably didn't insert it in the tree, and now try to use tree references with it. This is not related to the content of the page, the same thing would happen if you did the same from GDS with another GDS script, or from C# with another C# script.

I had no idea inserting it on the tree was a thing, probably for being new to Godot. It's just that it was never even hinted that there were additional steps to make calling a function work. The doc said it was straight forward, so in my head, if I just called a function anywhere, it would work, which wasn't the case with GetNode() and this whole topic I'm yet to figure out. I'm not sure if my confusion makes sense, and I'm not entirely sure if I can suggest the doc to babysit people through the process in the right direction.
But in short, I do think it could be handy to make at least a brief mention that existing nodes can simply be accessed from one language to the other and functions can be called without instantiation or any setup, which I thought was required, even if it is just a simple line somewhere.
(In fact, I'm still in the process of figuring out how to call GDScript functions from C# and I struggle to explicitly find this somewhere, but it's probably my fault again and I'm sure I can figure this part out on my own now - I'm referring to this part of code but in C#:)
```
onready var csharp_node = $"../MyCsharpNode"
func _ready():
	csharp_node.MyCSharpFunction()
```
> Let me know if I misunderstood your original message.

But overall I do think you got it right, it was just me missing the implicit obvious things, except I still think at least one mention that stuff just works out of the box and nodes can be accessed should have existed.
And thanks for the reply and attention either way

**Comment by paulloz** [comment]
> how to call GDScript functions from C# and I struggle to explicitly find this somewhere

[This](https://docs.godotengine.org/en/3.6/tutorials/scripting/cross_language_scripting.html#calling-gdscript-methods-from-c) is the section you are looking for. 

> It's just that it was never even hinted that there were additional steps to make calling a function work.

Because the two topics (calling a method, and instantiating something) are unrelated. Creating a new node here is not an additional step, it’s something that one shouldn’t/wouldn’t be doing. IMHO it is not possible for every page to reintroduce everything. I think in most pages, the reader is expected to be somewhat comfortable with the fundamentals of Godot.

I guess we could extend the context of the current examples to include the `get_node(…)` lines. On the other hand, then someone might understand this as "well, all the examples follow `get_node(…)`, so that’s the only context where this is valid". That’s the rationale behind not showing where the reference comes from: in the context of what the page explains, it doesn’t matter where it comes from.

**Comment by TBlazeWarriorT** [comment]
I think that solves all my questions/concerns anyways, so ty again
I'll assume that I was the only person confused and consider the doc page good enough, unless someone else complains about it in the future, and I'll try to dig things better in the future.

**Comment by TBlazeWarriorT** [comment]
> [This](https://docs.godotengine.org/en/3.6/tutorials/scripting/cross_language_scripting.html#calling-gdscript-methods-from-c) is the section you are looking for.

Also I just remembered it actually is was with the implicit part that I was confused with, I remember trying to define the "var myGDNode" or "GodotObject myGDNode" or "Godot.Object myGDNode" and all 3 said it was an invalid type, so the only thing left I think was figuring out how to store the GDScript node reference on the code, which are pretty much the only part the doc doesn't cover and caused the entire topic of this

**Comment by paulloz** [comment]
> In fact even the example code for instantiating gives me an error of
> 
> ```
> [...]\Main.cs(15,2): 'Object' is an ambiguous reference between 'Godot.Object' and 'object'
> ```

What version of Godot are you using? I didn't realize that you linked the documentation page for 3.6, is this intended? If no, the stable version is [here](https://docs.godotengine.org/en/stable/tutorials/scripting/cross_language_scripting.html). If yes, the error you're relaying is only a shadowing issue, probably because you have both `using Godot;` and `using System;` at the top of your file. In which case, you'd need to fully qualify `Godot.Object` instead of simply writing `Object`. This should probably be done in the doc itself anyway.

**Comment by TBlazeWarriorT** [comment]
> > In fact even the example code for instantiating gives me an error of
> > ```
> > [...]\Main.cs(15,2): 'Object' is an ambiguous reference between 'Godot.Object' and 'object'
> > ```
> 
> What version of Godot are you using? I didn't realize that you linked the documentation page for 3.6, is this intended? If no, the stable version is [here](https://docs.godotengine.org/en/stable/tutorials/scripting/cross_language_scripting.html). If yes, the error you're relaying is only a shadowing issue, probably because you have both `using Godot;` and `using System;` at the top of your file. In which case, you'd need to fully qualify `Godot.Object` instead of simply writing `Object`. This should probably be done in the doc itself anyway.

I'm using Godot_v3.6-beta4_mono_win64. I was using 3.5.3 Stable but I had to upgrade because I wanted the button icon tint feature from the betas.
I think I finally reasonably understood everything on that documentation page now. And after looking at "Nodes and scene instances", I think I got the rest of what you meant. In the end, it was just me not knowing where to look for things, except for the ambiguous object thing you just mentioned.

In the end, the code I needed (and just figured out) was just this: (plus the existing one I mentioned in the end of my original post for gdscript to access C# which is a bit easier)
```
		Godot.Node _myGDScriptNode = (Godot.Node)GetNode("GD_Node");
		GD.Print(_myGDScriptNode.Get("some_tree_node_reference"));
```
But I had no idea how to reference existing nodes, the Godot.Object type was getting on my way of getting it working, and I was calling things the wrong way and not understanding the error message, to a point where I even started thinking what I was doing was not supported.
In the end, I'm really glad I've managed to figure it out, and you're surely helped me.

I honestly still think this would be a good quickstart example for beginners learning Cross-language scripting, but I have no suggestions as to *where* this example should be, if not on the main page. I also would have definitely been still confused as heck if you didn't point out that I had to AddChild() for my node to have full capabilities and be able to use GetNode().
