### ISSUE TITLE
TileMap's docs needs pointers to TileSet when looking up collision

### ISSUE THREAD

**Issue by dootMaster** [godotengine/godot-docs#8915]
4.21

While trying to help a dev interface with collision properties in TileMap, I felt there was no hint or pointer that the collision API actually belongs to *TileSet*. I think the first place devs trying to interface with collision would search is in TileMap, so maybe we should have some kind of pointer. 

TileMap should be updated so that there's at least a clue pointing to 

[Link to page.](https://docs.godotengine.org/en/stable/classes/class_tilemap.html)

**Comment by AThousandShips** [comment]
I'd say this is clear from the [linked tutorial](https://docs.godotengine.org/en/stable/tutorials/2d/using_tilesets.html#doc-using-tilesets)

**Comment by skyace65** [comment]
I agree with AThousandShips on this. I would expect collision data to be part of the ``TileSet`` based on that description. Plus assuming the collision data is part of the TileMap, and not the TileSet makes no sense. Since TileMaps are usually unique to scenes, while TileSets are used by multiple tile maps, why would the collision data be in the part that's not re-usable when it doesn't change? And even if I don't make that assumption the next logical place I'd check after not finding it in ``TileMap`` is in ``TileSet``.
