### ISSUE TITLE
Pressing back doesn't change heading

### ISSUE THREAD

**Issue by sockeye-d** [godotengine/godot-docs#9183]
**Your Godot version:** 4.3

**Issue description:**
Pressing back on the browser no longer moves page to previously visited heading on the latest docs version (for example clicking on a class documentation, then clicking on a method, then pressing back doesn't bring you back to the top), as it used to on the docs for 4.2.

**URL to the documentation page:**
All of them

**Comment by dangerman** [comment]
I had a look into this and it was introduced in 4.2 with https://github.com/godotengine/godot-docs/pull/9015

![godot-docs-stable](https://github.com/user-attachments/assets/ecb105db-0b38-4f98-aa5c-5baeefaca142)

You can still go between other HTML pages at least.

| Stable (4.2) | Latest (4.3 |
| -- | -- |
| ![godot-docs-stable](https://github.com/user-attachments/assets/ecb105db-0b38-4f98-aa5c-5baeefaca142) |  |

However, it's fixed in `latest`, probably by https://github.com/godotengine/godot-docs/pull/9622 which was for another bug introduced by the same PR.

**Comment by sockeye-d** [comment]
It does appear to be fixed so I'm closing the issue
