### ISSUE TITLE
Possible Small Typo under Compiling for OSX

### ISSUE THREAD

**Issue by MetaSaval** [godotengine/godot-docs#921]
In the Compiling for OSX doc, when talking about creating a .app file, the steps after compiling with the .app template are currently this:

```
> user@host:~/godot$ cp -r misc/dist/osx_tools.app ./Godot.app
> user@host:~/godot$ mkdir -p Godot.app/Contents/MacOS
> user@host:~/godot$ cp bin/godot.osx.opt.tools.fat Godot.app/Contents/MacOS/Godot
> user@host:~/godot$ chmod +x Godot.app/Contents/MacOS/Godot
```
However, when going through the commands on my mid-2014 MacBook Pro, the third step points to a .64 file, not a .fat file. As in, the third step should theoretically read:

`> user@host:~/godot$ cp bin/godot.osx.opt.tools.64 Godot.app/Contents/MacOS/Godot`

I'm new, so I don't know if these two things are functionally equivalent. Should this be changed?

**Comment by bruvzg** [comment]
It is not functionally equivalent.

".fat" binary contains both 32 and 64-bit code (can be built with `scons p=osx bits=fat`).
".64" binary contains only 64-bit code (built by default or with `scons p=osx bits=64`).

All macOS version after 10.6 are 64-bit exclusive and fat binaries are essentially useless.

Since 64-bit only build is default this should be changed.

**Comment by mhilbrunner** [comment]
Closed by https://github.com/godotengine/godot-docs/pull/942
