### ISSUE TITLE
"Creating the enemy" 2D tutorial page missing a step

### ISSUE THREAD

**Issue by NightIsland** [godotengine/godot-docs#9356]
**Your Godot version:**
4.2.2

**Issue description:**
The "Creating the enemy" page of the first 2D game tutorial asks the user to create a new scene with the RigidBody2D node: it then says to make any child nodes unelectable.

If you have followed the tutorial, the last action previously completed was editing a script; this will leave the Godot Editor UI in the 'Script' state, from where the 'Group Selected Nodes' command is not visible.  This step needs to inform the user that selecting the Editor's '2D' state is necessary to be able to find this button.

**URL to the documentation page (if already existing):**
https://docs.godotengine.org/en/stable/getting_started/first_2d_game/04.creating_the_enemy.html

**Comment by skyace65** [comment]
I'm hesitant to document this because people should be able to easily figure out they just need to change back to the 2D editor view. While I understand we need to be explicit, especially for a first game tutorial, this seems excessive. Especially since the idea that the toolbar changes between editors is something people should have noticed by this point already, and it's explained that the toolbar changes in the introduction section on this [page](https://docs.godotengine.org/en/latest/getting_started/introduction/first_look_at_the_editor.html#id1).

**Comment by NightIsland** [comment]
You’re not wrong, I should have noticed and remembered that part: adding “which is in the 2D view at the top of the editor” doesn’t seem like a particularly heavy explanation, but given this it’s not as egregious as I first thought.Feel free to close the issue if you want.On 12 May 2024, at 18:14, Matthew ***@***.***> wrote:﻿
I'm hesitant to document this because people should be able to easily figure out they just need to change back to the 2D editor view. While I understand we need to be explicit, especially for a first game tutorial, this seems excessive. Especially since the idea that the toolbar changes between editors is something people should have noticed by this point already, and it's explained that the toolbar changes in the introduction section on this page.
