### ISSUE TITLE
The tutorial demo on godot4 docs is version 3.5.

### ISSUE THREAD

**Issue by piraxis2** [godotengine/godot-docs#9412]
**Your Godot version:** 
4.2
**Issue description:**
I tried to get the godot tutorial and run it on godot 4.2, but the version is different
**URL to the documentation page (if already existing):**
https://godotengine.org/asset-library/asset/111

![image](https://github.com/godotengine/godot-docs/assets/47844565/bc1b0002-129f-429a-9376-bf146e17f6a2)

**Comment by skyace65** [comment]
This, and every other demo link was fixed by this engine PR https://github.com/godotengine/godot/pull/90310. The change isn't going to be backported to the 4.2 branch as far as I'm aware, but once 4.3 is released all links on the website should point to the new demo projects on the asset library. In the meantime you can change the version of the docs you're reading to "latest" and that will give you the updated links. Also, here is the specific demo project you were looking for https://godotengine.org/asset-library/asset/2717
