### ISSUE TITLE
Incorrect reference in C# documentation

### ISSUE THREAD

**Issue by jdsutton7** [godotengine/godot-docs#9415]
**Your Godot version:**
v4.2.2.stable.mono.official

.NET version 8.0.300

OS: Linux Mint 21.3 x86_64

**Issue description:**
Documentation here is not up to date: https://docs.godotengine.org/en/stable/classes/class_time.html

For example: the documentation refers to "Time.get_ticks_msec()", but "Time.GetTicksMsec()" is correct.

**URL to the documentation page:**

If you know how to fix the issue you are reporting please
consider opening a pull request. We provide a tutorial on
using git here: https://docs.godotengine.org/en/stable/community/contributing/pr_workflow.html,
writing documentation at https://docs.godotengine.org/en/stable/community/contributing/docs_writing_guidelines.html
and contributing to the class reference here: https://docs.godotengine.org/en/stable/community/contributing/updating_the_class_reference.html

**Comment by raulsntos** [comment]
The class reference uses the GDScript syntax, so you'll see all methods in `snake_case` rather than `PascalCase`. You'll have to translate the method names you find. A properly configured editor can you help find the right method through autocompletion. Also be aware of other [_C# API differences to GDScript_](https://docs.godotengine.org/en/stable/tutorials/scripting/c_sharp/c_sharp_differences.html) that you may want to know about when reading the class reference.

**Comment by skyace65** [comment]
Closing per raulsntos' comment.
