### ISSUE TITLE
Add AstarGrid2D to 2D Navigation Overview?

### ISSUE THREAD

**Issue by shak2** [godotengine/godot-docs#9668]
**Your Godot version:**
NA

**Issue description:**

This page:

[https://docs.godotengine.org/en/stable/tutorials/navigation/navigation_introduction_2d.html](https://docs.godotengine.org/en/stable/tutorials/navigation/navigation_introduction_2d.html)

Does not contain a headline with detail of this important (new?) node:

[https://docs.godotengine.org/en/stable/classes/class_astargrid2d.html](https://docs.godotengine.org/en/stable/classes/class_astargrid2d.html)

I am new to pathfinding, so maybe there are other new 2D and 3D navigation nodes that are missing in the 2D and 3D pathfinding/navigation docs pages.

Please check and update as this is important information for completeness of these pages.

**URL to the documentation page (if already existing):**

NA

**Comment by tholan2** [comment]
I'd like to claim this issue if possible, as it seems like a good issue to resolve for a school assignment I've been working on. 
To be clear, the issue is asking for a short description of AstarGrid2D in the 2D Navigation page similar to the sections describing AStar2D and NavigationServer2D, if I'm reading this correctly.
Assuming I'm correctly understanding the problem, I feel confident I could fix this issue within the next month.
