### ISSUE TITLE
Screenshots in README in godotengine/godot are outdated

### ISSUE THREAD

**Issue by mak448a** [godotengine/godot-docs#9765]
**Your Godot version:**
N/A
**Issue description:**
The screenshot is still using Godot 3.x on the main README at https://github.com/godotengine/godot
**URL to the documentation page:**
https://github.com/godotengine/godot/blob/master/README.md

**Comment by AThousandShips** [comment]
I don't think the screenshot being of 4.x is that important, it's not part of any documentation so it's not relevant for functionality

**Comment by mak448a** [comment]
Where should I open this?

**Comment by tetrapod00** [comment]
Since it's about the [main repo](https://github.com/godotengine/godot/issues)'s readme, you could file an issue there.

I do agree this is pretty low priority, since the image in the godot repo is not going to make or break anyone's opinion of the engine. But it would be nice to fix! If you want to recreate the screenshot in 4.3, it uses [this demo project](https://github.com/godotengine/tps-demo).

**Comment by mak448a** [comment]
The main repo only has options for bugs about the engine. How can I file a bug there? Ignore that?

**Comment by tetrapod00** [comment]
Bug seems closest to me, I guess. It's not a whole feature proposal.

**Comment by Calinou** [comment]
Closing in favor of https://github.com/godotengine/godot/issues/95761.
