### ISSUE TITLE
simple 2D game, "invalid get index 'y.'"

### ISSUE THREAD

**Issue by Reizenchuu** [godotengine/godot-docs#991]
Hello,
so I'm new to Godot and have started following the documentation not too long ago. when I arrived at the simple 2d game example, I got the following error: "invalid get index 'y' (on base Rect2)".
I thought I did everything as it was supposed to be, so I have no idea about the way to deal with this.
could someone please give me some hint?
![2018-01-19 16_47_36-](https://user-images.githubusercontent.com/35606908/35172301-faad9b58-fd5e-11e7-930b-d9a6c5604e5e.png)

**Comment by cbscribe** [comment]
FYI, Github issues are for reporting problems with the documentation site and its content. They are not for technical support with your own projects. Please use the [QA Forum](https://godotengine.org/qa/) or the [Discord](https://discord.gg/zH7NUgz) if you need help.

That said, your problem is that you've set `screensize` to a Rect2 (`get_viewport_rect()`) on line 19, so on line 30 when you say `screensize.y` you get the error shown. Line 19 should be `screen_size = get_viewport_rect().size`
