### ISSUE TITLE
Clearer documentation 

### ISSUE THREAD

**Issue by Jaldvox** [godotengine/godot-docs#9988]
**Your Godot version:**

**Issue description:**

**URL to the documentation page (if already existing):**

Hello, greetings from Spain, my main account has been blocked, I went to the website and read the code of conduct, and I don't think it's good publicity to discriminate against Spanish, since at the level of scalability, it's not very good for an open source project, I think the more Spanish community the better, I only shared a code, and it wasn't accepted because it didn't make sense to add it, okay, no problem, but it wasn't something to get into, I just joined the godot community, and I understand that in open source you talk and debate and you don't get banned just by meeting you, anyway, I hope we can debate this matter, and not just get banned.

**Comment by akien-mga** [comment]
Hi, I assume you refer to this PR: https://github.com/godotengine/godot-docs/pull/9987

Your account as been blocked because of the use of AI generated replies, which made it look like a spam bot, or at the very least a low effort contribution.

The code itself in the PR also didn't make much sense, as it's copy-pasting the whole file contents into a multiline comment to translate a few sparse comments in Spanish. Copy-pasting code is not a useful contribution, and if we wanted to provide Spanish comments, it's also not the right way to do it. It definitely doesn't match what the AI generated replies claim that the PR does (it's not making code more organized).

To be clear, your account wasn't blocked due to the use of Spanish, or the desire to translate content in Spanish. It was blocked for unproductive use of AI generated text to justify a PR which technically doesn't make sense, making the account look like a bot.

Now, since you made a new account to appeal this, I unblocked your main account. But please avoid the use of AI for engaging in this repository:
- AI makes things up, and so its description of what your code does doesn't match reality. This wastes contributors' time and makes it unclear whether you yourself understand what your code change is doing.
- AI generated code (I don't know for sure if you used AI for the code part, so just mentioning it for clarity) is also problematic because it often means that the author of the PR isn't actually the author of the code, and may not understand what it does. We need code author to understand what they're doing to ensure that we can have useful contributions. Furthermore, AI generated code is often trained on copyrighted material and may lead to copyright infringement, possibly without you even knowing.

**Comment by Jaldvox** [comment]
I understand, so from what you're telling me, it's not good to learn programming with the available AIs either? I say this because Python excites me, and I want to specialize in code modulation. But I didn't know about copyright, thanks for telling me. I will try to learn and customize my code from now on, but... how can I know if the code is copyrighted?

**Comment by akien-mga** [comment]
>  how can I know if the code is copyrighted?

You can't really know, unless the code generated by the AI tool has something obvious like "Copyright (C) some name"... which sometimes happens, because it learned from existing codebases and thus also learned their copyright and license statements... or sometimes it can give you very specific names for functions or variables which seem highly project specific like `quake3_matrix_projection` :)

As a general rule, if you use AI as an aid to learn programming, I would suggest not using what it generates out of the box. Use it instead as an example to learn from, test it, confirm that it works, and then make your own version that you 100% understand. It's a gray area, but in general it's ok to learn from (short) code snippets, even if they're under copyright, as long as what you learn is how they make use of open source APIs, and not how to reproduce a proprietary algorithm that's specific to the codebase it was stolen from by AI companies.

**Comment by Jaldvox** [comment]
I don't know if it was understood well, but I meant to say that I will make the code more my own, before I start trying to help, to make sure that I help and that I don't harm.

**Comment by aaronfranke** [comment]
@Jaldvox If you are interested in learning programming, *do not use AI to do it*. AI is helpful for automating things after you already know what you are doing, but if you try to learn by using AI suggestions, you will learn nothing. Except for some cases of really common things (like "generate a quicksort function" or "explain how quicksort works"), the output AI gives you is likely to be wrong and must be manually reviewed. If you are not experienced enough to review code generated by AI, then you need to learn to code without AI first so that you gain that experience before you can use AI to help you.

**Comment by AThousandShips** [comment]
> how can you know if they really listened to you or if they are lying to you?

You can't, AI can't lie or anything, but it doesn't "understand", large language models are just a much more advanced version than the suggestions when you type in your phone, it "guesses" what word goes next

There's no guarantee that what it outputs is valid, or even good code, or the origin

**Comment by Jaldvox** [comment]
> > how can you know if they really listened to you or if they are lying to you?
> > You can't, AI can't lie or anything, but it doesn't "understand", large language models are just a much more advanced version than the suggestions when you type in your phone, it "guesses" what word goes next > > There's no guarantee that what it outputs is valid, or even good code, or the origin thank you very much.,! time to keep learning.
